### ISSUE TITLE
AccordionPanel does not work correct using LoadableDetachableModel<List<? extends ITab>>

### ISSUE THREAD

**Issue by Patrick1701** [sebfz1/wicket-jquery-ui#112]
Hi Sebastien,
I implemented an Accordion using the Accordion-constructor for IModel<List<? extends ITab>> and give a LoadableDetachableModel implementation to provide AjaxTabs.

The detaching-feature of the LDM, let the Accordion call getObject() twice.
The first on AccordionPanel#onInitialize() and the second later on Ajax-Create-event of the AccordionBehavior.

Due to that, the ITabs loading state doesnt match anymore (caused by another "new" tab instance), and the first AjaxTab never get loaded, because it is still in INIT_STATE.

Overriding detach() of my LDM, doing nothing, can fix this.

After this I tried to implement a BasicModel/Model not to have detaching-logic, but I did not get this compiled because the Model-generic type must be T extends Serializable, and the constructor of AccordionPanel only provides IModel<List<? extends ITab>>. I wasn't able to implement a serializable list of ITabs.
Also tried ListModel... but I did not get it compiled.

Is there any trick?

Back to the LDM... is this a bug? Or just a javadoc issue?

kind regards
Patrick

**Comment by Patrick1701** [comment]
Hi Sebastien,
happy new year! :-)

I'm working again on TabbedPanels which dynamically create tabs depending on some other components on a page and database data, I still run into this issue we discussed in this thread.

After several implementations of this TabbedPanel I've done the last months which uses LDMs, I more and more think about the wish to have a more non-static version of this Component.

As far as I can see, the Tabs are quite "static" due to the fact, they are added to the internal ListView in ```onInitialize()``` of ```TabbedPanel```.
So, its it possible to fetch tabs from a model, but only once the TabbedPanel is created, but never again in its Lifecycle.

I can manipulate Tabs by using ```add(ITab)```... this is helpfull for an "add tab"-use-case but, not for fetching them modeled from a database.

Additionally to my hack above, not to detach my TabList-LDM, I force a re-initialized TabbedPanel by using another workaround (lifecycle-break):

```
onSomething(AjaxRequestTarget target){
  surroundingContainer.addOrReplace(new TabbedPanel("p", LDM-for-tabs, new Options()));
  target.add(surroundingContainer);
}
```
instead of just

```
onSomething(AjaxRequestTarget target){
  target.add(tabbedPanel);//(does not re-render tabs right now)
}
```

I'm not sure if I request some sort of non-natural feature/behavior for TabbedPanels, but I have this situation quite often.

Possibly adding the tabs in ```onBeforeRender()```, not in ```onInitialize()``` could achive this, but I'm not sure.

What do you think?

best regards
Patrick

**Comment by sebfz1** [comment]
Hi Patrick,

Thank you very much, happy new year to you too! :)

`ITab`(s) are static for the reason they should keep their state (that's the reason not using a LDM). I can try to study how we can have a dynamic model... I just will ask you a little bit of more patience, everything will go back to a normal situation by the end of the month (crossing fingers)... 

Thanks & best regards,
Sebastien.

**Comment by Patrick1701** [comment]
>I just will ask you a little bit of more patience, everything will go back to a normal situation by the end of the month (crossing fingers)... 

Ok, good luck! :-)

( I hope you don't feel bothered, when I go on opening further issues... ;-) )

best regards
Patrick

**Comment by sebfz1** [comment]
I will try to spend time on this this week-end, sorry for the delay! :)

**Comment by sebfz1** [comment]
Hi Patrick,

> I can try to study how we can have a dynamic model...

So, I've added a `TabListModel`, which is a loadable (non detachable) model. You can use it for your dynamic `List<ITab>` which contains `AjaxTab(s)`.

Please note: in order to refresh the `Accordion` (and reload the model), please use `AccordionPanel#refresh` (instead of `target.add(accordion)`). If you cannot refresh the `Accordion` directly, call `myTabListModel.flush();` then `target.add(myAccordionContainer)`

Deployed `6.19.2-SNAPSHOT`

Best regards,
Sebastien,

**Comment by Patrick1701** [comment]
Ok, I will check that next, when I am upgrading...

Thanx a lot.
Patrick

**Comment by Patrick1701** [comment]
Hi Sebastien,
works great!

kind regards :-)
Patrick
