### ISSUE TITLE
Dialogs / Suggestion concerning "Warning with nested forms!"

### ISSUE THREAD

**Issue by Patrick1701** [sebfz1/wicket-jquery-ui#129]
Hi Sebastien,
I think, I have a solution for your warning...

I am often working with dialogs as part of other forms, and what I do is, disabling the dialogs form I have to provide to the AbstractFormDialog on construction time and enabling/disabling it onOpen and onClose time.

```
MyDialog() extends AbstractFormDialog<...>{
  this.form = new Form(...);
  this.form.setEnabled(false);
}
onOpen(...){
  super.onOpen();
  this.form.setEnabled(true);
}
onClose(...){
  super.onClose();
  this.form.setEnabled(false);
}
```

This works pretty well... (I experienced).
Maybe you can implement this as a default feature of your AbstractFormDialog?
(but you should have a deeper look; not sure if I consider every case, here it seems to work good)

kind regards :-)
Patrick

**Comment by Patrick1701** [comment]
Hi Sebastien,
I am not really sure anymore, what I should or wanted to test. ;-)

So... hmm... here we commonly override any ```onOpen(AjaxRequestTarget target)``` (and close) of any ```AbstractFormDialog```
```
@Override
public void onOpen(AjaxRequestTarget target){
  getForm().setEnabled(true);
  target.add(getForm());
}
@Override
public void onClose(AjaxRequestTarget target, DialogButton button) {
	getForm().setEnabled(false);
	target.add(getForm());
}
```
to avoid having not opened dialogs or canceled/closed dialogs being validated, if they are children of an other page-form.
Its kind of best practice here and we did not encoutered any other problems, yet.

But, I'm still not able to evaluate consequences concerning the outer-form-use-case you mentioned above.
So... for me this feature would be nice and "save" as far as I can see.

kind regards
Patrick

**Comment by sebfz1** [comment]
Hi Patrick,

> But, I'm still not able to evaluate consequences concerning the outer-form-use-case you mentioned above.

I think it will cause an issue with outer form like for `ConfirmAjaxButton`... Imagine you have a form with a Save (common) button and a Delete (confirm) button. If the Delete button disables the (parent) form, then all form sub-components will be disabled, including the Save button itself...

I think the way you are using it is correct, but I am not sure I can reflect the change in `AbstractFormDialog` directly... I will try to think a little bit more about this "nested form" issue.

>  minor addition note: if target.add(getForm()); is always be necessary; I'm not sure about that...

Yes, in your case - or if you change the dialog's model object - it is necessary...

Best regards,
Sebastien.

**Comment by Patrick1701** [comment]
Hi Sebastien,
today I had the chance to play around with that again... so, here a short feedback / note.

>minor addition note: if target.add(getForm()); is always be necessary; I'm not sure about that...

>>Yes, in your case - or if you change the dialog's model object - it is necessary...

It seems, just to prevent the validation in closed state of the form-dialog, there is no need to add the dialogs form to the ajax request target again.
The enabled-false-state of the form is kept server-side and wicket pays attention to that, when an outer form e.g. a wizard submits its outer form.
So re-rendering the dialog form is not "really" needed... because of the closed dialog, no user "needs" to see the disabled form fields, its invisible anyway. ;-)

best regards
Patrick

**Comment by sebfz1** [comment]
Hi Patrick,

Thanks for your feedback!

> It seems, just to prevent the validation in closed state of the form-dialog, there is no need to add the dialogs form to the ajax request target again.

In `#onClose`, yes that's true.

> The enabled-false-state of the form is kept server-side and wicket pays attention to that, when an outer form e.g. a wizard submits its outer form.

Also true, that's why it is not applicable for `ConfirmAjaxButton` for instance, because the form *is* the outer form... :)

Given our discussion and your tests, do we agree it is up to the user to handle this "form" usecase himself, meaning it cannot be handle automatically in [Abstract]Dialog side? Or did I missed something in your explanation? If we are clear on that, I think we can close this issue... :)

Thanks & best regards,
Sebastien.

**Comment by Patrick1701** [comment]
Hi Sebastien,
yes, it can be handled by the user, but you should give a "best practice" hint nearby where your "Warning with nested forms!" is on your example page.
Or at the point, where you also mention the issue "onOpen() target add any panel" to let the dialog reflect the current model object.

For new users, the AbstractFormDialog appears quite limited due to "nested forms warning", and for a wicket newbee, getting into this situation, having a closed form dialog (accidently or not) contained in a form of a page, he gets confused by the validation error of the dialogs form, because there "is nothing" in view. (I guess this will probably only happen, when someone uses a wicket wizard, caused by the implicit featured form).
You need to be experienced, to find the solution enabling/disabling the form in onOpen() / onClose() manually.

So, anyway. Its ok for me... :-) was just an idea. :-)

best regards
Patrick

**Comment by sebfz1** [comment]
Hi Patrick,

Thanks to WICKET-5889 (and my new super powers ;)), it will now be easy to handle a form-based dialog in a parent form...
Starting from next version (6.20 & 7-M6/7.0 you will be able to prevent submission of a nested form when the parent form is submitted:

```java
Form<?> form = new Form<Void>(id) {

	@Override
	protected boolean wantSubmitOnParentFormSubmit()
	{
		return false;
	}
};
```

Best regards,
Sebastien

**Comment by Patrick1701** [comment]
Hey cool,
I like your new super-powers. :-D

Ok, but having it as override-feature, its still needed to define that by myself. So, its a recommendation to do that when using an ```AbstractFormDialog```, but not implicit featured by ```AbstractFormDialog```, right?

best regards
Patrick :-)

**Comment by sebfz1** [comment]
Hi Patrick,

>  So, its a recommendation to do that when using an AbstractFormDialog, but not implicit featured by AbstractFormDialog, right?

Right, because `AbstractFormDialog` does not hold the form, so you define it the way you want, depending on if it's an inner form or it you refer to a parent form...

Best regards,
Sebastien.
