### ISSUE TITLE
Add SplitButton component

### ISSUE THREAD

**Issue by jchappelle** [sebfz1/wicket-jquery-ui#130]
I would like to request adding a SplitButton class that wraps the following jquery-ui component.
http://jqueryui.com/button/#splitbutton

The main features needed would be the ability to set the button text via a model and specify onclick behavior for the main button as well as the items in the dropdown.

**Comment by sebfz1** [comment]
Hi @Patrick1701 ,

Some news about this?

Thanks,
Sebastien.

**Comment by Patrick1701** [comment]
Hi Sebastien,
it does not have a reeeeal good state, yet.

I have some hovering (z-index) issues with dialogs etc pepe. and would like to fix them first.
If I'm not able to fix that, maybe you could help me? :-D

(but first I would like to have a clean state concerning #116 / working on too much different things. *confused*)

Patrick

**Comment by sebfz1** [comment]
Hi Patrick,

Sure, I can help if you need. You can commit in a separated branch in your repo (no need to create a PR, I can get your update from your repo directly...)

Best regards,
Sebastien.

**Comment by Patrick1701** [comment]
Hi Sebastien,
I created a pull request (#156).

kind regards
Patrick

**Comment by sebfz1** [comment]
Deployed `6.19.1-SNAPSHOT`
