### ISSUE TITLE
AbstractFormDialog leaves blue rectangle onClose

### ISSUE THREAD

**Issue by DanielaL** [sebfz1/wicket-jquery-ui#135]
Hi Sebastien,
I have a problem with a dialog which extends AbstractFormDialog:
Closing the dialog on a tablet with Android Browser leaves a transparent blue rectangle artifact where the dialog was until the user clicks anywhere. This happens only in the native Android Standard Browser no other browser.
I tryed to refresh the parent window in the onClose method with target.add(parentWindowForm);
but this doesn't help. I also tryed to add "outline: 1px solid transparent;" like suggested here http://stackoverflow.com/questions/12348884/jquery-ui-draggable-element-leaves-weird-traces-in-chrome, but this didn't help either.
Have you any idea what could remove these artifacts?
Best regards and many thanks in advance.
Daniela

**Comment by sebfz1** [comment]
Hi Daniela, any update on this? Does it still repro?

**Comment by DanielaL** [comment]
Hi Sebastien, unfortunately no news here I tried to solve the problem by updating the browser on the tablet, but the rectangle doesn't disappear. For the moment I asked the customer to use another browser on the tablet but that isn't really a solution...

**Comment by sebfz1** [comment]
Daniela,

I will close this issue as I think it is not on my hands, but rather on jquery ui side.
Do not hesitate to reopen it if you think I can do something...

Thanks & best regards,
Sebastien.
