### ISSUE TITLE
Calendar is broken in FF Win7/8

### ISSUE THREAD

**Issue by solomax** [sebfz1/wicket-jquery-ui#138]
Hello Sebastien,

Wicket Calendar component is broken if FF (31, 34) if used on Win7/8 machine (works as expected on virtual machine, broken in case of "real" PC)

Steps:
1) open http://7thweb.net/wicket-jquery-ui/calendar/ExtendedCalendarPage
Result: only few events are displayed
2) Create event on any date
Result: event is not displayed
3) open same page in Chrome/IE browser
Result: all events are displayed as expected

related issues: https://issues.apache.org/jira/browse/OPENMEETINGS-1131

reproducible with both 6.17.0 and 6.18.0

Not sure but maybe fullcalendar version might be upgraded to address this? (current version is: 1.6.4, latest version: 2.2.3 http://fullcalendar.io/download/)

this issue is showstopper for us, so I will provide as much help as possible to fix it

Thanks in advance!

p.s. only monthly view was tested

**Comment by solomax** [comment]
Hello Sebastien,

sorry bothering ... but what about wicket-7 version? :)))

**Comment by sebfz1** [comment]
Hi Maxim,

IIRC, wicket 7.0.0 should be released this month, so I would be able to
follow the official release...

Is that ok for you? Or would you like a snapshot in the meantime?

Best regards,
Sebastien

**Comment by solomax** [comment]
Our wicket-7 version in alpha stage, so no rush :)
just friendly remainder :)

**Comment by solomax** [comment]
Hello Sebastien,

can you please release wicket-7 version? M5 was just announced :)

**Comment by sebfz1** [comment]
Already available my dear ! :)
As well as 6.19.0 (which changelog is at the usual location, in the wiki...)

I will make the announcement tonight or tomorrow...

Best regards &... Enjoy!
Sebastien

**Comment by solomax** [comment]
Thanks a lot!
