### ISSUE TITLE
Order of Behaviors / JQueryUIBehaviors

### ISSUE THREAD

**Issue by Patrick1701** [sebfz1/wicket-jquery-ui#140]
Hi Sebastien,
I am asking here, because I subclassed ButtonBehavior, but I'm not sure, if its more a Wicket issue, but maybe you have a sudden inspiriation...

I would like to visualize a disabled button by using jqueryUIs Button feature "disabled" true/false.
What I do is extending your ButtonBehavior, asking for isLinkEnabled() (I am in context of an Link ) and setting the option "disabled" depending on the state.
(By the way, could be a nice standard-feature of your ButtonBehavior... feel free to integrate... :-) )

My problem now is, we have another custom (new) behavior which calls ```setEnabled(false)``` on the Component, and it seems it is not garanteed, that the Behaviors are "executed" by wicket in always the same order (or any order?)
Sometimes ButtonBehavior is first, than our custom behavior, sometimes otherway around.
But the call ```component#isLinkEnabled()``` depends on an order.

Do you have an idea? Are you able to garantee an order, that your JQueryUIBehaviors are always the lasts? Is this more an Wicket related issue?

Thanx for you feedback
Patrick

```
new ButtonBehavior(JQueryWidget.getSelector(this)){//the button look			
				private static final long serialVersionUID = 1L;
				
				@Override
				public void onConfigure(Component component) {
					if( ! isLinkEnabled()){
						setOption("disabled", "true");
					}
					else {
						setOption("disabled", "false");
					}
					super.onConfigure(component);
				}
			}
```

**Comment by sebfz1** [comment]
Hi Patrick,

I made it work with kendo button (on a A tag), simply with this:

```java
@Override
public void onConfigure(JQueryBehavior behavior)
{
	behavior.setOption("enable", this.isEnabled());
}
```

Btw, I didn't see `AbstractLink#isLinkEnabled` in wicket 7. Maybe it has been removed since...

Best regards,
Sebastien.

**Comment by Patrick1701** [comment]
Hi Sebastien,
in Wicket6 there was an helper method in ```AbstractLink``` delegating to ```isEnabledInHierarchy()```.
Possibly they removed this helper method.

best regards
Patrick

**Comment by Patrick1701** [comment]
I remember... Once I had problems by "only" using isEnabled(). Maybe isEnabledInHierarchy() works even better?
I'm not sure, where the real difference is.

**Comment by sebfz1** [comment]
Yes, #isEnabledInHierarchy() is probably more relevant!

**Comment by sebfz1** [comment]
Hi Patrick,

I will extends all XxxLink for taking the enable/disable state into account, for both jQuery UI [1] and Kendo UI [2], so the user don't bother adding the behavior himself each time... But I need WICKET-4551 [3] to be resolved first to not have to work twice on this.

[1] http://api.jqueryui.com/button/#option-disabled
[2] http://docs.telerik.com/kendo-ui/api/javascript/ui/button#configuration-enable
[3] https://issues.apache.org/jira/browse/WICKET-4551

Best regards,
Sebastien

**Comment by Patrick1701** [comment]
Hi,
ok, thanx so far...

I will wait... just give me feedback. :-)

kind regards
Patrick

**Comment by sebfz1** [comment]
Hi Patrick,

That's resolved now. `#isEnabledHierarchy` is now non-final and stands for `#isLinkEnabled`.
I will add the missing XxxLink in jQuery UI / Kendo UI very shortly.

Best regards,
Sebastien.

**Comment by Patrick1701** [comment]
Hi Sebastien,
is this issue resolved in 6.19.0 and 6.19.1?

Or still open?

kind regards
Patrick

**Comment by sebfz1** [comment]
Hi Patrick,

I did not yet added all XxxLink for both jQuery UI and Kendo UI.

For now on, `6.19.x` embeds:
- com.googlecode.wicket.kendo.ui.markup.html.link.AjaxLink<T>
- com.googlecode.wicket.kendo.ui.markup.html.link.BookmarkablePageLink<T>

Best regards,
Sebastien.

**Comment by Patrick1701** [comment]
Hi Sebastien,
ok, unfortunately we dont use the kendo buttons here, so I will need to wait for it featured in normal ```ButtonBehavior```.
But for that, you need
[3] https://issues.apache.org/jira/browse/WICKET-4551
correct?

regards
Patrick

**Comment by sebfz1** [comment]
Hi Patrick,

WICKET-4551 is now resolved; `#isEnabledHierarchy()` now stands for former `#isLinkEnabled`.

I am not sure to handle this in `ButtonBehavior`, I am figuring out that it's more convenient to have/use XxxLink directly. I will try to add these asap...

Best regards,
Sebastien.

**Comment by sebfz1** [comment]
Hi Patrick,

I've added `AjaxFallbackLink`, `AjaxLink`, `AjaxSubmitLink`, `BookmarkablePageLink`, `DownloadLink`, `ExternalLink`, `Link`, `ResourceLink`, `StatelessLink` & `SubmitLink`.

Deployed `6.19.2-SNAPSHOT`

Enjoy! :)
Sebastien.

**Comment by Patrick1701** [comment]
Hi Sebastien,
late, but a short feedback now. I changed two of our components and it works as expected.

Thanx :-)
Patrick

**Comment by sebfz1** [comment]
Hi Patrick,

Perfect, thanks for letting me know! :)

Best regards,
Sebastien
