### ISSUE TITLE
preventing AbstractFormDialog to close on pressing F5

### ISSUE THREAD

**Issue by DanielaL** [sebfz1/wicket-jquery-ui#144]
Hi Sebastien,
I have a dialog which extends AbstractFormDialog used for adding customer data to a appointment. When the dialog is opened the appointment is locked in the database. When the dialog closes the appointment is either saved or released (if cancel or the x button is pressed). 

Now I have the problem that if F5 is pressed while the dialog is open the dialog disappears and the appointment is not released because onClose is not called. Is there a way to either prevent the AbstractFormDialog from closing on F5 (like for esc) or to catch a event executed on pressing F5 to release the appoinment data?
Best regards and many thanks in advance
Daniela

**Comment by evalls** [comment]
Hi Daniela this is very helpfull
do you know if there is a way to know ,if the "X" button to close the abstractFormDialog was Clicked?
I have the Problem that, when i click the Cancel Button i call a methode but when i press the "X" Button, i don't know how to call my methode on it.
