### ISSUE TITLE
How to add tooltip in calenda?

### ISSUE THREAD

**Issue by sunlingfeng-daren** [sebfz1/wicket-jquery-ui#146]
Hi,I want to add tooltip in full calenda component just like http://www.discoveryeducation.com/Events/ . It can show tooltip in a popup window.How can I show this ?Thanks!

**Comment by sebfz1** [comment]
Hi,

This is not a built-in feature. In the link you mentioned, they are using a 3rd party library (powerTip). FullCalendar also mentioned another one to achieve the same usecase (qTip) [1].

You can try something like:
```java
Options options = new Options();
options.set("eventRender", "function(event, element) { element.qtip({ content: event.description });");

this.add(new Calendar("calendar", new DemoCalendarModel(), options));
```

Be sure to add qTip/powerTip dependency beforehand...

Hope this helps,
Sebastien.

[1] http://fullcalendar.io/docs/event_rendering/eventRender/
