### ISSUE TITLE
Add close button to jquery ui tabs?

### ISSUE THREAD

**Issue by sunlingfeng-daren** [sebfz1/wicket-jquery-ui#148]
hi,
I found a link http://jqueryui.com/tabs/#manipulation,how to use wicket-jquery-ui add close to tabs? Thanks!

**Comment by sebfz1** [comment]
Hi,

Unfortunately, this is not a built-in feature...
You can either try to integrate it according to the demo in the link you provided or use/integrate a plugin like http://andrew.io/weblog/2010/01/a-close-button-for-jquery-ui-tabs.

Gook luck & best regards,
Sebastien.
