### ISSUE TITLE
about JQueryFeedbackPanel

### ISSUE THREAD

**Issue by sunlingfeng-daren** [sebfz1/wicket-jquery-ui#149]
Dear Sir:
I used JQueryFeedbackPanel in my develop envirnment,I found it can display info very well.But after message displayed,it can not disappear auto,could you support this function? Thanks!

**Comment by sebfz1** [comment]
Hi,

The JQueryFeedbackPanel does not rely on a jQuery UI widget and therefore there is no option we can configure for that... However, it is quite easy to add it manually:

Using classic fade-out:

```java
feedback.add(new JQueryUIBehavior(JQueryWidget.getSelector(feedback), "fadeOut") {
	
	private static final long serialVersionUID = 1L;

	@Override
	protected String $()
	{
		String delay = String.format("jQuery('%s').delay(1000);", this.getSelector());

		return delay + super.$();
	}
});
```

Or using effect:

```java
feedback.add(new JQueryEffectBehavior(JQueryWidget.getSelector(feedback), Effect.Explode.toString()) {

	private static final long serialVersionUID = 1L;

	protected String $()
	{
		String delay = String.format("jQuery('%s').delay(1000);", this.getSelector());

		return delay + super.$();
	}			
});
```

Please note that I don't think I will add this feature natively in the library because it is too subject to user preferences... (but maybe I will change my mind later ;) )

Best regards,
Sebastien

**Comment by sunlingfeng-daren** [comment]
I think you are expert of wicket,I also know wicket-jquery-ui is a good point to learen wicket.So if you have free time,could you write a book to teach pepole who like to use wicket? Thanks!

**Comment by martin-g** [comment]
@sunlingfeng-daren Have you seen http://wicket.apache.org/guide/ ?

**Comment by sunlingfeng-daren** [comment]
yes,when I face problem I will search this guide,but I can not hold the core of wicket.

**Comment by sunlingfeng-daren** [comment]
I use wicket under osgi envirnment ,I found the component of wicket is a good friend of  osgi bundle,but I have poor knowleage of wicket.

**Comment by martin-g** [comment]
I see nothing in common between Wicket's org.apache.wicket.Component class (hierarchy) and OSGi bundles.

Usually the **core** of anything is an implementation detail. You don't need to know it if you are not going to modify it (i.e. to contribute to it). It may change how it works internally at any point of time.

Please do not hesitate to ask at users@wicket.apache.org if you have specific questions!

**Comment by sebfz1** [comment]
Hi,

@sunlingfeng-daren, thank you very much for your consideration! Maybe we can say I am a wicket expert (in the sense that I acquired some expertise from the time I am using it) but I'm definitely not a wicket's super guru! :) For instance, there is several things I never touched in wicket...
And to be absolutely honest, I don't think it is possible to do better than the actual free guide (thanks to Andrea!)
As Martin said, so not hesitate to ask the mailing list if you have any specific question, it is really reactive (thanks to Martin, 90% of time! ;))

Best regards,
Sebastien.

**Comment by sunlingfeng-daren** [comment]
@sebfz1  I found this link:http://comments.gmane.org/gmane.comp.java.wicket.user/115073
and following info:
1) create a custom Component or Behavior that will contribute the .js (and
>> any .css, images, ... if needed) in #renderHead()
>> 2) if the JS widget needs configuration (e.g. some JSON object passed to
>> the widget's constructor) then use again #renderHead() to write it to the
>> response
>> 3) if the JS widget provides functionality to send data back to the server
>> then use either Ajax Behavior, IResourceListener or mounted resource

I can correctly use step1,but I always can not config step2 and step3, I confused with integrate JS
library with wicket.Dear sir,can you give me some advice? thks!

**Comment by sebfz1** [comment]
Hi,

This is more a general question that would have a better place in users@wicket.apache.org...
For wicket-jquery-ui related question, there is also a forum [1]. Github's issue purpose is for bugs or enhancement requests...
To answer your question, as written in the post you mentioned, you can have a look at the source code to see how it works... I also began to write some how-tos several months agos. It may be a little be deprecated but still can give a good overview. [2][3]

If you still need help after that, please create your project in github with everything you were able to achieve and ask for help explaining where you are blocked. If your project relies on `wicket-jquery-ui-core`, you can ask in the dedicated forum... [1]

Thanks & best regards,
Sebastien.

[1] https://groups.google.com/group/wicket-jquery-ui
[2] https://code.google.com/p/wicket-jquery-ui/wiki/HowToCreatePlugin1
[3] https://code.google.com/p/wicket-jquery-ui/wiki/HowToCreatePlugin3
