### ISSUE TITLE
what is best practise to integrate a js to wicket?

### ISSUE THREAD

**Issue by minikiller** [sebfz1/wicket-jquery-ui#150]
Dear Sir:
I used wicket for a short time,it make me confuse is how to integrate a JS library with wicket. I searched google,but can not find a good way to introduce this. For example,I want to use uploadify js in my project.How can I to integrate Uploadify to wicket?  Thanks!

**Comment by martin-g** [comment]
Hi,

Check this article: http://wicketinaction.com/2012/11/uploading-files-to-wicket-iresource/
And the demo application for it.
It just uses different JS library for the same purpose.

**Comment by minikiller** [comment]
Thanks for you reply,I download this source code but it can not run under wicket 6.18.0.

**Comment by martin-g** [comment]
Please use users@wicket.apache.org.
This project is not related to the issue.
