### ISSUE TITLE
Wysiwyg Toolbar Issue Hyperlink

### ISSUE THREAD

**Issue by vurado** [sebfz1/wicket-jquery-ui#151]
I notice that the Hyperlink in Wysiwyg toolbar is not functional then you click on the URL (input field) the dropdownmenu lose the focus and you can never add a link. A solution for this issue ? thx

**Comment by sebfz1** [comment]
Hi,

Yes, that's true. I don't know if it comes from the plugin itself or something incorrect with the integration.
Maybe @solomax can have a closer look to this issue?
http://www.7thweb.net/wicket-jquery-ui/plugins/wysiwyg/WysiwygEditorPage

Thanks & best regards,
Sebastien.

**Comment by solomax** [comment]
I'll try to find some time this weekend and take a look at it

**Comment by sebfz1** [comment]
Fixed with https://github.com/sebfz1/wicket-jquery-ui/commit/5cc14670993e5c0a5994d8ff5c9f84040851bed2
Big thanks to Maxim! :)
