### ISSUE TITLE
Calendar get JQueryEvent

### ISSUE THREAD

**Issue by DanielaL** [sebfz1/wicket-jquery-ui#154]
Hi Sebastien,
how do I get the JQueryEvent event from a calendar at a onDayClick event? I want to get the resource from the clicked cell and I saw that the ressource is shown in the ClickEvents viewName. I want to create a new event based on the clicked cells startDate and the selected ressource.
Thank you very much in advance :-)
best regards
Daniela

**Comment by sebfz1** [comment]
Hi Daniela,

Hope you are going well! :)

To answer your question:
1/ before digging into JQueryEvent, you need to ensure how you can get the resource-id back. Someone just ask the question in FullCalendar/Resource View thread [1]

> is their anyway to get the resourceid when using the dayClick event? BTW big thank you for your work on this!

2/ Just retrieving the JQueryEvent will not be enough if the ajaxbehavior that sends this event does not retrieve the resourceId. Thus the JQueryEvent (DayClickEvent) should be extended with the getResourceId property. IMO the easiest way to achieve you case will be "override" the `dayClick` callback instead of whiling to override the `CalendarBehavior` itself... Look in `CalendarBehavior` how callbacks/ajaxbehavior are managed and write your own in YourCalendar directly, then just map your ajaxbehavior to the `dayClick` event:

```java
/** IJQueryAjaxAware will allow you to pass this (the calendar) to the 
ajaxbehavior and trigger #onAjax when the dayclick event will be fired */
public MyCalendar extends Calendar implements IJQueryAjaxAware {

	@Override
	public void onConfigure(JQueryBehavior behavior)
	{
		super.onConfigure(behavior);
		
		behavior.setOption("dayClick", this.myOnDayClickBehavior.getCallbackFunction());
	}
}
```

3/ Unfortunately this nice functionality still not has been merged, so I cannot handle it in the project...

4/ Be careful if you are going to migrate to wicket-jquery-ui 6.19.0 or 7.0.0-M5 because fullcalendar implementation changed to v2.x. So your forked fullcalendar.js may not work anymore...

Good luck :)
Sebastien.

[1] https://github.com/arshaw/fullcalendar/pull/195#issuecomment-70001688

**Comment by DanielaL** [comment]
Hi Sebastien,
I am fine thanks, I hope you too?
to 1) I already know that the first- and lastname of the resource is in the ClickEvents viewName so I would get the resource from the database with the viewName string.
to 2) I thought I could get the callbackParameters from OnDayClickBehavior somehow and extract the viewName.
to 3) Thats Ok :-)
to 4) I was trying to swap to the resource view you linked to be able to migrate to a newer version, but it didn't show any events and i have no time to investigate further at the moment.
I hope I described a little bit better what I want to achieve :-)
Have a nice weekend.
Salut
Daniela

**Comment by sebfz1** [comment]
I am going very well, thanks ! :)

So you mean the view name holds the user name?

If so, that's a problem because view names are enums (`CalendarView`). If the view that is returned by the dayclick event is unknown, null is returned. I say that's a problem because, even if I change views to const or even provide a fallback to the view name when it's not found, I can only do it from the current version. The version you do not support yet! :(

I think my previous comment remains valid, do like I descibed but reforward the viewName as-is, without calling `CalendarView#get()`. Then you will have your own event `public void onDayClick(AjaxRequestTarget target, String view, Date date, boolean allDay)`

Good luck again & have a nice week-end too,
Sebastien

**Comment by DanielaL** [comment]
Hi Sebastien,
Yes debugging showed the resource name that was added as a option like this  
```
resources: [
         	   { name: 'Resource 1',
           		 id: 1
         		},
         		...
```
I tried to implement the subclass of Calendar like you described. But I get a null pointer exception at getCallbackFunction for jsEvent, view and viewName. Have I missed any initialisation?

```
public class AjaxAwareCalendar extends Calendar implements IJQueryAjaxAware {

	public AjaxAwareCalendar(String id, CalendarModel model, Options options) {
		super(id, model, options);
	}

	@Override
	public void onAjax(AjaxRequestTarget target, JQueryEvent event) {
		 if (event instanceof ResourceDayClickEvent) {
                      ResourceDayClickEvent e = (ResourceDayClickEvent)event;
                      this.onResourceDayClick(target, e.getView(),e.getDate());
            }
	}
	
	 public void onResourceDayClick(AjaxRequestTarget target, String viewName, Date date) {

        }
	
    protected JQueryAjaxBehavior resourceDayClickBehavior()
	{
		return new JQueryAjaxBehavior(this) {
			@Override
			protected CallbackParameter[] getCallbackParameters()
			{
				//http://arshaw.com/fullcalendar/docs/mouse/dayClick/
				//function(date, allDay, jsEvent, view)
				return new CallbackParameter[] {
						CallbackParameter.converted("date", "date.getTime()"),
						CallbackParameter.explicit("allDay"),
						CallbackParameter.context("jsEvent"),
						CallbackParameter.context("view"),
						CallbackParameter.resolved("viewName", "view.name")
				};
			}

			@Override
			protected JQueryEvent newEvent()
			{
				return new ResourceDayClickEvent();
			}
		};
	}
	
	 @Override
    public void onConfigure(JQueryBehavior behavior)
    {
        super.onConfigure(behavior);

        behavior.setOption("dayClick", this.resourceDayClickBehavior().getCallbackFunction());
    }
    
    
    protected static class ResourceDayClickEvent extends JQueryEvent
	{
		private final Date day;
		private final String viewName;

		public ResourceDayClickEvent()
		{
			long date = RequestCycleUtils.getQueryParameterValue("date").toLong();
			this.day = new Date(date);

			this.viewName = RequestCycleUtils.getQueryParameterValue("viewName").toString();
		}

		public Date getDate()
		{
			return this.day;
		}

		public String getView()
		{
	        return this.viewName;
	    }
	}    
}
```

**Comment by sebfz1** [comment]
Hi Daniela, 

> Have I missed any initialisation?

Yes, you have to create the behavior first, attach it and use it. 
So you cannot have this:

```java
    this.resourceDayClickBehavior().getCallbackFunction()
```

but rather:

```java
onInitialize {
     this.resourceDayClickBehavior = this.newResourceDayClickBehavior()
     this.add(this.resourceDayClickBehavior);
}
...
this.resourceDayClickBehavior.getCallbackFunction()
```

Best regards,
Sebastien

**Comment by sebfz1** [comment]
The rest of the code looks good :)
Please let me know if you did it work!..

Thanks & best regards,
Sebastien.

**Comment by DanielaL** [comment]
The Nullpointer Exception is gone, thanks a lot, but onResourceDayClick is not called at all. I guess that it has to do with the Options HashMap, that 
```
behavior.setOption("dayClick", this.resourceDayClickBehavior.getCallbackFunction());
```
is not working on the options HashMap of the original dayClick which is in the options of the CalendarBehavior but it is in the options of the Calendar?
It now looks like this:

```
public class AjaxAwareCalendar extends Calendar implements IJQueryAjaxAware {

	private JQueryAjaxBehavior resourceDayClickBehavior; // day click

	public AjaxAwareCalendar(String id, CalendarModel model, Options options) {
		super(id, model, options);
	}

	@Override
	public void onAjax(AjaxRequestTarget target, JQueryEvent event) {
		 if (event instanceof ResourceDayClickEvent) {
                ResourceDayClickEvent e = (ResourceDayClickEvent)event;
                this.onResourceDayClick(target, e.getView(),e.getDate());
                
            }
	}
	
	@Override
	protected void onInitialize()
	{
		super.onInitialize();
	     this.resourceDayClickBehavior = this.newResourceDayClickBehavior();
	     this.add(this.resourceDayClickBehavior);
	}
	
	 public void onResourceDayClick(AjaxRequestTarget target, String viewName, Date date) {

      }
	
	 
    protected JQueryAjaxBehavior newResourceDayClickBehavior()
	{
		return new JQueryAjaxBehavior(this) {

			private static final long serialVersionUID = 1L;

			@Override
			protected CallbackParameter[] getCallbackParameters()
			{
				//http://arshaw.com/fullcalendar/docs/mouse/dayClick/
				//function(date, allDay, jsEvent, view)
				return new CallbackParameter[] {
						CallbackParameter.converted("date", "date.getTime()"),
						CallbackParameter.explicit("allDay"),
						CallbackParameter.context("jsEvent"),
						CallbackParameter.context("view"),
						CallbackParameter.resolved("viewName", "view.name")
				};
			}

			@Override
			protected JQueryEvent newEvent()
			{
				return new ResourceDayClickEvent();
			}
		};
	}
	
	 @Override
    public void onConfigure(JQueryBehavior behavior)
    {
        super.onConfigure(behavior);
        behavior.setOption("dayClick", this.resourceDayClickBehavior.getCallbackFunction());
    }
    
    
    protected static class ResourceDayClickEvent extends JQueryEvent
	{
		private final Date day;
		private final String viewName;

		public ResourceDayClickEvent()
		{
			long date = RequestCycleUtils.getQueryParameterValue("date").toLong();
			this.day = new Date(date);

			this.viewName = RequestCycleUtils.getQueryParameterValue("viewName").toString();
		}

		public Date getDate()
		{
			return this.day;
		}

		public String getView()
		{
	        return this.viewName;
	    }
	}
 }

```

Thank you and best regards
Daniela

**Comment by sebfz1** [comment]
Hi Daniela,

Sorry, my bad. In this case `CalendarBehavior` options takes priority over yours (I did not supposed the user - you - would have a special need based on a fork ;)).

The way to workaround this is however simple: just make `#isDayClickEnabled` return false (which is the default, so just remove the override which return true).

Just an additional note: the `CalendarBehavior#isEditable` property is important and must return true for the fullcalendar to be in "editable" mode. But if `YourCalendar#isEventClickEnabled` already returns true, that's fine.

It should work now :)

Best regards,
Sebastien

**Comment by DanielaL** [comment]
Hi Sebastien,
there is no isDayClickEnabled in 6.8.2 and have to stick to this version because of the resource view :-( I am sorry for causing so much trouble...
Best regards
Daniela

**Comment by sebfz1** [comment]
Hi Daniela,

That's bad news! :(

Unfortunatly I do see any immediate workaround. But I see two options: 

1/ take the fullcalendar v2 with the merge and then use the lastest wicket-query-ui 6.x release (6.19.0). It is a long task because you are almost 2 years late and as many changelogs to read and take care of. But that's a solution that will pay for the future.

2/ Override YourCalendar#newWidgetBehavior and provide your own MyCalendarBehavior (which is basically a copy/paste from the original). Apply your previous change in your MyCalendarBehavior in place of `newOnDayClickBehavior` directly, no need to be in YourCalendar anymore... You also have to change #onAjax to take into account your own DayClickEvent object and the corresponding #onDayClick(...) event.

3/ Clone the repo, change the code in directly CalendarBehavior, and recompile. That works but it's just to say this option exists. I would not recommend too much to opt for this one (it is like adding an issue over an issue to solve an issue*)...

Good luck, don't hesitate to ask for help,
Sebastien
(*) I will copyright this sentence I guess... :p

**Comment by DanielaL** [comment]
Hi Sebastien,
I will go for 2, because I don't have the time for 1 at the moment, but 1 is definetly on my agenda.
Thanks and best regards
Daniela

**Comment by DanielaL** [comment]
Hi Sebastien,
I still have a question: I tried to subclass CalendarBehavior and override newWidgetBehavior in my calendar but I am stuck with StringBuilder sourceBuilder = new StringBuilder();
				sourceBuilder.append("'").append(Calendar.this.modelBehavior.getCallbackUrl()).append("'");

**Comment by sebfz1** [comment]
Hi Daniela,

I don't exactly understand why you are stuck but you can move the code in Calendar directly
https://github.com/sebfz1/wicket-jquery-ui/blob/wicket-jquery-ui-6.18.0/wicket-jquery-ui-calendar/src/main/java/com/googlecode/wicket/jquery/ui/calendar/Calendar.java#L195

Caution, `modelBehavior` is not the widgetBehavior (CalendarBehavior), just to be clear...

**Comment by DanielaL** [comment]
Good evening Sebastien,
here is what I have tried subclassing the Calendar and provide a new newWidgetBehavior. Obviously some things have moved from the onConfigure of the CalendarBehavior to the onConfigure of the Calendar and now CalendarModelBehavior is public, but in my version, there is no possibility to acces the modelBehavior for the CallbackUrl:

```
public class ResourceClickCalendar extends Calendar{
	private Map<CharSequence, String> gcals;
	private final Options options;

	public ResourceClickCalendar(String id, CalendarModel model, Options options) {
		super(id, model, options);
		this.options = options;
	}
	
	
	 public void onResourceDayClick(AjaxRequestTarget target, String viewName, Date date) {

     }
	
	 
	 /**
		 * Adds a Google Calendar Feed
		 * @param gcal url to xml feed
		 * @param className css class to be used
		 */
		public void addFeed(CharSequence gcal, String className)
		{
			if (this.gcals == null)
			{
				this.gcals = new HashMap<CharSequence, String>();
			}

			this.gcals.put(gcal, className);
		}


	// IJQueryWidget //
		/**
		 * see {@link JQueryContainer#newWidgetBehavior(String)}
		 */
		@Override
		public JQueryBehavior newWidgetBehavior(String selector)
		{
			return new ResourceDayClickCalendarBehavior(selector, this.options) {

				private static final long serialVersionUID = 1L;

				@Override
				public boolean isEditable()
				{
					return ResourceClickCalendar.this.isEditable();
				}

				@Override
				public boolean isSelectable()
				{
					return ResourceClickCalendar.this.isSelectable();
				}

				@Override
				public boolean isEventDropEnabled()
				{
					return ResourceClickCalendar.this.isEventDropEnabled();
				}

				@Override
				public boolean isEventResizeEnabled()
				{
					return ResourceClickCalendar.this.isEventResizeEnabled();
				}

				@Override
				public boolean isViewDisplayEnabled()
				{
					return ResourceClickCalendar.this.isViewDisplayEnabled();
				}

				@Override
				public void onConfigure(Component component)
				{
					super.onConfigure(component);

					// lazy options //
					ResourceClickCalendar.this.onConfigure(this);

					// builds sources //
					StringBuilder sourceBuilder = new StringBuilder();
					sourceBuilder.append("'").append(ResourceClickCalendar.this.modelBehavior.getCallbackUrl()).append("'");//HERE IS THE PROBLEM

					if (ResourceClickCalendar.this.gcals != null)
					{
						for (Entry<CharSequence, String> gcal : ResourceClickCalendar.this.gcals.entrySet())
						{
							sourceBuilder.append(", ");
							sourceBuilder.append("jQuery.fullCalendar.gcalFeed('").append(gcal.getKey()).append("', { className: '").append(gcal.getValue()).append("' })");
						}
					}

					this.setOption("eventSources", String.format("[%s]", sourceBuilder.toString()));
				}

				@Override
				public void onResourceDayClick(AjaxRequestTarget target, String viewName, Date date){
					ResourceClickCalendar.this.onResourceDayClick(target, viewName, date);
				}
				
				@Override
				public void onSelect(AjaxRequestTarget target, CalendarView view, Date start, Date end, boolean allDay)
				{
					ResourceClickCalendar.this.onSelect(target, view, start, end, allDay);
				}

				@Override
				public void onDayClick(AjaxRequestTarget target, CalendarView view, Date date)
				{
					ResourceClickCalendar.this.onDayClick(target, view, date);
				}

				@Override
				public void onEventClick(AjaxRequestTarget target, CalendarView view, int eventId)
				{
					ResourceClickCalendar.this.onEventClick(target, view, eventId);
				}

				@Override
				public void onEventDrop(AjaxRequestTarget target, int eventId, long delta, boolean allDay)
				{
					ResourceClickCalendar.this.onEventDrop(target, eventId, delta, allDay);
				}

				@Override
				public void onEventResize(AjaxRequestTarget target, int eventId, long delta)
				{
					ResourceClickCalendar.this.onEventResize(target, eventId, delta);
				}

				@Override
				public void onViewDisplay(AjaxRequestTarget target, CalendarView view)
				{
					ResourceClickCalendar.this.onViewDisplay(target, view);
				}
			};
		}
	}
```

**Comment by sebfz1** [comment]
You are right, I did not realized it's private...

So... last chance giving these considerations... You have to implements your own calendar. But don't be afraid, it just consist of not extending from `Calendar` but `JQueryContainer implements ICalendarListener` and copy the code from the original. There is not protected nor package classes to be used so you should not be in troubles. As you already have rewrote the `CalendarBehavior`, it is the easy part now ;).
I know it not an ideal situation, but that's the best we can do shortly given your situation, I think...

If you are a little bit lost, you can prepare me a quickstart with your current version and I can manage to do it quickly...

**Comment by DanielaL** [comment]
Hi Sebastien,
I am so happy I found a solution :-) I was unhappy with all the overriding and reimplementing and went back to the first solution of the AjaxAwareCalendar. I simply did overwrite the onDayClick method and created a ResourceDayClickEvent there and it works!
```
@Override
public void onDayClick(AjaxRequestTarget target, CalendarView view, Date date)
{
	 ResourceDayClickEvent e = new ResourceDayClickEvent();
	 onResourceDayClick(target, e.getView(), date);
}
```
Thank you so much for your help!
Best regards
Daniela

**Comment by sebfz1** [comment]
Hi Daniela,

This is a nice workaround, congrats !! :)

Basically I do create events a little bit earlier in the cycle, so this did not came in my mind, but it is absolutely true you can create it after, like you did!

Best regards,
Sebastien.
