### ISSUE TITLE
New kendo artifact

### ISSUE THREAD

**Issue by solomax** [sebfz1/wicket-jquery-ui#155]
I believe it might be useful to have artifact like wicket-jqueryui-kendo-culture to have all up-to-date "language" files in one place.

This artifact should have one "anchor class" (for ex. KengoGlobalizationAnchor.java) with no methods and JS files with kendo locales.

In this case one can use code like:
	public static void renderTelericLocale(IHeaderResponse response, Locale l) {
		response.render(JavaScriptHeaderItem.forReference(new JavaScriptResourceReference(KengoGlobalizationAnchor.class
				, String.format("kendo.culture.%s.min.js", l.toLanguageTag()))));
	}

to localize kendo widgets

**Comment by sebfz1** [comment]
Hi Maxim,

I will do it shortly!
Alternate question: does `Locale#toLanguageTag` actually exists?

Best regards,
Sebastien

**Comment by martin-g** [comment]
It is in JDK 1.7+

**Comment by solomax** [comment]
Yes :) but java7 only

I'm afraid your LocaleUtils.getLangageCode method will produce wrong result for locale like "en" (without country)

**Comment by sebfz1** [comment]
Oh, thanks Martin & Maxim, because I don't have it my jdk1.7.0_65...
Yes, I was thinking about providing an helper too... So, if it is not supported in all jdk1.7x, I was figuring out to use `LocaleUtils#getLangageCode`, which is supposed to work even if there no "country" (actually it should have been named the "culture")... 

```java
/**
 * Gets the language-code (eg: xx-XX) from a given {@link Locale}
 * @param locale the {@link Locale}
 * @return the language-code
 */
public static String getLangageCode(Locale locale)
{
	if (!Strings.isEmpty(locale.getCountry()))
	{
		return String.format("%s-%s", locale.getLanguage(), locale.getCountry());
	}

	return locale.getLanguage();
}
```

Best regards,
Sebastien

**Comment by martin-g** [comment]
I believe the method is there since 1.7.0_0. It should be in _65 as well.

**Comment by solomax** [comment]
it is in general javadoc: 
http://docs.oracle.com/javase/7/docs/api/java/util/Locale.html#forLanguageTag(java.lang.String)
http://docs.oracle.com/javase/7/docs/api/java/util/Locale.html#toLanguageTag()

**Comment by sebfz1** [comment]
Well, my eclipse project was pointing to a old jre (but it was supposed to be 7). I changed to  jdk1.7.0_65 and I've got it! :) Thanks!

**Comment by sebfz1** [comment]
Should be able to commit today (javadoc todo). Usage will be the following:

```java
@Override
public void renderHead(IHeaderResponse response)
{
	super.renderHead(response);

	response.render(JavaScriptHeaderItem.forReference(new KendoGlobalizeResourceReference(Locale.FRENCH))); // wicket7.x
	// response.render(JavaScriptHeaderItem.forReference(new KendoGlobalizeResourceReference(KendoCulture.FR_FR)));
	// response.render(JavaScriptHeaderItem.forReference(new KendoGlobalizeResourceReference("fr-FR"))); // or fr only
}
```

**Comment by solomax** [comment]
Great!
I like it :)

**Comment by sebfz1** [comment]
Oops, bad commit, correcting this asap...

**Comment by sebfz1** [comment]
Deployed `6.19.1-SNAPSHOT`
Deployed `7.0.0-SNAPSHOT`

Additional note about `new KendoGlobalizeResourceReference(Locale.FRENCH)));`
- wicket7.x will use `locale#toLanguageTag()`
- wicket6.x will use `LocaleUtils#getLangageCode(locale)`

**Comment by solomax** [comment]
Thanks a lot!
Will try to test ASAP :)))

**Comment by solomax** [comment]
Everything works as expected :))
Thanks a lot!

**Comment by solomax** [comment]
Hello Sebastien,
what are your plans on releasing 6.19.1? ;)

**Comment by sebfz1** [comment]
Hi Maxim,

Well, if you need it, I have to release it this week...

Best regards,
Sebastien

**Comment by solomax** [comment]
There is no rush actually, for 6.19 based version we are using ant for build and it doesn't work very well with maven snapshots.
And I would like to commit my changes, cause otherwise I'll forget about them :(
If you can release next week it will be perfect for me :)

**Comment by sebfz1** [comment]
I will do it asap (this week) otherwise you will not have it before 2/3 weeks!.. (if you see what I mean... ;))

**Comment by solomax** [comment]
great!
Thanks one more time :)

**Comment by sebfz1** [comment]
Hi Maxim,

`6.19.1` has been released, and `7.0.0-SNAPSHOT` redeployed.
Hope all will be ok, I won't be available next 2 weeks...

Enjoy!
Sebastien.

**Comment by solomax** [comment]
Thanks a lot Sebastien!

**Comment by Patrick1701** [comment]
Hi Sebastien,
is this already featured for JQueryUI by using ```JQueryGlobalizeResourceReference.get()``` as HeaderItem?

kind regards
Patrick

**Comment by sebfz1** [comment]
Hi Patrick,

Sorry, just saw this question. The answer is "almost" :)

`JQueryGlobalizeResourceReference` already embeed `globalize.js` and is automatically added to header items... as soon the user set it explicitly in `JQueryLibrarySettings`, like this:

```java
// Application#init()
JQueryLibrarySettings settings = new JQueryLibrarySettings();
settings.setJQueryGlobalizeReference(JQueryGlobalizeResourceReference.get());
 
this.setJavaScriptLibrarySettings(settings);
```

Best regards,
Sebastien.

**Comment by Patrick1701** [comment]
Ah, ok, thanx... :)

Minor additonal question.
All these settings made in ```Application#init()```, don't mean the jquery/kendo ui header items (scripts etc) are always rendered to pages, it means they are only rendered, if at least one jquery/kendo-ui component is present on page, because components take care for that, right?

If I want them always being avaliable (for instance to feature a support of direct/hardcoded calls to jquery/kendo-ui javascript effects direct from my page-markup) I need to add them somewhere in my (border) page hierarchy manually like:

```
MyBasePage
...
	@Override
	public void renderHead(HtmlHeaderContainer container) {
		super.renderHead(container);
		IHeaderResponse response = container.getHeaderResponse();
		
		//JQueryUI / always present
		response.render(new PriorityHeaderItem(JavaScriptHeaderItem.forReference(JQueryUIResourceReference.get())));
		
		//KendoUI / always present
		response.render(JavaScriptHeaderItem.forReference(KendoUILibrarySettings.get().getJavaScriptReference()));
		
	}

```
Is it correct? :)

kind regards
Patrick

**Comment by martin-g** [comment]
s/renderHead(HtmlHeaderContainer/renderHead(IHeaderResponse/

If you need them at every page then you can use `org.apache.wicket.Application#getHeaderContributorListeners().add(...)`

**Comment by Patrick1701** [comment]
Hi Martin,
great, thanx a lot...

Patrick

**Comment by Patrick1701** [comment]
Hi Sebastien,
currently I'm upgrading to Wicket 6.20 and I would like integrate this feature.

Does it just provide the header contribution of the particular i18n culture file, or does it also enables the current culture by locale on js-client-side?
Is it mandatory to implement some script execution, which calls ```kendo.setCulture('xyz')```?

best regards
Patrick

**Comment by sebfz1** [comment]
Hi Patrick,

Nice to see you arround!

> Does it just provide the header contribution

Nope, it provide the resource reference for the given language/culture, up to you to contribute to the header:

```java
@Override
public void renderHead(IHeaderResponse response)
{
	super.renderHead(response);

	// response.render(JavaScriptHeaderItem.forReference(new KendoGlobalizeResourceReference("fr"))); // or fr-FR
	// response.render(JavaScriptHeaderItem.forReference(new KendoGlobalizeResourceReference(KendoCulture.FR_FR)));
	// response.render(JavaScriptHeaderItem.forReference(new KendoGlobalizeResourceReference(Locale.FRENCH)));
}
```


> Is it mandatory to implement some script execution, which calls kendo.setCulture('xyz')?

Yes, exactly. Or if a (Wicket Kendo UI) component already support `#setCulture` or a `Locale` you can use it directly, like for the `DatePicker`:

```java
// Constructor, which use Locale and Kendo UI Globalization
new DatePicker("datepicker", Model.of(new Date()), Locale.FRANCE)
```
