### ISSUE TITLE
Problems with Dialogs (Wizards) in AjaxTabs

### ISSUE THREAD

**Issue by Patrick1701** [sebfz1/wicket-jquery-ui#157]
Hi Sebastien,
when I put a ```AbstractWizard``` (-Dialog) into a panel which is lazy-loaded by ```AjaxTab``` (in a TabbedPanel), the dialog gets rendered into its placeholder on open, and I get the error message in Wickets AjaxDebugWindow.

>ERROR: Wicket.Ajax.Call.processEvaluation: Exception evaluating javascript: Error: cannot call methods on dialog prior to initialization; attempted to call method 'open', text: (function(){Wicket.Ajax.ajax({"u":"./page?4-1.IBehaviorListener.0-catalogs-catalogs-panels-tab~panels900~7-lazy-catentryGroups-3-widget-widget_body-bulk","e":"click","c":"bulkb0c"});})();(function()
...

Does this looks like a bug of ```AbstractDialog```s to you, or is this just a restriction due to the replacement of the panel?
If found this warning-comment in ```AjaxTab```
```
private Component replaceComponent()
	{
		return this.panel.getPlaceholderComponent().replaceWith(this.getLazyPanel()); // warning, inner panel is detached here.
	}
```

kind regards
Patrick

**Comment by sebfz1** [comment]
Hi Patrick,

I am happy to have a user like you, which tests every kind of combinations, lol!

About your specific construction, I don't know if it is a restriction, or if it can be solved (could be by a workaround), or if there is eventually a bug... 

What is sure is that the AjaxPanel content is designed to be loaded once... But I need a better view of your usecase, could you please prepare me quickstart so I can investigate?

Thanks in advance,
Sebastien.

**Comment by Patrick1701** [comment]
Hi,
> I am happy to have a user like you, which tests every kind of combinations, lol!

;-)

I wasnt able to reproduce it... strange.
A simple variant is working... also a more complex variant with sub-fragments containing refreshing views etc pepe.

I think, first I will re-implement our panel structure here. As I can see, the code I try to implement my wizard-dialog is not thaaat beautiful. Too many developers worked on that. So, maybe this issue will be solved then anyway.

If ok, I will let it open for some time, and coming back, if I still have this problem after the code cleaning is done.

best regards
Patrick

**Comment by sebfz1** [comment]
Hi Patrick,

> If ok, I will let it open for some time, and coming back, if I still have this problem after the code cleaning is done.

No problem, just remember to come back to it in order to not let this issue opened at vitam eternam (but I will send you some reminders, no worry ;) )

Best regards,
Sebastien.

**Comment by sebfz1** [comment]
One month elapsed... Here is a reminder! :)

**Comment by Patrick1701** [comment]
Oh, yes. Closable for now... :-)
