### ISSUE TITLE
Kendo AjaxDateTimePicker does not fire onValueChanged() in a localized variant

### ISSUE THREAD

**Issue by Patrick1701** [sebfz1/wicket-jquery-ui#159]
Hi Sebastien,
I try to implement a AjaxDateTimePicker in a localized variant.

So, a mix of these both examples:
http://www.7thweb.net/wicket-jquery-ui/kendo/datetimepicker/AjaxDateTimePickerPage
http://www.7thweb.net/wicket-jquery-ui/kendo/datetimepicker/LocaleDateTimePickerPage

But due to my override code
```
@Override
protected AjaxDatePicker newDatePicker(String id, IModel<Date> model, String datePattern)
{
	return new AjaxDatePicker(id, model, Session.get().getLocale());
}

@Override
protected AjaxTimePicker newTimePicker(String id, IModel<Date> model, String timePattern)
{
	return new AjaxTimePicker(id, model, Session.get().getLocale());
}

@Override
public void onValueChanged(AjaxRequestTarget target) {
	//never reach this code
}
```
I loose the feature of getting ```onValueChanged(...)``` fired.

Even if I copy-paste-like try to inner-sub-class / override the methods ```newWidgetBehavior(String selector)``` of my own localized ```AjaxDatePicker```s to delegate onAjax() etc, I'm not able to get it working because of member-visibility issues.
Here e.g. for ```this.options```, but also for other members...

```
@Override
protected AjaxDatePicker newDatePicker(String id, IModel<Date> model, String datePattern)
{
	return new AjaxDatePicker(id, model, Session.get().getLocale()){
		@Override
    		public JQueryBehavior newWidgetBehavior(String selector)
    		{
			return new DatePickerBehavior(selector, this.options) {
													^^^^ visibility issue / 'this' is not available
				...
			}
		}
	};
}
```

How can I achieve this? Did I miss something? Doing too complicate?
Is it a bug?

Thanx for help
Patrick

**Comment by sebfz1** [comment]
Hi Patrick,

I think **ajax**datetimepicker #newDatePicker & #newTimePicker was not intended to be overrided...
You can safely use this, which is equivalent:

```java
Locale locale = Session.get().getLocale();
String datePattern = LocaleUtils.getLocaleDatePattern(locale);
String timePattern = LocaleUtils.getLocaleTimePattern(locale);

final DateTimePicker datetimepicker = new AjaxDateTimePicker("datetimepicker", Model.of(calendar.getTime()), datePattern, timePattern) {
```

Hope this helps,
Sebastien

**Comment by Patrick1701** [comment]
Ah, I used the string pattern constructors for now as temporary solution which are working perfect, but this is quite hardcoded.
I didnt know you have a LocaleUtils... so great... I will try them in the afternoon. :-)

kind regards
Patrick

**Comment by sebfz1** [comment]
Hi Patrick,

Some update about his so we can close the issue?

Thanks & best regards,
Sebastien

**Comment by Patrick1701** [comment]
Hi Sebastien,
very sorry, for not replying here (and at all. Currently we are in hard part of our project, so unfortunately I'm quite focused on other things, than UI dev).

I will come back here, if get problems. So I close it for now...

Thanx a lot
Patrick
