### ISSUE TITLE
Bad component passed to DroppableBehavior.onDrop function

### ISSUE THREAD

**Issue by VaclavC** [sebfz1/wicket-jquery-ui#163]
I'am trying to work with drag ang drop behaviors. I have ListView of draggable components and one drop zone. When I drop any of draggables into zone, last draggable from listview is passed as argument of onDrop function. It is a bug or I'am doing something wrong?

I want to use Behaviors, not Draggrable and Droppable components, here I simplified it into wicket quickstart to demonstrate the problem, real use in my app is more complicated. I created following repository with modified quickstart:

https://github.com/VaclavC/wicket-dragtest

**Comment by VaclavC** [comment]
After I created this issue, I was instantly enlightened (yesterday I tried to resolve this for several hours...). I realized, that I should pass selector with id of concrete list item as DraggableBehavior argument. It should be this:

    ...
    item.add(new DraggableBehavior("#" + item.getMarkupId())
    ...

I used wicket-dnd before, there I should attach drag behavior to a container and select draggables with selector, this confused me a bit here.

Sorry for bothering.

**Comment by sebfz1** [comment]
No worry.

Basically you are right, a `DraggableBehavior` could have a css-class selector. I think it remains valid if you have only one draggable.
IIRC, as we need to know what component it's bound to (to get it back), we need to have a `DraggableBehavior` per component, so supplying a css-class as a selector will result to conflicts.

A shorthand for `"#" + item.getMarkupId()` is `JQueryWidget.getSelector(item)`.
Also be careful, in your sample you hardcoded the html-id for the drop_target. Even authorized, it would be better to have `new DroppableBehavior(JQueryWidget.getSelector(dropTarget))`.

Best regards,
Sebastien

**Comment by VaclavC** [comment]
Thank you for your reply.

I have another question, probably not worth of creating another issue: how can I get Component to which is DraggableBehavior or DroppableBehavior attached? With Wicket's Ajax behaviors I'am using getComponent method, but drag and drop behaviors are extended from Behavior class a have not such method.

**Comment by sebfz1** [comment]
What is the use case?

**Comment by VaclavC** [comment]
Basically it is an ordered list, which I can rearrange by dragndrop. With getComponent method in DroppableBehavior I don't need to have ListItem<T> final. But maybe I'am doing it completely bad ;-).

```java
package com.disnel.sypre.admin.wicket;

import java.util.List;

import org.apache.wicket.Component;
import org.apache.wicket.MetaDataKey;
import org.apache.wicket.ajax.AjaxRequestTarget;
import org.apache.wicket.markup.html.WebMarkupContainer;
import org.apache.wicket.markup.html.list.ListItem;
import org.apache.wicket.markup.html.list.ListView;
import org.apache.wicket.markup.html.panel.Fragment;
import org.apache.wicket.markup.html.panel.Panel;

import com.googlecode.wicket.jquery.core.IJQueryWidget.JQueryWidget;
import com.googlecode.wicket.jquery.ui.interaction.draggable.DraggableBehavior;
import com.googlecode.wicket.jquery.ui.interaction.droppable.DroppableBehavior;

public abstract class VerticalDraggableList<T> extends Panel
{
	
	private static MetaDataKey<Integer> INDEX = new MetaDataKey<Integer>() {};
	
	private List<T> itemsList;
	
	private WebMarkupContainer container;
	
	public VerticalDraggableList(String id, List<T> items)
	{
		super(id);
		this.itemsList = items;
		
		add(container = new WebMarkupContainer("container"));
		container.setOutputMarkupId(true);
		
		container.add(new ListView<T>("item", items)
		{

			@Override
			protected void populateItem(final ListItem<T> item)
			{
				T itemObject = item.getModelObject();
				
				item.setOutputMarkupId(true);
				
				item.add(getItemFragment("item_fragment", itemObject));
				
				item.setMetaData(INDEX, itemsList.indexOf(itemObject));
				
				item.add(new DraggableBehavior(JQueryWidget.getSelector(item)) {
					
						@Override
						public void onDragStop(AjaxRequestTarget target, int top, int left) {}
						
						@Override
						public void onDragStart(AjaxRequestTarget target, int top, int left) {}
						
						@Override
						public boolean isStopEventEnabled() { return false; }
					}
					.setOption("axis", "'y'")
					.setOption("revert", "'invalid'")
					.setOption("containment", "'#" + container.getMarkupId() + "'")
				);

				item.add(new DroppableBehavior(JQueryWidget.getSelector(item)) {
					
					@Override
					public void onOver(AjaxRequestTarget target, Component component) {}
					
					@Override
					public void onExit(AjaxRequestTarget target, Component component) {}
					
					@Override
					public void onDrop(AjaxRequestTarget target, Component component)
					{
						int oldIndex = component.getMetaData(INDEX);
						int newIndex = item.getMetaData(INDEX);
						
						if ( oldIndex == newIndex )
							return;
						
						if ( oldIndex < newIndex )
							newIndex--;
						
						T obj = itemsList.remove(oldIndex);
						itemsList.add(newIndex, obj);
						
						for ( int i=newIndex; i < itemsList.size(); i++ )
							setItemOrderValue(itemsList.get(i), i + 1);
						
						container.modelChanged();
						target.add(container);
					}
					
					@Override
					public boolean isOverEventEnabled() { return false; }
					
					@Override
					public boolean isExitEventEnabled() { return false; }
				});
			}
		});
	}

	public abstract Fragment getItemFragment(String id, T itemObject);
	
	public abstract void setItemOrderValue(T itemObject, Integer newOrderValue);
	
}
```

**Comment by sebfz1** [comment]
Well... Why don't you use the Sortable/SortableBehavior? This is exactly what it is intended for... :)
http://www.7thweb.net/wicket-jquery-ui/sortable/DefaultSortablePage

**Comment by VaclavC** [comment]
It seems, that I'am recreating the wheel ;-).

**Comment by sebfz1** [comment]
Indeed :)

**Comment by VaclavC** [comment]
And, of course, solution with Sortable is better. Thank you :).
