### ISSUE TITLE
Hover Intent

### ISSUE THREAD

**Issue by zenith77** [sebfz1/wicket-jquery-ui#164]
Seb, I have no clue how to do this... but I need to create a new Wicket/JqueryUI behaviour that uses this custom piece of Jquery;

http://cherne.net/brian/resources/jquery.hoverIntent.html

I need the 'onEnter' and 'onLeave' methods to trigger some server side code, Wicket ajax style methods, with AjaxRequestTarget parameters.

I know this is possible using your framework, but have no idea how to begin. Can you help?

Cheers,
Col.

**Comment by sebfz1** [comment]
Hi Colin,

I did not had time to migrate the how-to guides to implement custom plugins...
In short:

1/ create your behavior:
```java
public abstract class HoverIntentBehavior extends JQueryBehavior implements IJQueryAjaxAware
```
JQueryBehavior means it is a jquery plugin. JQuery*UI*Behavior would have meant it is a jquery-*ui* plugin...
IJQueryAjaxAware indicates your behavior will hold ajax behaviors (JQueryAjaxBehavior), so #onAjax will be automatically triggered.

2/ add your dependencies (in the ctor)
```java
this.add(new JQueryPluginResourceReference(HoverIntentBehavior.class, "jquery.hoverintent.js"));
```
3/ Test your behavior in a page: 
using html-id: new HoverIntentBehavior("#mylist"). 
using a wicket component: new HoverIntentBehavior(JQueryWidget.getSelector(myComponent)).  

4/ add your behaviors...
```java
private JQueryAjaxBehavior onEnterBehavior;
private JQueryAjaxBehavior onLeaveBehavior;

#bind, create ajax behaviors
component.add(this.onEnterBehavior = this.newOnEnterBehavior());
component.add(this.onLeaveBehavior = this.newOnLeaveBehavior());

#onConfigure, map ajax behaviors function to the plugin.
this.setOption("over", this.onEnterBehavior .getCallbackFunction());
this.setOption("out", this.onLeaveBehavior.getCallbackFunction());

private JQueryAjaxBehavior newOnEnterBehavior()
{
	return new JQueryAjaxBehavior(this) {
	};
}

private JQueryAjaxBehavior newOnLeaveBehavior()
{
	return new JQueryAjaxBehavior(this) {
	};
}
```

5/ test in your page whether #onAjax is triggered

6/ defines your own payload type: override `JQueryAjaxBehavior#newEvent`, returning your custom/extended JQueryEvent.

```java
protected static class EnterEvent extends JQueryEvent {}
protected static class LeaveEvent extends JQueryEvent {}
```

7/ In onAjax, test your payload type and fires your own event:
```java
public void onAjax(AjaxRequestTarget target, JQueryEvent event)
{
	if (event instanceof EnterEvent)
	{
		this.onEnter(target);
	}

	else if (event instanceof LeaveEvent)
	{
		this.onLeave(target);
	}
}
```

8/ in your test page, override onEnter and onLeave... That's it.

Hope that works.. ;)
Best regards,
Sebastien

**Comment by zenith77** [comment]
Awesome mate - that works a treat (and gives me a template for the future).

Cheers again! :D
