### ISSUE TITLE
double submit problem in dialogs

### ISSUE THREAD

**Issue by iluwatar** [sebfz1/wicket-jquery-ui#166]
Is there an example or pattern how to solve double submit problem in wicket-jquery-ui dialogs? An impatient user may double click dialog buttons and cause long running operations to be executed twice.

**Comment by sebfz1** [comment]
Hi,

You can do something like this:

```java
List<DialogButton> buttons = new ArrayList<DialogButton>();

buttons.add(new DialogButton("ok") {
	@Override
	protected CharSequence getCallbackScript(ButtonAjaxBehavior behavior)
	{
		String statement = String.format("$('#%s').button('disable');", behavior.getButton().getMarkupId());
		return statement + super.getCallbackScript(behavior);
	}
});
```

Hope this helps,
Sebastien.

**Comment by iluwatar** [comment]
Thanks! Looks wonderfully simple. I will prototype this.

**Comment by sebfz1** [comment]
Your welcome :)
