### ISSUE TITLE
Menu and DropDownList leak DOM nodes

### ISSUE THREAD

**Issue by martin-g** [sebfz1/wicket-jquery-ui#172]
I use ContextMenu and DropDownList deep in the component hierarchy.
If I repaint a parent container then these Kendo widgets contribute again their JS initialization code and produce extra DOM nodes

**Comment by martin-g** [comment]
There may be more such widgets which leak DOM nodes.

**Comment by sebfz1** [comment]
Well that's an interesting problem because when/if you need to repaint with ajax an element that has been entirely removed... the ART#add will not be able to retrieve it so the repaint will failed...

**Comment by sebfz1** [comment]
Caution before updating master, I will commit in a second...

**Comment by sebfz1** [comment]
Too late (for me), lol !

**Comment by martin-g** [comment]
My problem is that a completely new ContextMenu Wicket component is created in the Ajax request, because a parent uses `addOrReplace()` for one of its children and this child contains the menu (somewhere deeper in its hierarchy).
I think I need to use http://docs.telerik.com/kendo-ui/api/javascript/ui/contextmenu#configuration-target that keeps the root node of the menu close to the Wicket component. Otherwise by default it uses the document.body and thus produces the leak.

**Comment by martin-g** [comment]
Nope. `target` setting is something else. I already use it. Duh.

**Comment by sebfz1** [comment]
In other words, we need to destroy a widget based on a selector, right?

**Comment by sebfz1** [comment]
I meant destroy and remove content..

**Comment by sebfz1** [comment]
I think 'remove' can help here, because it allows a selector (which can be a global selector, like 'li' or '.myItem'?)
http://docs.telerik.com/kendo-ui/api/javascript/ui/contextmenu#methods-remove

**Comment by martin-g** [comment]
I don't see how my use case could be covered.
Here is what happens:
- a page is rendered with some KendoUI widget inside
- some container is re-rendered with an Ajax.
- this container uses addOrReplace() for some of its children before being repainted
- the new Ajax response doesn't know anything about the old KendoUI widgets inside the repainted container. It knows just about the newly created KendoUI widgets.
- because KendoUI adds its autogenerated stuff at the end of the body it is not replaced with my container and thus the leak

**Comment by martin-g** [comment]
A way would be to register to DOM_NODE_REMOVING (https://github.com/apache/wicket/blob/master/wicket-core/src/main/java/org/apache/wicket/ajax/res/js/wicket-event-jquery.js#L294) and then to find all widgets inside the node being removed and destroy them.

**Comment by sebfz1** [comment]
> because KendoUI adds its autogenerated stuff at the end of the body it is not replaced with my container and thus the leak

Yes, that the point, I will make a test on my side... 

> A way would be to register to DOM_NODE_REMOVING

Could be a nice option indeed...

**Comment by sebfz1** [comment]
Do we agree that `destroy` works as expected by itself? But you are experiencing your issue because  `addOrReplace` don't know anything about destroy, right?

**Comment by martin-g** [comment]
Right.

**Comment by martin-g** [comment]
http://stackoverflow.com/a/13256514/497381 looks promising.

**Comment by sebfz1** [comment]
I don't know if kendo-ui uses those pseudos... but I like the DOM_NODE_REMOVING options, I will have a try with this...

**Comment by martin-g** [comment]
I see some `k-window`, `k-animation-container`, etc. But all of them are at the bottom of the body.

**Comment by sebfz1** [comment]
Is DOM_NODE_REMOVING handled somewhere? I do not see any interface, adapter or even something related in `AbstractDefaultAjaxBehavior`...

**Comment by sebfz1** [comment]
Seems that DOM_NODE_ADDED will be a of a better help... Does not work yet, but I am sure to be close to a solution...

**Comment by sebfz1** [comment]
So, DOM_NODE_REMOVING does not seems to be called on target#add time and DOM_NODE_ADDED is called to late... I am looking another way...

**Comment by sebfz1** [comment]
Hi Martin,

I tested something that's seems to work as expected, easily generalizable, and that requires no user action:

```java
interface IDestroyable
{
	void destroy(AjaxRequestTarget target);
}

class DestroyListener implements IListener
{
	@Override
	public void onBeforeRespond(Map<String, Component> map, AjaxRequestTarget target)
	{
		for (Entry<String, Component> entry : map.entrySet())
		{
			Visits.visitPostOrder(entry.getValue(), this.newDestroyVisitor(target));
		}
	}

	protected IVisitor<Component, Object> newDestroyVisitor(final AjaxRequestTarget target)
	{
		return new IVisitor<Component, Object>() {

			@Override
			public void component(Component component, IVisit<Object> visit)
			{
				for (KendoUIBehavior behavior : component.getBehaviors(KendoUIBehavior.class))
				{
					if (behavior instanceof IDestroyable)
					{
						((IDestroyable) behavior).destroy(target);
					}
				}
			}
		};
	}

	@Override
	public void onAfterRespond(Map<String, Component> map, IJavaScriptResponse response)
	{
	}
}

public abstract class ContextMenuBehavior extends MenuBehavior implements IContextMenuListener, IDestroyable
{
	static
	{
		// TODO move to kendo IInitializer
		WebApplication.get().getAjaxRequestTargetListeners().add(new DestroyListener());
	}

	// #destroy
}
``` 

WDYT?

**Comment by sebfz1** [comment]
Hummm, the problem with my method is that it will not work if the ContextMenuBehavior (for instance) is added at a higher level than the component to be repainted which, I guess, is your case...

**Comment by martin-g** [comment]
`IDestroyable` and the AjaxRequestTargetListener looks promising!
Testing it...

**Comment by martin-g** [comment]
It does work well for my use case!
Good suggestion, Sebastien!
Thank you!

**Comment by sebfz1** [comment]
Glad to read this!... :)

I will generalize it asap and test it deeper (if kendo-ui cascades destroy and if it does not lead to js error)...

What also does worry me a bit is this [1]:

> Creating a new widget instance from the leftovers of a destroyed widget may work, but is not recommended. Please initialize new widgets from different (e.g. newly appended) DOM elements. 

Some destroy/repaint may not work as expected for some particular widgets; I'm afraid such cases will have to be fixed/handled one by one...

[1] http://docs.telerik.com/kendo-ui/framework/widgets/destroy

**Comment by sebfz1** [comment]
I've added a testing branch (and forgot to reference this issue in the commit of course...)
https://github.com/sebfz1/wicket-jquery-ui/tree/master-kendo-detroy

First testing on cascade destroy looks good! :)
![screenshot from 2015-05-26 01 08 16](https://cloud.githubusercontent.com/assets/1717144/7802988/bf7a0a70-0343-11e5-8509-6b367fb9d2a8.png)

**Comment by sebfz1** [comment]
Hi Martin,

I applied changes in my local `wicket7.x` branch and used it in my current project...
Even I do not have a massive usage of container repainting here, for the few everything looks good to me...

I would like to commit in master today so you can test it globally: `IDetroyable` is on `KendoUIBehavior` so every widgets will be destroyed if these are going to be repainted... or not, that's what I would like to know! ;) And also if you notice a performance impact...

Are you ok with this?

Thanks & best regards,
Sebastien

**Comment by martin-g** [comment]
Let's test it!

**Comment by sebfz1** [comment]
Committed in master, enjoy! :)

**Comment by martin-g** [comment]
I experience the following JS error now:
```
destroying kendoButton (#apply25d)...
wicket-ajax-jquery-debug-ver-1423486589000.js:130 Wicket.Ajax: Wicket.Ajax.Call.processEvaluation: 
Exception evaluating javascript: TypeError: Cannot read property 'destroy' of undefined, text: (function(){console.info('destroying kendoButton (#apply25d)...')})();
(function(){jQuery('#apply25d').data('kendoButton').destroy();})();
(function(){console.info('destroying kendoButton (#cancel25e)...')})();
(function(){jQuery('#cancel25e').data('kendoButton').destroy();})();
(function(){console.info('destroying kendoWindow (#editGroupWindow25c)...')})();
(function(){jQuery('#editGroupWindow25c').data('kendoWindow').destroy();})();
(function(){console.info('destroying kendoWindow (#facetInNewWindow25f)...')})();
(function(){jQuery('#facetInNewWindow25f').data('kendoWindow').destroy();})();
(function(){console.info('destroying kendoWindow (#configureModificationWindow25b)...')})();
(function(){jQuery('#configureModificationWindow25b').data('kendoWindow').destroy();})();
```

**Comment by martin-g** [comment]
```diff
--- i/wicket-kendo-ui/src/main/java/com/googlecode/wicket/kendo/ui/KendoDestroyListener.java
+++ w/wicket-kendo-ui/src/main/java/com/googlecode/wicket/kendo/ui/KendoDestroyListener.java
@@ -77,7 +77,8 @@ public class KendoDestroyListener extends AjaxRequestTarget.AbstractListener
                        {
                                for (KendoUIBehavior behavior : component.getBehaviors(KendoUIBehavior.class))
                                {
-                                       behavior.destroy(target);
+                                       String js = behavior.widget();
+                                       target.prependJavaScript("var $w="+js+";if($w)$w.destroy()");
                                }
```

This seems to work fine here.

**Comment by martin-g** [comment]
And it seems there are no leaking DOM elements!

**Comment by sebfz1** [comment]
> It seems something has destroyed this button already.

I would say that the element did not exists or does not exist anymore in the DOM. Isn't the case of a button which changed visibility to true?

**Comment by sebfz1** [comment]
> target.prependJavaScript("var $w="+js+";if($w)$w.destroy()");

I take care of this in `#destroy` and commit in a few minutes...

**Comment by martin-g** [comment]
Yes. You are right!
This particular button is in the content of a Window. Initially this Window starts as empty. Later when the user opens it I have a logic that decides what content to put inside it. This is the time when the button appears for a first time in the component tree.
