### ISSUE TITLE
Calendar allways display the same Events

### ISSUE THREAD

**Issue by iamvalls** [sebfz1/wicket-jquery-ui#173]
Hallo i have a Problem,
i have implemented the full calendar of sebfz1 in a application. when a user add some Calendar events it will be displayed, but when he log out and another user come and open the Calender he will see the calendar Events of the first user. If  i run the application again and connect the second User , i will see the Events of the Second User. Anytime i run the application and log Users they will always see the Event of the User who first log in ,in the  Calendar but they will not see their own. Don't know what is the Problem I hop you understand me.

**Comment by sebfz1** [comment]
Hi,

It could be a problem with the way you are loading events... Or something
else, it's hard to answer right now... Please create a quickstart that
repro your issue, in your github account, so I can have a look...

Thanks in advance,
Sebastien

**Comment by iamvalls** [comment]
Ok thank you for the fast answer,i just use the CalendarmodelBehavior and i have a data table calendarEvent where i i get the events to display.
protected IRequestHandler newRequestHandler()
	{
		return new IRequestHandler() {
			@Override
			public void respond(final IRequestCycle requestCycle)
			{
				WebResponse response = (WebResponse) requestCycle.getResponse();

				final String encoding = Application.get().getRequestCycleSettings().getResponseRequestEncoding();
				response.setContentType("text/json; charset=" + encoding);
				response.disableCaching();

				if (model != null)
				{
					List<? extends CalendarEvent> list = model.getObject(); // calls load()

					if (list != null)
					{
						StringBuilder builder = new StringBuilder("[ ");

						int count = 0;
						for (CalendarEvent event : list)
						{
							if (model instanceof ICalendarVisitor)
							{
								event.accept((ICalendarVisitor) model); // last chance to set options
							}

							if (count++ > 0)
							{
								builder.append(", ");
							}
							builder.append(event.toString());
						}

						builder.append(" ]");

						response.write(builder);
					}
				}
			}

tomorow i will create a quicstart for more details..
thank you for you support

**Comment by sebfz1** [comment]
Hi,

I don't see why you need to use the calendarmodelbehavior. You are supposed
to use the calendarmodel, which you can extend to supply your user info
(userId for instance) and query the database according to this, in
#load()...

Best regards,
Sebastien

**Comment by iamvalls** [comment]
Hi,
i found the problem , the singleton of the CalendarDao class will not be destroy wenn a User Sign off.
it will kepp the Old even instance. I try the System.gc(); to free the GC but he still keep the old Values. Do you hav a link where i Can find out how to commit code in Github;



public class CalendarDAO
{
	private static CalendarDAO instance = null;

	/** new event id */
	private static int ID = -1;

	private static synchronized CalendarDAO get()
	{
		if (instance == null)
		{
			instance = new CalendarDAO();
		}

		return instance;
	}

	public static boolean isNew(DemoCalendarEvent event)
	{
		return event != null && event.getId() == ID;
	}

	public static DemoCalendarEvent newEvent(LocalDateTime date)
	{
		return new DemoCalendarEvent(ID, "", Category.PUBLIC, date);
	}

	public static DemoCalendarEvent newEvent(LocalDateTime start, LocalDateTime end)
	{
		return new DemoCalendarEvent(ID, "", Category.PUBLIC, start, end);
	}

	public static DemoCalendarEvent getEvent(int eventId)
	{
		for (DemoCalendarEvent event : get().list)
		{
			if (event.getId() == eventId)
			{
				return event;
			}
		}

		return null;
	}

	public static List<DemoCalendarEvent> getEvents(LocalDate start, LocalDate end)
	{
		List<DemoCalendarEvent> events = new ArrayList<DemoCalendarEvent>();

		CalendarDAO dao = get();

		for (DemoCalendarEvent event : dao.list)
		{
			if (dao.isInRange(event, start.atStartOfDay(), end.atStartOfDay()))
			{
				events.add(event);
			}
		}

		return events;
	}

	public static void addEvent(DemoCalendarEvent event)
	{
		if (event != null)
		{
			if (isNew(event))
			{
				event.setId(get().newId());
			}

			get().list.add(event);
		}
	}

	private final List<DemoCalendarEvent> list;
	private int id = 0;

	public CalendarDAO()
	{
		this.list = new ArrayList<DemoCalendarEvent>();
		this.initList();
	}

	private final void initList()
	{
		this.list.add(new DemoCalendarEvent(this.newId(), "Public event", Category.PUBLIC, LocalDateTime.now()));
		this.list.add(new DemoCalendarEvent(this.newId(), "Private event", Category.PRIVATE, LocalDateTime.now()));
	}

	protected final int newId()
	{
		return ++this.id;
	}

	/**
	 * Helper that indicates whether an event is in the given date range (between start date & end date)
	 *
	 * @param event
	 * @param start
	 * @param end
	 * @return true or false
	 */
	protected boolean isInRange(DemoCalendarEvent event, LocalDateTime start, LocalDateTime end)
	{
		LocalDateTime dateS = event.getStart();
		LocalDateTime dateE = event.getEnd();

		return dateS != null && start.compareTo(dateS) <= 0 && end.compareTo(dateS) >= 0 && // lf
				(dateE == null || (start.compareTo(dateE) <= 0 && end.compareTo(dateE) >= 0));
	}
}

**Comment by martin-g** [comment]
Hi,

See https://help.github.com/ and especially its "Bootcamp" section.

CalendarDAO is a class used for the samples. It uses static members just to make the demo easier. You should not use it as is in production code.

**Comment by iamvalls** [comment]
Ok Thank you.
