### ISSUE TITLE
Problem with modal behavior

### ISSUE THREAD

**Issue by MedKhem** [sebfz1/wicket-jquery-ui#174]
Hi,

I'm using MessageDialog class to get the confirmation of the user to save his modifications on an item or just move to the next item that will be loaded on the same page. here is a snippet of my java code:  

       private  final MessageDialog warningDialog; 

          // Add the warning dialog to remind the user if he forgets to save
            warningDialog = new MessageDialog("warningDialog", "Warning",
                "Are you sure you want to do something?", DialogButtons.YES_NO, DialogIcon.WARN)
           {
            private static final long serialVersionUID = 1L;

            @Override
            public void onClose(AjaxRequestTarget target, DialogButton button)
            {
                // TODO Auto-generated method stub
                if (button != null && button.match(LBL_NO)) {
                    itemSelectionForm.actionNextItem();
                    // Rerender whole page (just lazy right now)
                    target.add(MyPage.this);
                }

            }
        };

        add(warningDialog);

and here where I open the warningDialog after pressing an Ajax button in a form:

     add(new AjaxButton("nextButton")
            {
                private static final long serialVersionUID = 1L;

                @Override
                protected void onSubmit(AjaxRequestTarget target, Form<?> form)
                {
                           
                    warningDialog.open(target);               
                }
            });

and the corresponding  html:
 ```html
<div wicket:id="warningDialog">[warning]</div>'
```
The dialog message is displayed and functional but the problem is that isn't shown as a panel in a modal window. It's just displayed as a text on the current page, with 3 buttons, Yes, No and Close.

 Any idea where the problem is?

**Comment by sebfz1** [comment]
Hi,

Yes, you should have a javascript error in your console...
I tried with the samples and `target.add(MessageDialogPage.this)` and don't have the problem.

Best regards,
Sebastien

**Comment by MedKhem** [comment]
Hi Sebastien,

it was a problem of missing css libraries solved by adding some wicket-jquery-ui dependencies.
Thanks for the answer!

Best,
Mohamed
