### ISSUE TITLE
context menu - left click on another link should close context menu

### ISSUE THREAD

**Issue by jamerlan** [sebfz1/wicket-jquery-ui#175]
Take a look at this example: http://www.7thweb.net/wicket-jquery-ui/menu/ContextMenuPage

if you right click on second link - menu will be shown
then left click on the first link. 
Expected result: menu (its menu for a second link) should be closed
Actual result: menu is still visible

Suggested fix:
Martin Grigorov: It seems you need http://api.jqueryui.com/menu/#method-_closeOnDocumentClick

**Comment by sebfz1** [comment]
Unfortunately `_closeOnDocumentClick` seems to not work as expected, unless I missed something... As a fix, I removed the "INVOKER_CSS_CLASS" click-condition and just replaced by left click...

**Comment by sebfz1** [comment]
Deployed 6.19.3-SNAPSHOT (based on wicket-6.20.0-SNAPSHOT)
