### ISSUE TITLE
Latest versions not on central Maven repo

### ISSUE THREAD

**Issue by ilgrosso** [sebfz1/wicket-jquery-ui#176]
Neither 6.0.20 nor 7.0.0.M5: https://repo1.maven.org/maven2/com/googlecode/wicket-jquery-ui/wicket-jquery-ui/

**Comment by martin-g** [comment]
Right. They are staged at Sonatype.
See http://markmail.org/search/?q=%5Bwicket-jquery-ui%5D+Wicket+jQuery+UI+6.20.0+pre-release.
If there are no issues I'll release it later this week.

**Comment by ilgrosso** [comment]
Sorry, I was getting confused by the message in README.md that says

```
 <version>6.20.0</version> <!-- or 1.5.11, 7.0.0-M6 -->
```

**Comment by martin-g** [comment]
Released!
