### ISSUE TITLE
Wicket7: AbstractDialog.open signature need to be changed

### ISSUE THREAD

**Issue by solomax** [sebfz1/wicket-jquery-ui#177]
Due to latest Wicket7 changed it is no longer possible to open any Dialog using WebSocketRequestHandler (no longer subclass of AjaxRequestTarget)

Could you please change signature of AbstractDialog.open method to be

public final void open(IPartialPageRequestHandler target)

to make it work with WebSocketRequestHandler

Thanks in advance!

**Comment by martin-g** [comment]
The branch has been deployed at Sonatype OSS Snapshots.
Please give it a try!

**Comment by sebfz1** [comment]
Oh, that will be a problem for several components (progressbar and some
other)...
I will have a look at this when I will return (which will be earlier than
expected due to a difficult situation here...)

Please do not close the issue for now...

Thanks Martin for the snapshot! :)

**Comment by sebfz1** [comment]
Oh, just had a quick look at the commit, it seems that you already did everything Martin! Thanks a million!! :)

**Comment by martin-g** [comment]
I've changed all "transitively" called methods by AbstractDialog#open(). But maybe this change will be needed in more places.
For now the changes are in a branch. I won't close the issue.

**Comment by sebfz1** [comment]
Ok, I will have a deeper look next week, thanks again!

**Comment by solomax** [comment]
Also need to be updated:
com.googlecode.wicket.jquery.ui.calendar.Calendar.refresh

**Comment by martin-g** [comment]
Done. A new snapshot is deployed.

**Comment by solomax** [comment]
Thanks!
Works as expected
