### ISSUE TITLE
warnings in javascript console (both chrome and firefox) wicket 6.20 + wicket-jquery-ui 6.20.0

### ISSUE THREAD

**Issue by jamerlan** [sebfz1/wicket-jquery-ui#178]
warnings in javascript console (both chrome and firefox) wicket 6.20 + wicket-jquery-ui 6.20.0

we have this in pom.xml
```xml
		<dependency>
			<groupId>com.googlecode.wicket-jquery-ui</groupId>
			<artifactId>wicket-jquery-ui</artifactId>
			<version>6.20.0</version>
		</dependency>
		<dependency>
			<groupId>com.googlecode.wicket-jquery-ui</groupId>
			<artifactId>wicket-kendo-ui</artifactId>
			<version>6.20.0</version>
		</dependency>
		<dependency>
			<groupId>com.googlecode.wicket-jquery-ui</groupId>
			<artifactId>wicket-jquery-ui-theme-uilightness</artifactId>
			<version>6.20.0</version>
		</dependency>
		<dependency>
			<groupId>com.googlecode.wicket-jquery-ui</groupId>
			<artifactId>wicket-kendo-ui-theme-default</artifactId>
			<version>6.20.0</version>
		</dependency>
```
We have updating panels (with trees which have context menus) via ajax and we have MANY warnings in console like listed at the bottom. But if we use "6.19.2" version of "wicket-jquery-ui" even with wicket 6.20 - no warnings in console (but context menu is working incorrectly in firefox with 6.19.2 and wicket 6.20). 

TypeError: $w.destroy is not a function
Stack trace:
@http://localhost:8080/wicket/resource/org.apache.wicket.ajax.AbstractDefaultAjaxBehavior/res/js/wicket-ajax-jquery-ver-1435914959000.js line 1200 > eval:1:73
@http://localhost:8080/wicket/resource/org.apache.wicket.ajax.AbstractDefaultAjaxBehavior/res/js/wicket-ajax-jquery-ver-1435914959000.js line 1200 > eval:1:2
Wicket.Ajax.Call.prototype.processEvaluation/evaluate/<@http://localhost:8080/wicket/resource/org.apache.wicket.ajax.AbstractDefaultAjaxBehavior/res/js/wicket-ajax-jquery-ver-1435914959000.js:1200:7
FunctionsExecuter/this.processNext/run@http://localhost:8080/wicket/resource/org.apache.wicket.ajax.AbstractDefaultAjaxBehavior/res/js/wicket-ajax-jquery-ver-1435914959000.js:139:14
.proxy/proxy@http://localhost:8080/wicket/resource/org.apache.wicket.resource.JQueryResourceReference/jquery/jquery-1.11.3-ver-1435914959000.js:548:11
FunctionsExecuter/this.processNext@http://localhost:8080/wicket/resource/org.apache.wicket.ajax.AbstractDefaultAjaxBehavior/res/js/wicket-ajax-jquery-ver-1435914959000.js:154:21
FunctionsExecuter/this.start@http://localhost:8080/wicket/resource/org.apache.wicket.ajax.AbstractDefaultAjaxBehavior/res/js/wicket-ajax-jquery-ver-1435914959000.js:166:16
FunctionsExecuter/this.notify@http://localhost:8080/wicket/resource/org.apache.wicket.ajax.AbstractDefaultAjaxBehavior/res/js/wicket-ajax-jquery-ver-1435914959000.js:171:4
.proxy/proxy@http://localhost:8080/wicket/resource/org.apache.wicket.resource.JQueryResourceReference/jquery/jquery-1.11.3-ver-1435914959000.js:548:11
.Head.Contributor.processScript/</onScriptReady@http://localhost:8080/wicket/resource/org.apache.wicket.ajax.AbstractDefaultAjaxBehavior/res/js/wicket-ajax-jquery-ver-1435914959000.js:2230:9

**Comment by jamerlan** [comment]
Issue is in this component:
		<dependency>
			<groupId>com.googlecode.wicket-jquery-ui</groupId>
			<artifactId>wicket-jquery-ui</artifactId>
			<version>6.20.0</version>
		</dependency>
If I downgrade it to 6.19.2 - no warnings are printed (but not usable with 6.20 wicket)

**Comment by sebfz1** [comment]
Hi Alexander,

Yes, these warnings are on purpose in 6.20.0 (sorry if it's flooding your
console), these will be removed in the next version (6.20.1, in 2 weeks I
think). I should identify which cases throws these warnings and if these
does not hide an issue...

Sorry again for the inconvenience.

Best regards,
Sebastien

**Comment by martin-g** [comment]
On Jul 3, 2015 12:36 PM, "Alexander Lipatov" <notifications@github.com>
wrote:
>
> Issue is in this component:
>
> com.googlecode.wicket-jquery-ui
> wicket-jquery-ui
> 6.20.0
>
> If I downgrade it to 6.19.2 - no warnings are printed (but not usable
with 6.20 wicket)

Sure, it is usable.
Just avoid using the newly introduced method in Form.java (I don't remember
its name right now)

**Comment by jamerlan** [comment]
>>Sure, it is usable.
>>Just avoid using the newly introduced method in Form.java (I don't remember
>>its name right now)
Context menu is auto-closing after it was opened under firefox

**Comment by martin-g** [comment]
My application runs with Wicket 6.17 and Wicket jQuery UI 6.20 without any problems.
I use KendoUI ContextMenu component.
