### ISSUE TITLE
context menu - left click on another link should close context menu - 2

### ISSUE THREAD

**Issue by jamerlan** [sebfz1/wicket-jquery-ui#179]
Looks like this bug: https://github.com/sebfz1/wicket-jquery-ui/issues/175
is not fixed for ajax. Is fix included in 6.20.0?

Tested in 6.20.0
Looks like it not works if ajax is used. We have a tree with many nodes. Each node have context menu. On click - panel refreshed near the tree via ajax and context menu opened for another node - not closed.

**Comment by sebfz1** [comment]
Hi Alexander,

Yes, it is supposed to be fixed in 6.20.0. Can you provide a quickstart so I can have a look next week ?

Thanks in advance,
Sebastien.

**Comment by jamerlan** [comment]
Created. I dont know how to attach it here. So I shared using dropbox.

Looks like bug happens when you use context menu on ajax links. In our app we have a tree where each node is ajax link and it have context menu also.

https://www.dropbox.com/s/sm7iidcax9g2uf5/myproject.zip?dl=0

How to reproduce: right click on link to display context menu then left click on another link
expected result: menu dissappeared
actual result: menu is still shown

**Comment by martin-g** [comment]
In Wicket 6.x Ajax behaviors disable the bubbling of the JS event.
You should do this explicitly l.

**Comment by jamerlan** [comment]
How to do it explicitly? We have a lot of menus... Maybe when we add ContextMenuBehaviour it can also add some JS that will be automatically executed? If this is not possible.. maybe I can run some JS myself? like $(".menus").close() - is it possible to have such universal script for all menus?

**Comment by martin-g** [comment]
Override AnotherLink#updateAjaxAttributes and call
attributes.setEventPropagation(BUBBLE)

**Comment by sebfz1** [comment]
I confirm Martin's answer solves the question, so closing...
