### ISSUE TITLE
Change color of event.

### ISSUE THREAD

**Issue by evalls** [sebfz1/wicket-jquery-ui#180]
Hi sebfz1 please i have 2 questions,
1-  how can i Change the Color of a CalendarEvent?
2- when i use a downloadlink i can generate a file for the user like This:

 DownloadLink link = new DownloadLink(wicketID, new AbstractReadOnlyModel<File>() {
            private static final long serialVersionUID = 1L;

            @Override
            public File getObject() {
                File tempFile;
                try {
                    tempFile = File.createTempFile("test", ".csv");
                    InputStream data = new ByteArrayInputStream("some calendarEvent".getBytes());
                    Files.writeTo(tempFile, data);

                } catch (IOException e) {
                    throw new RuntimeException(e);
                }

                return tempFile;
            }
        }
        ).setCacheDuration(Duration.NONE).setDeleteAfterDownload(true);
        return link;
    }
how can i do it in a onsubmit methode of a button: i am trying to export my CalenderEvents?

I hope you will help me..........

**Comment by martin-g** [comment]
For 2) see https://github.com/apache/wicket/blob/master/wicket-core/src/main/java/org/apache/wicket/markup/html/link/DownloadLink.java#L152-L185

**Comment by martin-g** [comment]
For 1) I see there is a setter - https://github.com/sebfz1/wicket-jquery-ui/blob/master/wicket-jquery-ui-calendar/src/main/java/com/googlecode/wicket/jquery/ui/calendar/CalendarEvent.java#L166

**Comment by evalls** [comment]
ok thk you for your fast answer. I will try it now and let you know.

**Comment by evalls** [comment]
is there some thing to pay attention again when i  export CalendarEvent. I use what you show me and i'm getting this error:

Wicket.Ajax.Call.failure: Error while parsing response: Not Found

**Comment by sebfz1** [comment]
Hi,

Additionally if you would like to change the color in a lazy way (when these are loaded by the model) you could make `YourCalendarModel implements ICalendarVisitor`.

https://github.com/sebfz1/wicket-jquery-ui/blob/master/wicket-jquery-ui-samples/src/main/java/com/googlecode/wicket/jquery/ui/samples/data/DemoCalendarModel.java#L29

Best regards,
Sebastien

**Comment by evalls** [comment]
My onSubmit() look like this:

 @Override
                    public void onSubmit(AjaxRequestTarget target)
                    {
               
               
              final File file = new File("myfile"); // that is just a test
		if (file == null)
		{
			throw new IllegalStateException(getClass().getName() +
				" failed to retrieve a File object from model");
		}
                       

		String fileName = fileNameModel != null ? fileNameModel.getObject() : null;
		if (Strings.isEmpty(fileName))
		{
			fileName = file.getName();
		}

		IResourceStream resourceStream = new FileResourceStream(
			new org.apache.wicket.util.file.File(file));
                        Duration cacheDuration = null;
		getRequestCycle().scheduleRequestHandlerAfterCurrent(
			new ResourceStreamRequestHandler(resourceStream)
			{
				public void respond(IRequestCycle requestCycle)
				{
					super.respond(requestCycle);
                                    boolean deleteAfter = false;

					if (deleteAfter)
					{
						Files.remove(file);
					}
				}
			}.setFileName(fileName)
				.setContentDisposition(ContentDisposition.ATTACHMENT)
				.setCacheDuration(cacheDuration));
                    
                        
                        }

**Comment by sebfz1** [comment]
The error message is not clear enough to me to identify the issue.
I don't exactly how your code looks like, but to export datatable rows for instance, I have the following:
https://github.com/sebfz1/wicket-jquery-ui/blob/master/wicket-kendo-ui/src/main/java/com/googlecode/wicket/kendo/ui/datatable/export/CSVDataExporter.java (itself based on wicket's CSVDataExporter).

The usage is as simple as: `@ Override public void onSubmit() { CSVDataExporter.export(myTable, "table.csv"); }

Maybe can you get inspiration from this, replacing the `DataTable/IDataProvider` by `Calendar/CalendarModel`...

**Comment by evalls** [comment]
Thk you martin and sebfz1,
i made it. I can change  the Color of my Events.......
