### ISSUE TITLE
 DialogButton btnSubmit 

### ISSUE THREAD

**Issue by evalls** [sebfz1/wicket-jquery-ui#181]
Hi sebfz1 und martin,
please where do i fine the HTML  of the DialogButton btnSubmit or how are this button generated when i do:
protected final DialogButton btnSubmit = new DialogButton("Speichern", JQueryIcon.CHECK);
i want to edit it
please don't mine my English.....

**Comment by martin-g** [comment]
Hi,

jQuery UI Dialog uses JSON to setup its buttons. See http://api.jqueryui.com/dialog/#option-buttons and the code of http://jqueryui.com/dialog/#modal-form demo

**Comment by evalls** [comment]
What amase me is that the button does have a wicket id.

**Comment by martin-g** [comment]
Which button?

**Comment by martin-g** [comment]
See https://github.com/sebfz1/wicket-jquery-ui/blob/master/wicket-jquery-ui/src/main/java/com/googlecode/wicket/jquery/ui/widget/dialog/DialogButton.java#L141
It has autogenerated id, a name, an icon, ...

**Comment by evalls** [comment]
ok thk you for your help..........

**Comment by martin-g** [comment]
Welcome!
