### ISSUE TITLE
Remove XxxBehavior implements XxxListener, pass XxxListener to ctors directly and provide XxxAdapter if needed

### ISSUE THREAD

**Issue by sebfz1** [sebfz1/wicket-jquery-ui#184]
This issue aims to separate event/listener concerns from the behavior.
This will lead to some API breaks for advanced users, but will definitely ease behavior overrides in widgets...

**Comment by sebfz1** [comment]
@martin-g , @solomax 

I think you will like this enhancement (and maybe hate me for another API break...)

Your advices/comments are welcome of course, you can track current and future changes using:
https://github.com/sebfz1/wicket-jquery-ui/compare/master-adapters

Best regards,
Sebastien

**Comment by martin-g** [comment]
:+1: I DO like it!
This will indeed simplify some of my code where I need to copy/paste all the methods of the anonymous behavior class in my specialization of a component!

**Comment by solomax** [comment]
I also like the changes :)

**Comment by sebfz1** [comment]
Glad to read you like it! :)
I will continue this way, hoping being able to do it quickly in order integrate this change in `7.0.0`...

**Comment by sebfz1** [comment]
Deployed `7.0.0-SNAPSHOT`, I will test it tomorrow.
If everything looks good I will release `7.0.0` this WE...

**Comment by solomax** [comment]
Just updated, only 1 compilation error :))))
not a big deal :)

**Comment by sebfz1** [comment]
- [ ] `XxxListener` should be `IClusterable`
