### ISSUE TITLE
How to get the methode of the "X" button of the abstractFormDialog

### ISSUE THREAD

**Issue by evalls** [sebfz1/wicket-jquery-ui#185]
Hi Sebastian,
do you know if there is a way to know ,if the "X" button to close the abstractFormDialog was clicked?
I have the problem that, when i click the Cancel Button i call a method but when i press the "X" button, i don't know how to call my methode on it because when xou click the "X" button, it does call the onClose method.
Thank you in advance.......

**Comment by sebfz1** [comment]
IIRC, the button arg is null if X was clicked... Also I am quite sure there
is a method to prevent the X button firing the ajax event.... Hope this
helps!

**Comment by sebfz1** [comment]
`AbstractDialog#isDefaultCloseEventEnabled()` returns `false` by default, so just override it and the 'X-icon' will fire the `#onClose` event...

Javadoc:
https://github.com/sebfz1/wicket-jquery-ui/blob/master/wicket-jquery-ui/src/main/java/com/googlecode/wicket/jquery/ui/widget/dialog/IDialogListener.java#L36

**Comment by iamvalls** [comment]
Thank you  very much......
