### ISSUE TITLE
CustomTooltipBehavior should also escape "\r"

### ISSUE THREAD

**Issue by reckart** [sebfz1/wicket-jquery-ui#186]
I've just spent quite a while trying to figure out why one of my tooltips broke... and the reason was that it was fill from a data source using Windows line endings.

The CustomTooltipBehavior should be changed to also escape "\r":

	protected String escape(String content)
	{
		return content.replace("\t", "").replace("\n", "").replace("\r", "").replace("\"", "'");
	}

**Comment by reckart** [comment]
Wow, that was fast! Thanks :)

**Comment by sebfz1** [comment]
Hi,

You are welcome :)
Currently deploying 6.20.1-SNAPSHOT & 7.0.0-SNAPSHOT, will be available in the next 10 mins...

Enjoy,
Sebastien.

**Comment by reckart** [comment]
I was just wondering... "\r" helped in my case, but looking at JSONObject.quote(String), there might also be other cases to be considered.  

I wonder whether using JSONObject.quote() in CustomTooltipBehavior.bind(Component) when setting *this.setOption("content", ...* wouldn't be the safer fix. WDYT?

**Comment by sebfz1** [comment]
Yes, this would be logical...

I think I wasn't using JSONObject#quote the time I coded CustomTooltipBehavior; I still considering it a little bit heavy, but I should say it works well so now I'm quite fine for using it...

That would means I should remove #escape; let me think about this tomorrow...

**Comment by reckart** [comment]
In case somebody wants to "post-process" data between the model and the rendering it could still be used, e.g. when somebody really wants to replace a \t by (non-breaking) spaces instead of letting the browser handle the \t. But I guess for what escape() does now, JSONObject.quote(String) might be the better choice. Maybe leave escape() around a bit more as a NOP? Removing it would be a breaking change anyway.

**Comment by sebfz1** [comment]
Yes that's what I was currently thinking, but : 
- either the content is already quoted (#escape = no-op)
- #escape returns JSONObject#quote by default, up to the user to change if needed

I prefer the first, but both cases are error prone if the user replace the double quotes... Maybe will I have a better idea tomorrow... Good night :)

**Comment by sebfz1** [comment]
I finally opted for a mix because the first was not suitable and the second was misleading.
I've introduced `#quote()` and deprecated `#escape()`.
