### ISSUE TITLE
Eager to upgrade to 7.0.0

### ISSUE THREAD

**Issue by doncferguson** [sebfz1/wicket-jquery-ui#187]
Will a 7.0.0 version be coming soon?  Please oh please?

**Comment by sebfz1** [comment]
I will stage it tonight (normally) and let users test it for several days
before pushing it to maven central...

**Comment by doncferguson** [comment]
Many thanks.

-Don

On Mon, Aug 3, 2015 at 11:13 AM, Sebastien Briquet <notifications@github.com

**Comment by sebfz1** [comment]
Done, enjoy! :)
http://markmail.org/message/wjegxum23pfffnhh
