### ISSUE TITLE
How to set the next button arrow of the header Calendar..

### ISSUE THREAD

**Issue by iamvalls** [sebfz1/wicket-jquery-ui#188]
Hi Sebastian and Martin ,
i'm trying to set the theme of my full calendar and when i set the theme  to true , the arrow of the next and prev Button doesnt appear again, but when i set it to false, it appear. Do you have any idea?
![withouttheme](https://cloud.githubusercontent.com/assets/12074291/9115391/2037a12a-3c5f-11e5-8ca0-8989d3cbf0a9.PNG)
![withtheme](https://cloud.githubusercontent.com/assets/12074291/9115397/28b7d482-3c5f-11e5-8cca-0395fb9a1390.PNG)

thk you

**Comment by sebfz1** [comment]
Hi,
Does it repro in a quickstart? If yes, please make a repo with the
quickstart and I will try to have a look tomorow...
Thanks,
Sebastien

**Comment by iamvalls** [comment]
it is not a quickstart

**Comment by sebfz1** [comment]
Please try in a quickstart. If it does repro the issue, push your
quickstart in a github project, or attach it in the forum....

Thanks,
Sebastien

**Comment by iamvalls** [comment]
Hi Sebastian I solve the Problem the image and Jquery-ui.css, kendo.....  was in a wrog package.
thk you
