### ISSUE TITLE
DialogButton ctor looses parameter

### ISSUE THREAD

**Issue by solomax** [sebfz1/wicket-jquery-ui#190]
DialogButton(string, string, string, bool) passes null as icon parameter

Sorry for short descent, from mobile :(

**Comment by solomax** [comment]
Version 6.20

**Comment by martin-g** [comment]
@solomax Thanks!
@sebfz1 I'll let you merge this back to wicket6.x.

**Comment by martin-g** [comment]
Reopen the issue until it is merged to 6.x

**Comment by sebfz1** [comment]
Thanks Martin for the fast correction!!
I am deploying `7.0.1-SNAPSHOT` and will merge to 6.x later today...
@solomax if you need a final version I can release 7.0.1 tonight...

**Comment by ArtyomSavchenko** [comment]
Thanks for the fix
I currently have no time to test it :( so no rush :)

**Comment by solomax** [comment]
Thanks for the fix
I currently have no time to test it :( so no rush :)

**Comment by sebfz1** [comment]
Fixed on `wicket6.x` branch by 2dd0c73d1d8b1aea082caa0d1ac1b54c9fc3a55d

**Comment by sebfz1** [comment]
Released  `7.0.1` and `6.20.1`
https://github.com/sebfz1/wicket-jquery-ui/releases/tag/wicket-jquery-ui-7.0.1
