### ISSUE TITLE
'X' icon button of the Abstractformdialog doesnt show. 

### ISSUE THREAD

**Issue by iamvalls** [sebfz1/wicket-jquery-ui#192]
Hello, it is me again,
i created a dialog extending the abstractformdialog. The close button on top rigth ist there but the 1 'x' icon doesnt show. what could be the reason? I read somewhere that Bottstrap and JQuery UI can have conflict

Thk you.

**Comment by paulbors** [comment]
Feel free to follow the examples at:
http://www.7thweb.net/wicket-jquery-ui/dialog/MessageDialogPage

On Thu, Aug 20, 2015 at 11:38 AM, iamvalls <notifications@github.com> wrote:

> Hello, it is me again,
> i created a dialog extending the abstractformdialog. The close button on
> top rigth ist there but the 1 'x' icon doesnt show. what could be the
> reason? I read somewhere that Bottstrap and JQuery UI can have conflict
>
> Thk you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sebfz1/wicket-jquery-ui/issues/192>.
>



-- 
~ Thank you,
   Paul Bors

**Comment by martin-g** [comment]
I guess it is some clash of CSS classes (JQuery UI and Bootstrap)

**Comment by iamvalls** [comment]
Hi paulbors that is the examples i use.

**Comment by iamvalls** [comment]
![x icon](https://cloud.githubusercontent.com/assets/12074291/9405137/6d80a3f4-47f5-11e5-9678-e6de96347285.PNG)
 that is what i hav.

**Comment by iamvalls** [comment]
can please somebody help me :) .

**Comment by martin-g** [comment]
No.
Without a quickstart we can only watch movies (well pictures in this case :) ).
As I said it should be a problem with mixed CSS libraries. Open browser's Dev Tools and see what CSS classes are applied on this button.

**Comment by iamvalls** [comment]
ok thank you martin.

**Comment by sebfz1** [comment]
Hi,

Did you find the problem? Should we close this issue?

Thanks,
Sebastien.

**Comment by iamvalls** [comment]
Hi,
the Problem is my Css, i will fix it today. As soon i do it i will let you know.
