### ISSUE TITLE
empty wizard is displayed if "autoOpen" option is used

### ISSUE THREAD

**Issue by solomax** [sebfz1/wicket-jquery-ui#202]
Hello Sebastien,

was reproducible with 6.20.1:

steps
1) create wizard with only step displaying dynamic text (single Label child element)
2) add "autoOpen" option inside onConfigure method
Result: wizard is displayed empty

I'll try to reproduce it later using latest SNAPSHOT (currently at airport :(( )	
Thanks in advance!

**Comment by sebfz1** [comment]
Hi Maxim,

Unfortunatly `autoOpen` option cannot be supported in Wizard, I've updated AbstractWizard#onConfigure(JQueryBehavior)` javadoc accordingly.

You can use this code snippet as a workaround:

```java
class MyWizard ... {

	@Override
	protected void onConfigure()
	{
		super.onConfigure();
		
		this.add(new AbstractDefaultAjaxBehavior() {
			
			private static final long serialVersionUID = 1L;
			
			@Override
			public void renderHead(Component component, IHeaderResponse response)
			{
				super.renderHead(component, response);
				
				response.render(OnDomReadyHeaderItem.forScript(this.getCallbackScript()));
			}
	
			@Override
			protected void respond(AjaxRequestTarget target)
			{
				MyWizard.this.open(target);
			}
		});
	}
}
```

Best regards,
Sebastien.

**Comment by solomax** [comment]
Thanks!
Actually I thought it is not supported, and have asked just to ensure :)
