### ISSUE TITLE
ui issue with split button

### ISSUE THREAD

**Issue by solomax** [sebfz1/wicket-jquery-ui#203]
Hello Sebastien,

Steps:
1) go to page http://www.7thweb.net/wicket-jquery-ui/button/AjaxSplitButtonPage
2) select "down arrow" to display drop-down list
3) select any choice (for ex. "delete")
Result: info on selected action is displayed correctly, but there is no "down arrow" anymore

**Comment by sebfz1** [comment]
I should postpone investigation of this one for a few days...
@Patrick1701 do you think you can have a look at this one?

**Comment by Patrick1701** [comment]
Hi Sebastien,
yes, I had a similar issue on my local legacy SplitButton impl some weeks ago.
But not onClick... maybe its somehow the same... I will have a look problem.

best regards
Patrick

**Comment by Patrick1701** [comment]
Ok, found it.
Wasn't a css issue, like my some weeks ago. Was an ajax refreshing issue.
Will create a pull request, next.

Patrick
