### ISSUE TITLE
Add a style to the Submit button of abstractDialog 

### ISSUE THREAD

**Issue by iamvalls** [sebfz1/wicket-jquery-ui#206]
Hi Sebastian
ist there a way to add some Style class to the submit button of a AbstractDialog. I have something like this:
protected final transient DialogButton btnSubmit = new DialogButton((new StringResourceModel("save", this, null)).getString(), JQueryIcon.CHECK);

and i want to add some Style on it without Usind the TemeRoller.

**Comment by sebfz1** [comment]
Hi,

You can override #getMarkupId (returning `myButtonId`) and specify a style
in your css: #myButtonId { ... }
Just be sure the markup id will remain unique...

For general questions, please use the forum. GitHub issues are for bugs &
enhancement requests.

Best regards,
Sebastien

**Comment by iamvalls** [comment]
Ok Thank you.
