### ISSUE TITLE
Use ServiceLoader instead of /META-INF/wicket/**.properties

### ISSUE THREAD

**Issue by martin-g** [sebfz1/wicket-jquery-ui#207]
Hi Sebastien,

I guess you have already noticed the discussion at Wicket dev@ about deprecating the custom `/META-INF/wicket/` way to find all IInitializer implementations. See http://markmail.org/message/o5jvwjmmezu4xebe for details.

All files like:
https://github.com/sebfz1/wicket-jquery-ui/blob/master/wicket-kendo-ui/src/main/resources/META-INF/wicket/com.googlecode.wicket.kendo.ui.properties
should be reworked for 7.1.0. The old functionality will be there until Wicket 7.3.0 so this task is not really urgent now.
Just let me know when and I can make the changes.

**Comment by sebfz1** [comment]
Hi Martin,

Right, I saw the discussion. I did not took position as all OSGi & webjar/uberjar stuff are completely blackboxes to me :-/
I will upgrade to 7.1.0 probably tomorrow, so I guess the change would be ready to be done. Thank you very much in advance!

**Comment by martin-g** [comment]
OK. I'll do it now!

**Comment by sebfz1** [comment]
All right! :)

**Comment by martin-g** [comment]
PR: #208
