### ISSUE TITLE
StackOverFlow / infinite loop in KendoDataSource/SchedulerDataSource

### ISSUE THREAD

**Issue by Patrick1701** [sebfz1/wicket-jquery-ui#210]
Hi Sebastien,
today I updated to ```6.20.2``` and got a infinite loop.
```
java.lang.StackOverflowError
	java.util.HashMap.hash(HashMap.java:362)
	java.util.HashMap.put(HashMap.java:492)
	com.googlecode.wicket.jquery.core.Options.set(Options.java:230)
	com.googlecode.wicket.kendo.ui.KendoDataSource.prepareRender(KendoDataSource.java:126)
	com.googlecode.wicket.kendo.ui.KendoDataSource.toString(KendoDataSource.java:140)
	com.googlecode.wicket.kendo.ui.scheduler.SchedulerDataSource.toScript(SchedulerDataSource.java:56)
	com.googlecode.wicket.kendo.ui.KendoDataSource.toString(KendoDataSource.java:140)
	com.googlecode.wicket.kendo.ui.scheduler.SchedulerDataSource.toScript(SchedulerDataSource.java:56)
	com.googlecode.wicket.kendo.ui.KendoDataSource.toString(KendoDataSource.java:140)
	com.googlecode.wicket.kendo.ui.scheduler.SchedulerDataSource.toScript(SchedulerDataSource.java:56)
	com.googlecode.wicket.kendo.ui.KendoDataSource.toString(KendoDataSource.java:140)
	com.googlecode.wicket.kendo.ui.scheduler.SchedulerDataSource.toScript(SchedulerDataSource.java:56)
	com.googlecode.wicket.kendo.ui.KendoDataSource.toString(KendoDataSource.java:140)
	com.googlecode.wicket.kendo.ui.scheduler.SchedulerDataSource.toScript(SchedulerDataSource.java:56)
```

Thanx for help!
kind regards
Patrick

**Comment by sebfz1** [comment]
Hi Patrick,

Yes, I am very (very) sorry for this! This has been corrected by eed81774d247d9bd583782f25edb89ac5292c106. I will deploy a bugfix version tonight if you need it.

Apologies for the problem it may have cause! :/

Best regards,
Sebastien.

**Comment by Patrick1701** [comment]
Tonight or tomorrow night would be great! :)

Thank you!
Patrick

**Comment by sebfz1** [comment]
Hi Patrick,

`6.20.3` has been released :)

Best regards,
Sebastien

**Comment by sebfz1** [comment]
**Caution:** Kendo UI version has been upgraded to `2015.3.930`. 
I don't think there is API Breaks; I will do the `7.1.0` changelog tomorow (code is aligned with `6.20.3`) and I will let you know...

**Comment by sebfz1** [comment]
Hi Patrick,

Here is the changelog:
https://github.com/sebfz1/wicket-jquery-ui/releases/tag/wicket-jquery-ui-7.1.0

Best regards,
Sebastien
