### ISSUE TITLE
ID returned by ComboBox.getMarkupId() is not for actual input field

### ISSUE THREAD

**Issue by reckart** [sebfz1/wicket-jquery-ui#211]
It appears as if the Kendo ComboBox widget is taking the original input element on which it is defined, hides it, and creates a new input with dropdown selection list etc it in its place. However, the old input element still remains in the DOM and still has the component ID. When calling ComboBox.getMarkupId() we get the old hidden element, not the new one. Of course we cannot do much with the old element, e.g. we cannot focus it. Wouldn't it be better to move the component ID attribute over to the new element?

**Comment by sebfz1** [comment]
Hi Richard,

> Wouldn't it be better to move the component ID attribute over to the new element?

This is definitely not possible, Kendo UI is managing this part after wicket has rendered the page.
If you want to access the "new" (ie: outermost) element, in javascript, you have the `wrapper` property
http://docs.telerik.com/kendo-ui/framework/widgets/wrapper-element

You can get it like this: (`this` being the ComboBox)
```
String wrapper = KendoUIBehavior.widget(this, ComboBoxBehavior.METHOD) + ".wrapper";
```

Hope this helps,
Sebastien.

**Comment by reckart** [comment]
Thanks for the pointer :)
