### ISSUE TITLE
Kendo UI date pattern does not support 'EEE'

### ISSUE THREAD

**Issue by sebfz1** [sebfz1/wicket-jquery-ui#216]

**Comment by hfriederichs** [comment]
Sebastien, I cannot reopen this issue, so I'll put the details here.
Even with the deault locale (en_US) and using:

@Override
			public void renderHead(IHeaderResponse response) {
				super.renderHead(response);
				response.render(new KendoCultureHeaderItem(KendoCulture.EN_US));
			}

the behaviour is:
Correct display at opening of teh form that contains the AjaxDateTimePicker:
Tue 1 March 2016
Incorrect display as soon as you pick another date:
EEE 2 March 2016
along with an error:
Error while parsing datetime: date was 'EEE 2 March 2016' and time was '22.00'

**Comment by sebfz1** [comment]
Thank you, I've repro the issue. I try to investigate this asap.

**Comment by sebfz1** [comment]
Hi,

Kendo UI's datepicker culture and wicket locale (at session or component level) should match.
By using KendoCultureHeaderItem you sets kendo ui widgets to a specific culture, so the session/component locale should be set.

Please override datepicker#getLocale() returning the same locale/language-code you defined with KendoCultureHeaderItem.

I will work on providing more a convenient way...

Thanks & best regards,
Sebastien.

**Comment by hfriederichs** [comment]
It still does'nt work. My Code:

private final static String dateDisplay = "EEEE d MMMM yyyy";
private final static String timeDisplay = "HH.mm";

scheduleDateTimeField = new AjaxDateTimePicker("scheduledatumtijd", planDateModel, dateDisplay, timeDisplay) {

			private static final long serialVersionUID = 4648604650274730058L;
			
			@Override
			public void renderHead(IHeaderResponse response) {
				super.renderHead(response);
				response.render(new KendoCultureHeaderItem(KendoCulture.NL_NL));
			}
			
			@Override
			public Locale getLocale() {
				return new Locale("nl", "NL");
			}

			@Override
			public void onValueChanged(IPartialPageRequestHandler handler) {
				if (getModelObject().before(new Date())) {
					error("Gekozen datum/tijd ligt in het verleden");
					handler.add(scheduleDateTimeField);
				}
				handler.add(getFeedbackPanel());
			}

		};

Page renders at first with correct DateTime: maandag 7 maart 2016 (maandag=monday, maart=march)
But when onValueChanged is executed:
Error while parsing datetime: date was 'EEEE 8 maart 2016' and time was '13.29'

**Comment by sebfz1** [comment]
Weird, I will retry with your exact use-case...

**Comment by sebfz1** [comment]
Hi,

I've retry with your use-case (nl-NL) and its works in my case.
Could you please create a quickstart so I can have a look? Maybe I missed something in my retry !?

Thanks in advance,
Sebastien.

**Comment by sebfz1** [comment]
> if (getModelObject().before(new Date())) {

btw the way, you can set the option at js/kendo level, something like this:

```java
DatePicker#onConfigure(JQueryBehavior behavior)
{
//call super!
behavior.setOptions("min", "new date()")
}
```

**Comment by sebfz1** [comment]
Hi,

(@solomax & @Patrick1701, FYI)

I've reworked `[local.][[Ajax]Date|Time]Picker` to better support `Locale`
The major behavioral change is that you can supply a Locale and/or a pattern.

*But*, if you supply a Locale, it will act as the Component's Locale (ie, the localized version). That's the difference between the previous version where the Locale was only to guess the pattern (ie: dd/MM/yyyy for French), and sets the widget's culture. But it was leading to some issues with localized dates (name of days or months for instance). That's also means you don't have to override `#getLocale` anymore.

I've released `6.22.2` & `7.2.1`, please give it a try.

Btw, the samples now covers 54 use cases: DatePicker, TimePicker, DateTimePicker, Ajax and non-Ajax, Ajax vs submitted, Java Dates & Java Local[Date][Time].

If you (still?) encounter an issue; please fork the project, find the closest sample and repro the issue in there.

Best regards & enjoy,
Sebastien.

**Comment by Patrick1701** [comment]
Hi Sebastien,
thanx for the info.

I think, I'm not affected...
I use the normal AjaxDateTimePicker, like this:

```
AjaxDateTimePicker startPicker = new AjaxDateTimePicker("start"
												, start
        										, LocaleUtils.getLocaleDatePattern(UserSession.get().getLocale())
        										, LocaleUtils.getLocaleTimePattern(UserSession.get().getLocale())
        										)
```

Works well, or do I have bugs, without knowing it?
I guess, I do not switch my locals that often...

Patrick

**Comment by solomax** [comment]
I'm also using it as follows `new AjaxDateTimePicker("validFrom", "yyyy/MM/dd", "HH:mm:ss")`
Will additionally double-check with 7.2.1

**Comment by sebfz1** [comment]
Hi @Patrick1701 

> Works well, or do I have bugs, without knowing it?

No that's fine! :)

@solomax 

> I'm also using it as follows new AjaxDateTimePicker("validFrom", "yyyy/MM/dd", "HH:mm:ss")

Perfect, no worry


Guys, if you also can double check there is no timezone issue with AjaxDateTimePicker... ;)

**Comment by solomax** [comment]
I'm using LocalDate/LocalDateTime only, no issues here :)
