### ISSUE TITLE
Add jQuery UI Time Spinner

### ISSUE THREAD

**Issue by ephraimrosenfeld** [sebfz1/wicket-jquery-ui#217]
The existing Wicket jQuery-UI spinner [widget](http://www.7thweb.net/wicket-jquery-ui/spinner/DefaultSpinnerPage) works well for simple, discreet numeric values, but it would be nice to have a spinner component for dates as well, such as the one provided in [this example] (https://jqueryui.com/resources/demos/spinner/time.html), similar to the Kendo UI [time picker] (http://www.7thweb.net/wicket-jquery-ui/kendo/datetimepicker/DefaultTimePickerPage) that takes in, either a Java `Locale` instance or a `SimpleDateFormat` string.

Thank you in advance!

**Comment by sebfz1** [comment]
Hi 

This has been implemented. I will probably deploy a snapshot this WE...

Usage is the following:

```java
new TimeSpinner("spinner", myModel, Locale.FRENCH) {

	private static final long serialVersionUID = 1L;

	@Override
	public void onConfigure(JQueryBehavior behavior)
	{
		super.onConfigure(behavior);

		behavior.add(new JavaScriptResourceReference(MyApplication.class, "globalize.culture.fr-FR.js"));
	}
};
```

You can omit the `locale` arg and the `globalize.culture.xx-XX.js` file if you are using the default en-US culture.

Best regards,
Sebastien.

**Comment by sebfz1** [comment]
Forgot to mention: you *have to* include jQuery Globalize by yourself, either:

1/ at application level

```java
public void init()
{
	super.init();

	JQueryLibrarySettings settings = new JQueryLibrarySettings();
	settings.setJQueryGlobalizeReference(JQueryGlobalizeResourceReference.get());

	this.setJavaScriptLibrarySettings(settings);
}
```

2/ at page level
```java
public void renderHead(IHeaderResponse response)
{
	super.renderHead(response);

	response.render(new PriorityHeaderItem(new JQueryGlobalizeHeaderItem()));
}
```
