### ISSUE TITLE
Support dynamic load of Resources in Scheduler

### ISSUE THREAD

**Issue by Patrick1701** [sebfz1/wicket-jquery-ui#218]
Hi Sebastien,
today I worked on our Scheduler again and ran into a problem which is also mentioned in 

https://github.com/sebfz1/wicket-jquery-ui/issues/116#issuecomment-87486753

and

https://github.com/sebfz1/wicket-jquery-ui/issues/116#issuecomment-121269637

Long story in short...

I have a ```DropDownChoice``` and a ```Scheduler``` on a page, and this ```DropDownChoice``` updates the ```Scheduler``` via ```scheduler.refresh(...)``` and the ```Scheduler``` needs to refresh the ResourceLists depending on the ```DropDownChoice``` to be able to show correct/new ResourceGroupings.

(You made a note to yourself about using Kendo Filters to achieve this https://github.com/sebfz1/wicket-jquery-ui/issues/116#issuecomment-87486753)

kind regards
Patrick

**Comment by Patrick1701** [comment]
Good morning,
I played a bit with the scheduler not to use ```Scheduler.refresh()```, but ```target.add(scheduler)``` again, and it seems this works since #182 has been fixed.

So, I made a minor experimental change and used ```Scheduler.set(ResourceList resourceList)``` which clears the ResourceList before the Scheduler re-renders and it seem to work.
I get entire re-build Scheduler grid.

So, maybe this issue is done by just adding a new method ```Scheduler.set(ResourceList resourceList)```.

What do you think?

Patrick

**Comment by sebfz1** [comment]
Hi Patrick,

That's a good news, thanks! I will think about `#set` (or equivalent) and will let you know!

Best regards,
Sebastien.

**Comment by sebfz1** [comment]
Hi Patrick,

Another approach is to have the full ResourceList while instantiating the Sheduler and decide whether to display or not the event using the SchedulerModel's `#visit` method.

https://github.com/sebfz1/wicket-jquery-ui/blob/master/wicket-jquery-ui-samples/src/main/java/com/googlecode/wicket/jquery/ui/samples/pages/kendo/scheduler/SingleResourceSchedulerPage.java#L159

Hope this helps,
Sebastien.

**Comment by Patrick1701** [comment]
Hi,
are you sure this also works on grouped views.

Does the Scheduler finds out, if no event of a resource of a group is displayed at all, there is no need to build a grid-part for this grouping and will it even remove empty grid parts?

I don't want to display empty grids without any events... thats why I'm focused on ```target.add(scheduler)``` instead of ```scheduler.refresh()```, because this rebuilds the grid.

Patrick

**Comment by Patrick1701** [comment]
No, tested, not working... the grid is still there. Its just empty then...

**Comment by sebfz1** [comment]
Sure, if you have a group, it might not work as expected as all resources of this group will be displayed, even if there is no events for the date range.
As you know, resources cannot be dynamic (well, these could be... but not at this stage ;)). So the only way in this case is to reload the scheduler, that's fine. I will try the `#set` method (or maybe giving access to the underlying `ResourceListModel`)...

**Comment by Patrick1701** [comment]
> I will try the ```#set``` method (or maybe giving access to the underlying ResourceListModel)...

Great, thanx!

**Comment by sebfz1** [comment]
Hi Patrick,

So I opted for giving access to the `ResourceListModel`. I initially reserves `ResourceListModel` for internal usage only due to the potentially confusing name (`ResourceListModel` is a `ListModel` of `ResourceList`, i.e. a List of Lists).

Here is a sample usage:
```java
final Scheduler scheduler = new Scheduler("scheduler", newSchedulerModel(), options) {

	private static final long serialVersionUID = 1L;

	@Override
	protected void onConfigure()
	{
		super.onConfigure();

		this.getResourceListModel().clear();
		this.getResourceListModel().add(myFirstResourceList);
		this.getResourceListModel().add(myOtherResourceList);
	}
}
```

Best regards,
Sebastien.

**Comment by Patrick1701** [comment]
Hi Sebastien,
a final feedback here, due to my upgrade today...

Works! :-)

best regards
Patrick

**Comment by sebfz1** [comment]
Cool, thanks for the feedback Patrick! :)
