### ISSUE TITLE
Add kendo-culture initializer and register current culture

### ISSUE THREAD

**Issue by sebfz1** [sebfz1/wicket-jquery-ui#222]

**Comment by Patrick1701** [comment]
Hi Sebastien,
I followed the mails on the userlist.

Do you mean with "register current culture" an feature, which determines needed culture by locale and automatically add the particular matching KendoCultureHeaderItem to the HeaderResponse?

best regards
Patrick

**Comment by sebfz1** [comment]
Hi Patrick,

I meant register the current system default culture. But maybe is it
useless. But would have been to register the current default session locale
but i am not sure it is possible...

Thanks,
Sebastien
