### ISSUE TITLE
Javascript Error in Kendo Scheduler when using isEditEnabled() true

### ISSUE THREAD

**Issue by Patrick1701** [sebfz1/wicket-jquery-ui#224]
Hi Sebastien,

```OnEditAjaxBehavior#getCallbackFunctionBody``` of ```SchedulerBehavior``` accesses
```
statement += "e.sender.start = e.sender.start.getTime();";
statement += "e.sender.end = e.sender.end.getTime();";
```
but ```sender``` is not available in this case. ```event``` seem correct to me.
```
statement += "e.event.start = e.event.start.getTime();";
statement += "e.event.end = e.event.end.getTime();";
```

I remember, we had this issue once, while developing the Scheduler integration.
I changed and tested it. For me it looks good in my use-cases; if you like I can create a pull request.

kind regards
Patrick

**Comment by sebfz1** [comment]
Hi Patrick,

Argh, you are right! I don't know why I wrote "sender" instead of "event"...
Please go ahead with the pull request, I will deploy a fix-release tonight (what version are you using?)

The best would be to have a sample with a custom edit-window...

**Comment by sebfz1** [comment]
Hi Patrick,

I've deployed `6.22.2-SNAPSHOT` & `7.2.1-SNAPSHOT`, can you confirm it's ok before I perform a release?

Thanks in advance,
Sebastien.

**Comment by Patrick1701** [comment]
Good morning,
sorry, for not replying yesterday anymore... I had to leave office due to an "appointment" ;-)

I will have a test and let you know... I'm also investigating another issue, so maybe I will open another one you could release within 6.22.2.

Coming back here next hours...
Patrick

**Comment by Patrick1701** [comment]
> I'm also investigating another issue

Not found, so nothing to do, right now.

> can you confirm it's ok before I perform a release?

Confirmed... please go ahead.

Thanx and best regards
Patrick
