### ISSUE TITLE
read of top/left position in DraggableBehavior does not always return proper values

### ISSUE THREAD

**Issue by Patrick1701** [sebfz1/wicket-jquery-ui#226]
Hi Sebastien,
we found a wicket debug out
```
2016-03-30 10:34:59,078 DEBUG string.StringValue - An error occurred while converting '705.9000244140625' to an integer: Unable to convert '705.9000244140625' to an int value
```
In Wickets point of view its just a debug, because it happens, when ```getQueryParameterValue("left").toInt(-1);``` falls through an the default value should be returned.

But in point of view of ```DraggableBehavior```, this looks like a bug, because it returns -1, but 705 (or rounded 706?) is expected.

kind regards
Patrick

**Comment by sebfz1** [comment]
Hi Patrick,

If you are talking about jquery-ui's `DraggableBehavior` (not kendo-ui one), then you are right it is a bug. I had supposed that returned positions was integers (maybe it was the case before). I'm fixing this...

Best regards,
Sebastien

**Comment by sebfz1** [comment]
Deployed `6.22.3-SNAPSHOT` & `7.2.2-SNAPSHOT`
