### ISSUE TITLE
NullPointerException in kendo.ui.form.datetime.DateTimePicker when timepicker is disabled

### ISSUE THREAD

**Issue by Patrick1701** [sebfz1/wicket-jquery-ui#229]
Hi Sebastien,
I have a NPE when using the ```DateTimePicker``` and the time-picker part is disabled.

On submitting the form the disabled timepicker does not have an input so in
```
	@Override
	public void convertInput()
	{
		Date date = this.datePicker.getConvertedInput();
		Date time = this.timePicker.getConvertedInput();

		this.setConvertedInput(DateUtils.dateOf(date, time));
	}
```
the 
```time = this.timePicker.getConvertedInput()``` is null.

```
Root cause:

java.lang.NullPointerException
     at com.googlecode.wicket.jquery.core.utils.DateUtils.toLocalTime(DateUtils.java:281)
     at com.googlecode.wicket.jquery.core.utils.DateUtils.dateOf(DateUtils.java:203)
     at com.googlecode.wicket.kendo.ui.form.datetime.DateTimePicker.convertInput(DateTimePicker.java:159)
     at org.apache.wicket.markup.html.form.FormComponent.validate(FormComponent.java:1131)
...
```

Possibly other DateTimePicker components in sub-package ```local``` are also affected.

best regards
Patrick

**Comment by Patrick1701** [comment]
It seems to me ```AjaxDateTimePicker``` is save, because ```formatInput(String dateInput, String timeInput)``` checks for ```this.isTimePickerEnabled()```.

But -to be sure- please also have a look...

**Comment by sebfz1** [comment]
Hi Patrick,

Thanks for reporting. Good catch! I thought I handled it, but obviously I missed something...

https://github.com/sebfz1/wicket-jquery-ui/blob/6fcca9a54d1c386f3ce3fd981e3be4d2ed1cb38c/wicket-jquery-ui-core/src/main/java/com/googlecode/wicket/jquery/core/utils/DateUtils.java#L215

I will correct this asap.

Thanks & best regards,
Sebastien

**Comment by sebfz1** [comment]
Deployed `6.22.3-SNAPSHOT` and `7.2.2-SNAPSHOT`
`7.3.0` is planned to be released soon

**Comment by Patrick1701** [comment]
Hi Sebastien,
thanx a lot. Had a short test ```6.22.3-SNAPSHOT```, looks good to me.

Currently I'm working on some date related things, so no hurry for final ```6.22.3```, maybe we find another one.
I will get in contact with you.

best regards
Patrick

**Comment by Patrick1701** [comment]
Hi Sebastien,
from my side I think ```6.22.3``` can be released. I'm currently finishing some work, so a final ```6.22.3``` would be great. Did not found any other issues.

kind regards
Patrick

**Comment by sebfz1** [comment]
Hi Patrick,

I didn't found any other issue...

`wicket-6.23.0` is currently releasing. I will try to test it by tonight and release `wicket-jquery-ui-6.23.0` asap...

Best regards,
Sebastien.
