### ISSUE TITLE
MessageDialog with DialogIcon.LIGHT

### ISSUE THREAD

**Issue by solomax** [sebfz1/wicket-jquery-ui#230]
Hello Sebastien,

It seems like following code:
new MessageDialog("testId", "Test Title", "Test Message", DialogButtons.OK, DialogIcon.LIGHT) 

produces broken dialog, icon is cut, text is not displayed

same time, changing only icon works as expected
new MessageDialog("testId", "Test Title", "Test Message", DialogButtons.OK, DialogIcon.INFO)

**Comment by solomax** [comment]
Thanks for the super fast fix :)

**Comment by sebfz1** [comment]
Hi Maxim,

Yes, fix was easy (it was careless mistake, grrr)

Thanks a lot for reporting! :)
Sebastien.

**Comment by sebfz1** [comment]
Do you need a snapshot on 7?

**Comment by solomax** [comment]
I'll wait for release :)
Not a big issue :)

**Comment by sebfz1** [comment]
All right, should be soon anyway :)
