### ISSUE TITLE
kendo css.map files are missing

### ISSUE THREAD

**Issue by solomax** [sebfz1/wicket-jquery-ui#231]
Hello Sebastien,

I would like to log this errors here:

Failed to parse SourceMap: http://localhost:5080/openmeetings/wicket/resource/com.googlecode.wicket.kendo.ui.theme.Initializer/kendo.default.min.css.map
Failed to parse SourceMap: http://localhost:5080/openmeetings/wicket/resource/com.googlecode.wicket.kendo.ui.theme.Initializer/kendo.common.min.css.map
Failed to parse SourceMap: http://localhost:5080/openmeetings/wicket/resource/com.googlecode.wicket.kendo.ui.theme.Initializer/kendo.default.mobile.min.css.map

I believe this need to be fixed :)

**Comment by sebfz1** [comment]
Hi Maxim,

Thanks a lot for reporting, I didn't realized (or remember?) css also have map files...

**Comment by solomax** [comment]
I do remember we have discussed it in wicket mailing list :)
those dev-console errors are so annoying :(

**Comment by sebfz1** [comment]
Yes, maybe I was focused on `.min.js` (by the way, one was missing, I've added it)

**Comment by sebfz1** [comment]
Hi Maxim,

Something strange happened: according to the git log, files have been added prior to the `7.3.0` release:

c0db1cd [maven-release-plugin] prepare release wicket-jquery-ui-7.3.0
0dcff0a Upgraded to wicket-7.3.0
769e151 Added *.min.js.map & *.min.css.map files; fixes #231 Removed *.js files

But 769e1511090810fd1a01abc4b228099f65ebae91#diff-5afb98096adab3694de3080aa526b02b does not seems to contain `*.min.js/css.map` files! Very (very) strange (not to say bizarre) !

I will release `7.3.1` shortly...

Thanks & best regards,
Sebastien.

**Comment by solomax** [comment]
Thanks a lot!

**Comment by sebfz1** [comment]
Maxim,

`wicket-jquery-ui-7.3.1` will be based on `jquery-ui-1.12.0-rc.2`. Is it ok for you?

Thanks,
Sebastien

**Comment by solomax** [comment]
to be fair I'm not sure :(
area there any API breaks with current version? if not - it's OK with me :)

**Comment by solomax** [comment]
Hello Sebastien,
Main page states 7.3.1 is available, but I'm unable to find it in maven :(
Do you have any ETA when it will be available?

ps sorry pushing you, but I'm preparing release so I need to know if it will be based on 7.3.1 or 7.3.0 ....

**Comment by sebfz1** [comment]
Hi Maxim, 7.3.1 in a couple of hours...

**Comment by sebfz1** [comment]
Maxim,

Please be aware that  `7.3.1` will be based on `jquery-ui-1.12.0` and `kendo-ui-2016.2.714`.
I had to upgrade the (jquery) indicating button and the menu.
So far, everything seems ok but maybe is it better you test `7.3.1` before your release

I'm starting the process right now...

Best regards,
Sebastien.

**Comment by sebfz1** [comment]
Hi Maxim,

`7.3.1` is now released.

Best regards,
Sebastien.

**Comment by solomax** [comment]
Thanks a lot!
will test it right now :)

**Comment by solomax** [comment]
Everything works as expected (after some fixing)
Thanks for the updated version!
