### ISSUE TITLE
Support of jqueryUI 1.12

### ISSUE THREAD

**Issue by Patrick1701** [sebfz1/wicket-jquery-ui#232]
Hi Sebastien,
did you already had a look at jqueryUI 1.12-rc.2?

The reason why I'm asking is, we are waiting for a critical bugfix concerning the radio-choices rendered as buttons:
https://bugs.jqueryui.com/ticket/12554
https://bugs.jqueryui.com/ticket/9990

Do you think an upgrade of your wicket-jquery-ui components would be easy or painful?
Do you think it is possible already upgrading our system without having an upgraded wicket-jquery-ui?

https://jqueryui.com/upgrade-guide/1.12/

As far as I can see, they implemented 1.12 backward-compatible... so, I think, it could be possible, upgrading jqueryUI in our system, without using an already upgraded wicket-jquery-ui.

I'm thinking about this (hacky) way, because -currently- I'm facing a very critical time-line.
I short feedback with your expertise and your opinion would be great.

Thanx a lot!
Best regards
Patrick

**Comment by sebfz1** [comment]
Hi Patrick,

Sorry for the delay, I just wake up...

You can change the resource reference quickly, by chance it will we backward compatible.
https://github.com/sebfz1/wicket-jquery-ui/wiki/%5Bhowto%5D-change-resource-references#customize-jquery-ui-resources

It does not apply for the theme however, but with some chance it also backward compatible.

In the mean time, I will updrade in a dedicated branch, read the migration guide, test a litlle and release a special version later today

Is it ok for you?

**Comment by sebfz1** [comment]
Are you on Wicket jQuery UI 7?

**Comment by sebfz1** [comment]
I've updated js & themes to 1.12-rc2, but the display is very bad (not to say globally broken)

![1](https://cloud.githubusercontent.com/assets/1717144/14761530/2e84b196-0964-11e6-8ad6-b5aaded15331.png)
![2](https://cloud.githubusercontent.com/assets/1717144/14761535/5ae23c54-0964-11e6-8a25-d538650d7401.png)
![3](https://cloud.githubusercontent.com/assets/1717144/14761540/900618f6-0964-11e6-9a91-a69d572d4e05.png)

I will try to figure out why. In the meantime, did you workaround your critical issue?

**Comment by sebfz1** [comment]
I opened an issue to jQueryUI
https://github.com/jquery/download.jqueryui.com/issues/298

**Comment by Patrick1701** [comment]
Thanx a lot for your fast reply!
I get the notifications about issue comments only at work e-mail. Sorry, for not replying again.

> Are you on Wicket jQuery UI 7?

I'm still on 6.x.

> I opened an issue to jQuery UI:

Ok, thank you.

Can I support some how?

Patrick

**Comment by sebfz1** [comment]
Hi Patrick,

I'm afraid that until I get an answer from jQuery UI team and proper theme
builds, I cannot do much more for now...

What are your urgency/ies today?

**Comment by Patrick1701** [comment]
> did you workaround your critical issue?

Unfortunately, I'm not / wasn't able to fix that on my side with a workaround or hacky fix.
It seemed it is a major issue, because the JQueryUI guys decided to fully re-implement the button component. Thats the reason why its in a major release of them.

Due to the major release it becomes critical here. Bugfix releases weren't a problem in the past.

I'm thinking about using another component, but this will change the ui and the ux, so I have to get the ok of my business-devs.

Currently, I try to keep all doors open, to handle this. ;-)

Patrick

**Comment by sebfz1** [comment]
You can use kendo button group?

**Comment by Patrick1701** [comment]
Also, thought about that... but I need a vertical variant.
I have a local implementation of JQueryUI ButtonSets for Radio Choice in a vertical way.

This is the reason, why I'm a bit handcuffed.

**Comment by Patrick1701** [comment]
Hi Sebastien,
ok... its getting a bit stress-free... I found a solution with native radio choices, without breaking the usability... its just looking a bit old-school.

So, if you like, you can keep this issue open for a normal jquery-ui maintenance upgrade, next.

best regards
Patrick

**Comment by sebfz1** [comment]
Hi Patrick,

The issue has been fixed on the jQuery UI side. I will upgrade asap...

Best regards,
Sebastien.

**Comment by sebfz1** [comment]
I've updated master to 1.12.0-rc.2 but there is some side effects.
https://bugs.jqueryui.com/ticket/14983

**Comment by Patrick1701** [comment]
Hi Sebastien,
I've just seen the mail from the mailing list about 8.0.0.
You say... it is working with jquery-ui 1.20.0...

Your jquery-ui ticket about the menu icon has been closed.
Did the upgrade guide work well?

Is everthing is working so far? Can I have a test somewhere on a 6.x branch?

kind regards
Patrick

**Comment by sebfz1** [comment]
On Jul 18, 2016 9:52 AM, "Patrick" <notifications@github.com> wrote:
>
> Hi Sebastien,
> I've just seen the mail from the mailing list about 8.0.0.
> You say... it is working with jquery-ui 1.20.0...
>
> Your jquery-ui ticket about the menu icon has been closed.
Yes, it was part of their migration guide

> Did the upgrade guide work well?
The wicket one? Yes, I don't see anything missing...

>
> Is everthing is working so far?
I believe. Maxim also confirmed it is ok (after some fix, I don't know what
he mean exactly...)

Can I have a test somewhere on a 6.x branch?

Yes, wicket6.x is in sync. I did not deploy a snapshot however. You can
build it locally and have a try. I will try to deploy a snapshot tonight,
and will release 6.24.0 next week-end...

**Comment by Patrick1701** [comment]
As I remember there was a backwardCompatibility flag, which is settable.
Did you use this flag?

**Comment by sebfz1** [comment]
Isn't this flag about jquery backward compatibilty ? I don't see/remember
about a jquery-ui one...

**Comment by Patrick1701** [comment]
https://jqueryui.com/upgrade-guide/1.12/#api-redesigns

Ok, it seems its otherway around... by setting this, you can force much more strict API.
Its backward compatible by default...

**Comment by sebfz1** [comment]
Hi Patrick,

Thanks for the link! I wasn't aware of such flag...
I did already see that several widgets have been deprecated, I will I have to rework these before 1.13....

I've deployed `6.23.1-SNAPSHOT` (I finally found some network :p)

![img_20160718_200929199](https://cloud.githubusercontent.com/assets/1717144/16926997/9ad34aaa-4d2b-11e6-938d-1bf5b2ea5269.jpg)

Best regards,
Sebastien

**Comment by Patrick1701** [comment]
This is already contained in 6.24.x, and can also be closed... am I right?

**Comment by sebfz1** [comment]
Right, thanks!
