### ISSUE TITLE
Scheduler#onNavigate() / is SchedulerViewType the new or previous view?

### ISSUE THREAD

**Issue by Patrick1701** [sebfz1/wicket-jquery-ui#233]
Hi Sebastien,
what is the meaning of SchedulerViewType on `onNavigate(..., SchedulerViewType view)`.

The new view or the previous view?

Currently it seems it is the previous view.

kind regards
Patrick

**Comment by sebfz1** [comment]
Hi Patrick, it actually look like a question! :)

**Comment by sebfz1** [comment]
http://docs.telerik.com/kendo-ui/api/javascript/ui/scheduler#events-navigate

```
e.view String
Name of the view
```

Well... Not sure it answers your question :/
But my assumption was it's the name of the view we are switching on...

**Comment by sebfz1** [comment]
Seems that I did not use that property, but the sender's one. I don't know/remember if there was a reason to this...

```java
CallbackParameter.resolved("view", "e.sender.view().name") };
```

I will probably correct by updating properties with `#getOldView` and `#getNewView` or equivalent...

**Comment by Patrick1701** [comment]
Ok, just a short info why I'm interested in the view.

When replacing the Scheduler via ```target.add(scheduler);``` to force a rebuild of the grid, I loose the information of the current view and the current date-interval.

So, I try to extend my Scheduler subclass to keep its states, and I will add methods like ```changeView(...)``` and ```changeDate(...)``` server-side to be able to set the states back.
(later I would like to contribute to you, when the methods are finally working)

best regards
Patrick

**Comment by sebfz1** [comment]
Isn't `#refresh` enough?

**Comment by Patrick1701** [comment]
No, because of the necessary grid rebuild. If you can feature both (keeping the state and rebuilding the grid, when resource selections changed) then I also would prefer ```refresh()```, but currently its not working.

**Comment by Patrick1701** [comment]
Good Morning,
my last answer wasn't precise enough...

```refresh()``` already rebuilds the grid, when changing a resource (turn on or off for the view) of the current resource list.

But when changing the entire resource list, the rebuild does not work.
e.g. when changing from employee resources to room resources.

To achieve this, I need to replace the scheduler. An of call ```refresh()``` does not work yet.

Patrick

**Comment by Patrick1701** [comment]
Hi Sebastien,

> I will probably correct by updating properties with #getOldView and #getNewView or equivalent...

FYI... I'm working on that... need it next. I will do a push request when ready for reviewing...

best regards
Patrick

**Comment by Patrick1701** [comment]
This issue can be closed, right?

**Comment by sebfz1** [comment]
Right, thanks!
