### ISSUE TITLE
KendoUIBehavior renders KendoUI Javascript References with priority

### ISSUE THREAD

**Issue by Patrick1701** [sebfz1/wicket-jquery-ui#234]
Hi Sebastien,
I think we already had this topic once... but I'm not sure.

Is there a special reason why do you render them with priority?

In some circumstances it happens, the KendoUI scripts trying to execute code before JQuerys references are loaded by the browser.
Currently, I have this problem using the the ```KendoDataSource```.

![screen](https://cloud.githubusercontent.com/assets/3428658/15850365/d0673780-2c97-11e6-8a3e-13696bf2355e.png)

kind regards
Patrick

**Comment by sebfz1** [comment]
Hi Patrick,

Yes we had a similar discussion in the past. What's strange is that jquery is loaded after kendo ui (it is a jquery plugin, with a dependency to jquery). Are you using the lastest version (just to be sure) ?

**Comment by sebfz1** [comment]
Ah, you are using your own kendo-all resource reference :) Make it dependent from jquery and it should be ok...

**Comment by Patrick1701** [comment]
Works... using ```JQueryPluginResourceReference``` now.

Thanx :)
Patrick

**Comment by sebfz1** [comment]
Perfect! I just forgot to tell you to look at the wiki :)
