### ISSUE TITLE
No finale qualifier for onError(...) of AbstractWizard

### ISSUE THREAD

**Issue by Patrick1701** [sebfz1/wicket-jquery-ui#235]
Hi Sebastien,
is it possible to remove the `final` qualifier of `AbstractWizard#onError(AjaxRequestTarget target)`?

I would like to extend and add the form to the request target, as well.

Or can this lead into problems concerning the form handling of the wizard?

kind regards
Patrick

**Comment by sebfz1** [comment]
Hi Patrick, I think it's final for a reason, i'll try to have a look over
the we...
