### ISSUE TITLE
Extendable TabbedPanel with user supplied markup

### ISSUE THREAD

**Issue by hlemcke** [sebfz1/wicket-jquery-ui#236]
Currently TabbedPanel cannot be extended to supply your own markup. It requires a method like "newTabContainer( int index )" as in the standard Wicket TabbedPanel which can be overwritten. This would allow to extend TabbedPanel and supply your own markup.

I want to add an icon (taken from the panel on the tab), a link which sends the form on the tab for validation and another link which only shows up when the validation ends with some violations to show up a dialog box with the validation error messages.

**Comment by sebfz1** [comment]
I've added `#newTabContainer` which should answer your need. 

This is a method that should be overridden with care (e.g. `AttributeModifier.replace("href", "#" + tabId)` is very important!). I *may* change it in the future by supplying a default Panel (instead of an internal fragment) so it is less error prone...

Usage is the following:

**java (MyTabbedPanel)**
```java
@Override
protected WebMarkupContainer newTabContainer(String id, String tabId, ITab tab, int index)
{
	Panel panel = new MyTabTitlePanel(id); // which have empty impl in that case

	Label label = new Label("link", tab.getTitle());
	label.add(AttributeModifier.replace("href", "#" + tabId)); // important!
	panel.add(label);

	AbstractLink link = this.newRemoveLink("remove", index);
	panel.add(link);

	return panel;
}

private AbstractLink newRemoveLink(String id, final int index)
{
	return new AjaxLink<Integer>(id, Model.of(index)) {

		private static final long serialVersionUID = 1L;

		@Override
		public void onClick(AjaxRequestTarget target)
		{
			MyTabbedPanel.this.getModelObject().remove(index);
			target.add(MyTabbedPanel.this.setActiveTab(0));
		}
	};
}
```

**html (MyTabTitlePanel)**
```html
<wicket:panel>
	<a wicket:id="link">[title]</a>
	<a wicket:id="remove" class='ui-icon ui-icon-close' role='presentation' title="Remove"></a>
</wicket:panel>
```
