### ISSUE TITLE
Selectable, selection restricted to only one element?

### ISSUE THREAD

**Issue by TheAntimist** [sebfz1/wicket-jquery-ui#238]
I have been looking for a way to achieve this behaviour while using a Selectable Component, to select restrict the selection to only one element in the list at a time. Any help is appreciated.

**Comment by TheAntimist** [comment]
Closing this issue, since the problem is on the JQuery side of things, supposedly the Selectable is meant to be only used with Multiple Selection. The bug issue filed is here: https://bugs.jqueryui.com/ticket/7937

**Comment by sebfz1** [comment]
I had a look yesterday and didn't find any option for this purpose...

**Comment by TheAntimist** [comment]
Thanks for checking. Oh, well, the only solutions I found would be to append JS, as mentioned [here](https://stackoverflow.com/questions/5855905/jquery-ui-selectable-how-to-select-one-item-only/) and [from the topic on the JQuery forums](https://forum.jquery.com/topic/selectable-single-select), in case, somebody really wants to use it. In my case, I'll probably look into something else.
