### ISSUE TITLE
Alternative to Kendo Combobox

### ISSUE THREAD

**Issue by reckart** [sebfz1/wicket-jquery-ui#243]
Is there a JQuery-UI alternative for the Kendo Combobox? The AutoCompleteTextField looks useful, but lacks the styling with the arrow that triggers the dropdown box. The [JQuery UI example](https://jqueryui.com/autocomplete/#combobox) of a combobox that looks similar to the Kendo Combobox seems to be just that: an example - it is not in any way integrated and/or supplied via the JQuery UI integration in Wicket, right?

**Comment by sebfz1** [comment]
Hi Richard, afaik there is no combobox widget supplied out-of-the box in
JQuery-UI. I had a look to the example some time ago but I was not really
convinced... Please let this issue open, I will have a look again. (Cannot
promess it will be "soon", however...)

**Comment by reckart** [comment]
I just noticed that Kendo UI Core is now licensed under Apache License 2.0 - that also kind of addresses the problem :)

**Comment by sebfz1** [comment]
If using Kendo UI is an option for you, I think you will enjoy it :)

**Comment by reckart** [comment]
We are actually already using it but I wanted to switch away from it due to its licensing. But since Kendo UI Core now apparently is properly licensed under the ASL 2.0, that's a non-issue :) We might even start using it more extensively.

**Comment by reckart** [comment]
Although there is still a problem with the Kendo Combobox. It looks like it loads its data always completely when the box is rendered. We have some cases where thousands of options are possible. So I need to check if the Kendo Combobox also allows loading the dropdown contents on-demand via AJAX...

**Comment by sebfz1** [comment]
The content can be more static, ie generate the select/options with a
listview and apply the combobox behavior on the parent container (iirc)...
(new KendoUIBehavior(JQueryBehavior.getSelector(myContainer),
ComboboxBehavior.METHOD). Something like that...

**Comment by reckart** [comment]
The options are already loaded "statically". I.e. when the Combobox is rendered, all the data is included as a JSON object. I need it to be more dynamic. I.e. when the users starts writing or when the user opens the dropdown box, only then should the choices be loaded from the backend via AJAX. The AutoCompleteTextField works that way by default. Presently, we have the problem that for Kendo Comboboxes with many choices, easily several MB of data are transferred to the browser each time the Combobox rerendered.

**Comment by sebfz1** [comment]
Hi Richard,

Did the Kendo's AutoCompleteTextField answered your need?

Thanks,
Sebastien

**Comment by reckart** [comment]
I'm afraid I haven't had the chance to work on it lately.

**Comment by reckart** [comment]
Finally, I had a look at the Kendo AutoComplete. I'm now actually planning to use it for cases where there are a lot of choices and server-side filtering is required.

Unfortunately, the suggestion pane does not open automatically when the users clicks into the AutoComplete field, neither if it already contains text nor if it is empty. However, this seems to be (unfortunately) intended in this way by Telerik.

Also, AutoComplete and ComboBox both to not refocus automatically. I had to hack Wicket to ensure they automatically receive their focus back after an AJAX action (https://github.com/webanno/webanno/blob/4c2fd35eab97d30a949847c7e2c7dfdc4ca51042/webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/kendo/wicket-jquery-focus-patch.js#L90).

I also had a look at Select2, but it also has issues. One thing which is pretty cool about Select2 though is that is supports infinite scrolling with server-side paging.

I think this one can be closed now. Thanks!
