### ISSUE TITLE
Error when using KendoDatasource if markupId contains a dash

### ISSUE THREAD

**Issue by reckart** [sebfz1/wicket-jquery-ui#244]
The KendoDatasource in version 7.4.0 is created with code like 

```
window.<datasourceName> = new KendoDatasource(...)
```

If the datasource name contains a dash, this will fail with a message like "left side of an assignment must be a reference". With version 6.20.x, this problem did not exist.

**Comment by sebfz1** [comment]
Hi Richard

Right, it should not contain a dash. I should double check if it is escaped
(replaced with _) in the ctor...

I don't see any reason why it "works" previously...

I will try to have a look tonight, thanks for reporting!

Sebastien

**Comment by reckart** [comment]
With older versions, the datasource was not a separate JS object, but it was directly part of the Combobox command:

```
jQuery('#featureEditorHead-0').kendoComboBox({ "template": jQuery('#kendo-template-1450408254').html(), "dataTextField": "text", "dataValueField": "value", "dataSource": [{ "text": "$(", "value": "$(", "name": "$(", "description": "sonstige Satzzeichen; <........SNIP.........>
```

That is why it worked before. There are probably many illegal characters. I was thinking that instead of sanitizing (and thus introducing a difference between the markupId and the datasourceId which might cause more confusion) throwing an exception in Java about an illegal markupId might be more sensible. At least in Java it would be easier then to locate the problem that using a JS debugger in the browser.  Also, if somebody needs to recreate the datasource ID for use in custom JS code, then `"datasource_"+getMarkupId()` is easier than `"datasource_"+sanitize(getMarkupId())`.

**Comment by sebfz1** [comment]
Hi Richard,

Please see if this update answers your concern: https://github.com/sebfz1/wicket-jquery-ui/issues/245#issuecomment-252486823

Thanks in advance,
Sebastien.
