### ISSUE TITLE
Update KendoUI to 2016.3.1028

### ISSUE THREAD

**Issue by Patrick1701** [sebfz1/wicket-jquery-ui#247]
Hi Sebastien,
please update KendoUI to this release 2016.3.1028 next.

Do you think it is a problem, upgrading our own pro version to 2016.3.1028 right now, without waiting for you?

best regards
Patrick

**Comment by sebfz1** [comment]
Hi Patrick,

I will do it tonight and deploy a snapshot. I do however not recommend you to mix versions (if you are using a default theme artifact, you might experience some issues)

I plan to release versions over the next WE...
