### ISSUE TITLE
MessageFormDialog overlays/hides choices of AutoCompleteTextfield

### ISSUE THREAD

**Issue by Patrick1701** [sebfz1/wicket-jquery-ui#25]
Hi Sebastien,
when I use an ACTF in a MessageFormDialog, the choices are rendered behind the MessageDialog.

I think, there is something wrong with the z-index.

Unfortunately, I cannot provide a screenshot, because any event (keyboard/mouse etc) let the choices disappear immediately.

So, just move the MessageDialog using the mouse, than you can see the rendered choices are behind it.

kind regards
Patrick

**Comment by sebfz1** [comment]
A colleague of mine also recently add this issue and solved it with:

```css
.ui-dialog {
	overflow: initial !important;
} 
```
