### ISSUE TITLE
Javascript error 'effectMethod is undefined' when using JQueryEffectContainer

### ISSUE THREAD

**Issue by Patrick1701** [sebfz1/wicket-jquery-ui#251]
Hi Sebastien,
just found a bug in the JQueryEffectContainer.

![grafik](https://cloud.githubusercontent.com/assets/3428658/20486808/723f582a-b001-11e6-9661-d05de22e7742.png)

kind regards
Patrick

**Comment by sebfz1** [comment]
Oops, seems to be a javascript error in the page rendering...
Thanks for reporting, Patrick!

**Comment by Patrick1701** [comment]
Maybe for 6.25.1? :-D

**Comment by sebfz1** [comment]
humm, seems to be wicket related or a wrong usage which was tolerated before. I will try to investigate later...

```
WARN  - AjaxButton                 - unexpected invocation of #onSubmit() on [AjaxButton [Component id = button]]
```

**Comment by sebfz1** [comment]
The issue was actually due to an empty effect at the  ̀QueryEffectContainer ̀ initialization, which was attempt to be played. Somehow, it used to break something in the javascript, leading to weird behaviors...

**Comment by Patrick1701** [comment]
Ok, sounds a bit like, I also have to do some changes concerning effects, right?
Or should it work again out-of-the-box?
(also needed for 6.25.1)

**Comment by sebfz1** [comment]
It should work back as normal, and the commit will be part of `6.25.1`
You can checkout `wicket6.x` branch and test the sample if you would like to double check...
