### ISSUE TITLE
JQueryTemplateBehavior / JQueryPluginResourceReference points to wrong jquery.tmpl.js location

### ISSUE THREAD

**Issue by Patrick1701** [sebfz1/wicket-jquery-ui#252]
Hi Sebastien,
it seems your ```jquery.tmpl.min.js``` has moved.

Your

```
new JQueryPluginResourceReference(JQueryTemplateBehavior.class, "jquery.tmpl.min.js");
```
of ```JQueryTemplateBehavior``` is wrong.

Correct is
```
new JQueryPluginResourceReference(JQueryTemplate.class, "jquery.tmpl.min.js");
```

kind regards
Patrick

**Comment by sebfz1** [comment]
Damned! Well done Patrick.

This has been caused by https://github.com/sebfz1/wicket-jquery-ui/commit/8624e25327d29c6b0d0acb56a46fb330255f7e38 (jQueryTemplateBehavior: moved from 'jquery-core' to 'jquery-ui')
I will correct asap (today), sorry for the inconvenience :/

Best regards,
Sebastien.

**Comment by Patrick1701** [comment]
No problem... but I will need a 6.25.1 :-)

**Comment by sebfz1** [comment]
> No problem... but I will need a 6.25.1 :-)

Fine, you will have it on monday morning! :)

**Comment by sebfz1** [comment]
Hi Patrick

`wicket-jquery-ui-6.25.1` has been released, enjoy!

I was not able to reply to Hans & you by mail:
`Remote host said: 550 No RDNS entry for *ip adress*`

Best regards,
Sebastien.
