### ISSUE TITLE
UI looks odd

### ISSUE THREAD

**Issue by bernhardwaidacher** [sebfz1/wicket-jquery-ui#258]
I have tried including this awesome project to my project. I have downloaded "wicket-jquery-ui-7.6.0.jar" and "wicket-jquery-ui-core-7.6.0.jar" and added it to my project and I don't get any warnings. 

But the problem is it looks this: [http://imgur.com/a/Reii8](http://imgur.com/a/Reii8)

Do I have to include some other jars? I'm using bootstrap

**Comment by sebfz1** [comment]
> Do I have to include some other jars? 

Yes, the theme jar
