### ISSUE TITLE
Change KendoUI Scheduler ajax requests to POST

### ISSUE THREAD

**Issue by Patrick1701** [sebfz1/wicket-jquery-ui#259]
Hi Sebastien,
do you think it would be possible to change the schedulers ajax requests to POST request?

The data parameter can exceed normal url length due to stringified event json.
And I will also need it for security reasons.

best regards
Patrick

**Comment by sebfz1** [comment]
Hi Patrick,

I will look at this asap...

Thanks and best regards,
Sébastien

**Comment by sebfz1** [comment]
Hi Patrick,
I've updated create, update, delete and edit commands to use POST requests.
Please try out `6.27.0-SNAPSHOT` to ensure everything works. As soon as you confirm it's ok I will deploy a patch release (`6.27.1`).

**Comment by Patrick1701** [comment]
Hi Sebastien,
POST tested and works for me.

No need for a patch release. Can go through standard release cycle.
I've also found an additional solution for my privacy-issue I told you by mail.

Patrick
