### ISSUE TITLE
examples not working

### ISSUE THREAD

**Issue by blopatka** [sebfz1/wicket-jquery-ui#262]
I found that some of the examples (eg. from jquery-ui slider) do not work (they throw ClassCastException) ...
http://www.7thweb.net/wicket-jquery-ui/slider/InputSliderPage
http://www.7thweb.net/wicket-jquery-ui/slider/OptionSliderPage
and so on...

**Comment by sebfz1** [comment]
I think it will be my day today.... :-/
Thank you very much for reporting!

**Comment by sebfz1** [comment]
Java8 problem with generic & interface overload (already opened an issue to Oracle without success [1])
`public <W extends AbstractSlider<T>> W setMax(Integer max)`

[1] http://bugs.java.com/bugdatabase/view_bug.do?bug_id=8151584

**Comment by sebfz1** [comment]
Reloaded!

**Comment by blopatka** [comment]
Thanks. It works now.
I checked the source code of samples to make my code work, but now working examples gave me some nice idea ;-)
