### ISSUE TITLE
AjaxSlider constructor with input has Model instead of IModel

### ISSUE THREAD

**Issue by blopatka** [sebfz1/wicket-jquery-ui#264]
When using `AjaxSlider` connected with input one have to use `Model `instead of `IModel `implementations because strange (for me) type change form `IModel `to `Model`.
Where `Slider `has `IModel `in constructor, `AjaxSlider `has `Model` - and it complies only to one from three constructors.
As for me - it's a bug that prevents from using every implementations of `IModel `and forces me to write new one that is derived from `Model`.

**Comment by sebfz1** [comment]
Yes, looks like a mistake. I try to handle this asap :)
