### ISSUE TITLE
Menu is not working with Jquery3

### ISSUE THREAD

**Issue by solomax** [sebfz1/wicket-jquery-ui#266]
Steps:

1. get sources for wicket-jquery-ui-samples
2. Edit SampleApplication.java add following line to `init()' method
```
getJavaScriptLibrarySettings().setJQueryReference(JQueryResourceReference.getV3());
```

3. compile and run
```
mvn clean jetty:run
```
4. open browser console
5. navigate to http://localhost:8080/wicket-jquery-ui/menu/DefaultMenuPage
Result: Menu clicks are broken, following error in the console
```
Uncaught TypeError: Cannot read property 'id' of undefined
```

**Comment by solomax** [comment]
forgot to mention: branch `wicket8.x`

**Comment by solomax** [comment]
@sebfz1 can you please look at it before M6?

**Comment by sebfz1** [comment]
yes, will try tonight!

**Comment by martin-g** [comment]
Better try with jquery-migrate.js and see what kind of warnings it will produce. Fix them and try again without it.

**Comment by sebfz1** [comment]
Thanks a lot, Martin! I will try that!

**Comment by solomax** [comment]
Just have tested,
Everything seems to work as expected
Thanks a lot for the quick fix!
