### ISSUE TITLE
Ability to include custom javascript in AjaxSlider change event

### ISSUE THREAD

**Issue by aioobe** [sebfz1/wicket-jquery-ui#269]
I need to make a loading indicator visible as soon as the value of an `AjaxSlider` changes (client side). I can do this by overriding `onConfigure` and setting a suitable function with `behavior.setOption("change", ...)`. The problem is that the `"change"` behavior is already used by the framework (in `AjaxSliderBehavior.onConfigure`), and by setting it to my own javascript function, I break stuff.

Right now I have an ugly hack where I, in the `AjaxSlider.onConfigure`, extract the current `"change"` function and inject my own statements right before the closing `}` bracket.

It would be great if there was a better way of achieving this.

**Comment by Patrick1701** [comment]
Hi, I've just read your ticket...

In such cases, sometimes I do it using this way:

Implement your own MyAjaxSlider extends AjaxSlider.
and override the new newWidgetBehavior which internally returns an own sub-class of OnChangeAjaxBehavior (<-MyOnChangeAjaxBehavior)
```
	@Override
	public JQueryBehavior newWidgetBehavior(String selector)
	{
		return new AjaxSliderBehavior(selector, this.options) {

			private static final long serialVersionUID = 1L;

			@Override
			public void onConfigure(Component component)
			{
				super.onConfigure(component);

				AjaxSlider.this.onConfigure(this); // important, should call Slider#onConfigure(JQueryBehavior)
			}

			@Override
			public void onAjax(AjaxRequestTarget target, JQueryEvent event)
			{
				AjaxSlider.this.onAjax(target, event);
			}

			@Override
			protected JQueryAjaxPostBehavior newOnChangeAjaxBehavior(IJQueryAjaxAware source)
			{
				return new MyOnChangeAjaxBehavior(source, AjaxSlider.this.input);
			}
		};
	}
```

	MyOnChangeAjaxBehavior overrides
```
	@Override
	protected void updateAjaxAttributes(AjaxRequestAttributes attributes) {
		super.updateAjaxAttributes(attributes);
		attributes.getAjaxCallListeners().add(AjaxCallListener.getBeforeSendHandler("console.log('activate your indicator by js')"));
	}
```

I'm not sure, if this is the best way... , but using this you dont end-up with javascript string manipulations.
@sebfz1 What you you think?

See also IAjaxCallListeners for more information.

kind regards
Patrick

**Comment by sebfz1** [comment]
Hi, I will look at this today...

**Comment by sebfz1** [comment]
@Patrick1701's solution is accurate, I don't have a better one to suggest right know! :)

**Comment by martin-g** [comment]
May I suggest a small improvement: 
All Ajax** components in Wicket itself provide hooks to override `#updateAjaxAttributes()` and `#getStatelessHint()` to make Ajax related configuration easier for the end user. If even more customization is needed then there is also factory method for creating the Ajax behavior too (as in AjaxSlider).
See https://github.com/apache/wicket/blob/63aa52b04df11e87ae20cda744465c4d77dde05b/wicket-core/src/main/java/org/apache/wicket/ajax/markup/html/AjaxLink.java#L88-L99 and https://github.com/apache/wicket/blob/63aa52b04df11e87ae20cda744465c4d77dde05b/wicket-core/src/main/java/org/apache/wicket/ajax/markup/html/AjaxLink.java#L76 for example.

**Comment by aioobe** [comment]
@Patrick1701, @sebfz1 thank you both. I tried your solution yesterday and it works very well indeed.
