### ISSUE TITLE
Kendo-combo-box took so much time to load when combo box is in grid

### ISSUE THREAD

**Issue by kottakotaashokkumar** [sebfz1/wicket-jquery-ui#271]
Hi,

I have a grid in which there are 3 kendo combo boxes. The grid has 50 rows so that I have 150 combo box's total. It is taking too much time to load all the combo boxes approximately 30 seconds. I have used plain select box instead of kendo-combo-box, then there is significant difference in loading time it took only 6 seconds to load all the combo boxes.

Can anyone please suggest why kendo-combo-box took so much time to load.

Here is code snippet I have used for kendo-combo-box.
`<tr ng-repeat="employeedetail in vm.employeeDetails"><td><select kendo-combo-box name="employeeTypeCombo" ng-model="employeedetail.employeeType" k-data-text-field="'name'"k-data-value-field="'id'"k-data-source="vm.employeeTypes"k-filter="'contains'"k-auto-bind="true"k-placeholder="'-- Select --'"k-option-label="'-- Select --'"></select></td></tr>`

I have loaded vm.employeeTypes only once in service. Same values are used for all the 50 rows for employee type combo. Like this I have another 2 combos.

Thanks in advance,
Ashok.K

**Comment by sebfz1** [comment]
Hi,

Just for clarification: I saw `ng-repeat` in your code snippet, which let me think you are using Angular. Is this issue related to "Wicket Kendo UI" ?

Thanks & bet regards,
Sebastien
