### ISSUE TITLE
Request for feature - Kendo grid/datatable column reorder event trapping

### ISSUE THREAD

**Issue by RichLiv** [sebfz1/wicket-jquery-ui#272]
I would very much like to be able to 

1) get an event when a column is reordered
2) be able to retrieve the latest set of columns and their current ordering

I can then persist this and reapply it the next time a user opens a page. Could I also ask if it is possible at the same time to retrieve the set of columns the user has selected for display from that neat dropdown at the top right of the grid? It would be awesome to be able to save that info at the same time, as it would give users quite a bit of power to customise their view (and if it is generic then it is write-once, in theory)

Not a huge priority but if you had time, start of August would be great as I can work on it over the summer and reengineer my webapp to Wicket 8 at the same time, which is also needed in this case (currently on Wicket 6). If not, then just let me know if/when and I will schedule some time to integrate it if/when you do it.

Thanks! I realize this is a spare-time activity and I'm in awe, honestly.

Regards
Richard L

**Comment by sebfz1** [comment]
Hi Richard,

I've added `DataTable#onColumnReorder` so you can play with it.
Usage is the following:

```java
Options options = new Options();
options.set("reorderable", true);

DataTable<Product> table = new DataTable<Product>("datatable", newColumnList(), newDataProvider(), 25, options) {
	@Override
	public void onColumnReorder(AjaxRequestTarget target, int oldIndex, int newIndex, JSONObject column)
	{
		// column.optString("field") // get the column's fields
	}
};
```

It is however not possible to retrieve the (re-)ordered columns array, you may maintain it by yourself...
Hope this helps anyway. If you have any other concerns regarding this feel free to reopen this issue.

Best regards,
Sebastien.

**Comment by RichLiv** [comment]
Many thanks, Sebastien, I will take a look at this shortly Sounds like it
will do enough of what I need. Don't know where you find the time to do
this stuff, really. I have enough trouble organising the rest of my working
life without open source!

Best wishes

Richard

Richard Livingstone

m +44 (0) 7711 590497
e
*richard@bananasoft.net <richard@bananasoft.net>*
*"Non ti curar di loro, ma guarda e passa"*

*This document, together with any attachments, is for the exclusive and
confidential use of the recipient addressee. Any other distribution, use or
reproduction without prior consent is unauthorised and strictly prohibited.
If you have received this message in error please notify the sender by
email immediately.*

**Comment by sebfz1** [comment]
You're very welcome, Richard! Right, it's sometime hard to find the time :)
