### ISSUE TITLE
Uncaught TypeError: jQuery(...).autocomplete is not a function at HTMLDocument

### ISSUE THREAD

**Issue by alsant0z** [sebfz1/wicket-jquery-ui#276]
Hi,

I have added the "wicket-jquery-ui" dependency to my pom file. I'm using the AutoCompleteTextField. However, when I run my wicket application, it shows an error and the page does not load.

Uncaught TypeError: jQuery(...).autocomplete is not a function
    at HTMLDocument.<anonymous> (main?1:48)
    at fire (jquery-2.2.4-ver-1502805691797.js:3187)
    at Object.fireWith [as resolveWith] (jquery-2.2.4-ver-1502805691797.js:3317)
    at Function.ready (jquery-2.2.4-ver-1502805691797.js:3536)
    at HTMLDocument.completed (jquery-2.2.4-ver-1502805691797.js:3552)

I'm using the M7 version of wicket and wicket-jquery-ui.

		<dependency>
		    <groupId>com.googlecode.wicket-jquery-ui</groupId>
		    <artifactId>wicket-jquery-ui</artifactId>
		    <version>8.0.0-M7</version>
		</dependency>

Thanks in advance.
Regards,
Alexandre.

**Comment by sebfz1** [comment]
Hi,

It's strange. Please create a quickstart so I can have a look.
Btw, do not forget to add the theme dependency...

Best regards,
Sébastien

**Comment by alsant0z** [comment]
Hi Sébastien,

After testing the code in a quickstart, I figure out that was conflict with the template I was using.
The autocomplete works as expected when I created the quickstart.

Thanks.
Best Regards,
Alexandre.
