### ISSUE TITLE
Disabling and undisabling tabs in a JQuery TabbedPanel

### ISSUE THREAD

**Issue by zenith77** [sebfz1/wicket-jquery-ui#279]
Pretty much as it says on the description.

I've tried using the Options object to set "disabled" but nothing works, oddly. I'd also like to use Javascript to un-disabled them, too. Hopefully that should be easy to work out, once I work out how to disable tabs, first!

I am looking to disable multiple tabs in the first instance.

**Comment by sebfz1** [comment]
The `disabled` option works for me (to disable in the first instance):

```
new TabbedPanel("tabs", model, new Options("disabled", "[1, 2]"))
```

I've added `enable` and `disable` ajax methods:
```
tabPanel.enable(target);     // enable all tabs
tabPanel.enable(1, target);  // enable one tab
tabPanel.disable(target);    // disable all tabs
tabPanel.disable(1, target); // disable one tab
```

**Comment by sebfz1** [comment]
Snapshots are on their ways:
- `6.29.0-SNAPSHOT`
- `7.9.1-SNAPSHOT`
- `8.0.0-SNAPSHOT`

**Comment by zenith77** [comment]
Amazing! Thanks dude, once again! :D
