### ISSUE TITLE
which html component that jquery.ui.samples.kendoui.datatable uses

### ISSUE THREAD

**Issue by guilherme-oliveria** [sebfz1/wicket-jquery-ui#298]
I need to know to make more more changes in the component, and I use to his infinite listing.

http://www.7thweb.net/wicket-jquery-ui/kendo/datatable/InfiniteDataTablePage?4

**Comment by sebfz1** [comment]
Hi, not sure to understand the question...

**Comment by guilherme-oliveria** [comment]
does the library use the default HTML component of the wicket table?
photo.
[http://uploaddeimagens.com.br/imagens/eclipse-png-4983f13b-a70f-402e-857f-1bbf3fdc7368](url)

**Comment by sebfz1** [comment]
No, it is based on a common `WebComponent` (java side) and on a `div` element (html side).
But the `IDataProvider` is the wicket one.

**Comment by guilherme-oliveria** [comment]
just with the `<div>`, mount a `<table>`?, and thank you, I'm going from one more studied in the structure.


This is my question that I wanted to solve with your API.
https://github.com/apache/wicket/pull/289

**Comment by martin-g** [comment]
@guilherme-oliveria https://github.com/apache/wicket/pull/289 is not a question but a Pull Request. Please close it!

**Comment by sebfz1** [comment]
> just with the `<div>`, mount a `<table>`?

Right. Just check out the samples in the demo site.

**Comment by guilherme-oliveria** [comment]
thanks sebfz1, and martin-g helps me instead of criticizing ..

**Comment by martin-g** [comment]
@guilherme-oliveria Sure, we will help you once you close the meaningless pull request!
