### ISSUE TITLE
Is possible to have diffrent value and content in MultiSelect <option>

### ISSUE THREAD

**Issue by VaclavC** [sebfz1/wicket-jquery-ui#299]
Hello,

   I'am using AjaxMultiSelect and currently I'am getting something like this in HTML:

```
<select ...>
  <option value="Item 1 (10)">Item 1 (10)</option>
  <option value="Item 2 (211)">Item 2 (211)</option>
  ...
</select>
```

  and I want it like this:

```
<select ...>
  <option value="Item 1">Item 1 (10)</option>
  <option value="Item 2">Item 2 (211)</option>
  ...
</option>
```

Is this possible?

**Comment by sebfz1** [comment]
Hi , you may have a look at the demo that use beans..

**Comment by VaclavC** [comment]
I'am sorry, but I'am unable to find that demo. Looking [here](http://www.7thweb.net/wicket-jquery-ui/kendo/multiselect/AjaxMultiSelectPage) but all three demos there are using multiselect with String and not Genre class.

**Comment by sebfz1** [comment]
I will have a look this week-end...

**Comment by VaclavC** [comment]
Thank you very much.

**Comment by sebfz1** [comment]
I added a sample using a custom renderer:
http://www.7thweb.net/wicket-jquery-ui/kendo/multiselect/RendererMultiSelectPage
