### ISSUE TITLE
DropDown column datatable

### ISSUE THREAD

**Issue by mauromar09** [sebfz1/wicket-jquery-ui#301]
i use inline edit and works fine, but i doesn't find a column component inline editable for dropdownchoice or can you help me with a example.

**Comment by sebfz1** [comment]
I'm not sure to spot your problem, can you detail? You want an editable
dropdown? (a combobox...)

**Comment by mauromar09** [comment]
I’m Using Kendo datatable inline edition, I need in editable row use a dropdown combo selectable with choises! I need a Example or any ideas!

**Comment by sebfz1** [comment]
Hi, sorry for the very late reply. Did you had a look at `DropDownListEditor`?

**Comment by mauromar09** [comment]
Yes I try, but isn’t a Icolumn, pelase can you give me a example how yo use
in a column?

**Comment by sebfz1** [comment]
It's the editor to be used by the column in edit mode, you just have to specify it like:
```
new PropertyColumn("myDD", "dd", 150) {

	@Override
	public IKendoEditor getEditor()
	{
		return new DropDownListEditor(new String []{"myvalue-1", "myvalue-2"});
	}
}
```
