### ISSUE TITLE
Kendo Window creates new instances in DOM which interfere with form submission in Window

### ISSUE THREAD

**Issue by mdbergmann** [sebfz1/wicket-jquery-ui#307]
Hi.

I have the following problem.
We have a Kendo `Window` which we use as confirmation window with form and checkbox.
After the first successful submit (checkbox verification OK) of the window form any new spawned window submits ‚value=on‘ even though the checkbox is not ‚checked‘.

The window is part of an inner container that is part of an outer container.
The outer container creates new inner containers depending on a navigation.
So basically a new window is created each time for the same WicketId.

What appears to happen is that whenever an inner container is created that contains a window, a new window is added in the DOM, under body.
Any previous window is not removed.

I’m assuming (couldn’t really verify this yet) that after a successful submit (checkbox checked) some listeners are not completely cleaned up and a new window uses some old data, or the OK button of the new Window actually triggers a listener of some old window which contained the checked checkbox, hence the ‚value=on‘ is transmitted.

After a browser ‚refresh‘ this behavior is gone and a new window works properly, once.

Attached is a quickstart project.
Just unpack and run `./gradlew run`.

The issue can be replicated as follows:
when the page loads, click "New Window".
In the window make sure the form validation fails by just clicking OK.
Then check the checkbox and click OK again. The window closes.
Then click "New Content".
Click again "New Window" and try the same, while the checkbox is unchecked you can successfully click OK and the form is validated.

Having said all this, I'm not sure whether this is a user issue, like creating a wrong hierarchy of components or doing something else stupid.
But it seems OK for me.

Also I'm not sure if this issue applies to the standard Wicket ModalWindow as well.

Our fix was to add append `";$('.k-window').remove();")` when the window.close() was called to remove it from the DOM.
But the way we do this is quite a hack.

[wicket-window-quickstart.zip](https://github.com/sebfz1/wicket-jquery-ui/files/3206581/wicket-window-quickstart.zip)

**Comment by sebfz1** [comment]
Hi Manfred,

Window are not designed to be removed from DOM on close. There are designed to be created, then opened and closed (and repeatedly). That means that the same component will/should be reused.

So you have 2 options:
1/ You may create a global window that you can reuse, eventually by updating its model
2/ If you prefer the strategy of creating and destroying then you can use this code instead of your js code

```java
@Override
public void onClose(IPartialPageRequestHandler handler)
{
	this.getBehaviors(WindowBehavior.class).stream().findFirst().ifPresent(b -> b.destroy(handler));
}
``` 

If you want to keep your js code, better use `destroy` as it also detaches all event handlers and removes jQuery.data attributes (avoid memory leaks)

**Comment by mdbergmann** [comment]
Thanks for your comment.
I guess we can close the issue.

Let me compare the window design to other desktop UI frameworks.
I can see a need 'global' window uses.
But there is also a need for local window/requester definitions which are restricted to individual components.
So I think there should be a distinction related to how the user uses windows towards if they have to be removed from the DOM or not.
