### ISSUE TITLE
8.6.0 version released on GitHub but not on Maven Central

### ISSUE THREAD

**Issue by reckart** [sebfz1/wicket-jquery-ui#310]
I can see the 8.6.0 was released (tagged on GitHub) but it seems to never have arrived on Maven Central. We are stuck with 8.3.0 on Maven Central. Any idea?

**Comment by sebfz1** [comment]
Hi Richard, you are right. Unfortunately it is pain to upload to Nexus
these days... I get "connection reset by peer" all the time while I'm
uploading... :(

**Comment by reckart** [comment]
Have you tried increasing the deployment retry count?

https://maven.apache.org/plugins/maven-deploy-plugin/deploy-mojo.html#retryFailedDeploymentCount

**Comment by sebfz1** [comment]
Thanks for the tip, will try asap!

**Comment by martin-g** [comment]
@sebfz1 Please let me know if I can do it for you!
I see 7.15.0 being staged at Sonatype OSS.

**Comment by sebfz1** [comment]
Right, 7.15.0 is staged but incomplete. I should have tried 10 times over
the past 2 weeks....
Will try again soon, maybe will I also try to take advantage of the
timezone as Maxim used to do (don't know what's the best time though...)

Thanks a lot, I will tell you if I need additional help on this!

>

**Comment by sebfz1** [comment]
After several retries, it finally passed! (during severe typhoon, lol)
Should be on Maven Central soon....
I will retry 7.15.0, crossing fingers....

**Comment by sebfz1** [comment]
7.15.0 passed too!
