### ISSUE TITLE
this.getCurrentRange is not a function on Android

### ISSUE THREAD

**Issue by sebawagner** [sebfz1/wicket-jquery-ui#315]
Testing the module on Android leads to an issue where some event notifiers don't seem to work:
![image](https://user-images.githubusercontent.com/5152064/80332928-70647c80-88a0-11ea-95f8-ef5e3cf3b797.png)

And looking through the console debug it looks like:
![image](https://user-images.githubusercontent.com/5152064/80332939-7c503e80-88a0-11ea-811c-1ec87a65c69e.png)

Is that a platform specific issue?

That is Chrome 81.0.4044.117 on Android 9
And wicket-jquery-ui version 9.0.0-M5

**Comment by sebawagner** [comment]
Its this line in the plugin:
https://github.com/sebfz1/wicket-jquery-ui/blob/wicket9.x/wicket-jquery-ui-plugins/src/main/resources/com/googlecode/wicket/jquery/ui/plugins/wysiwyg/resource/js/bootstrap-wysiwyg.js#L64

I'm not sure why it can't find the function defined on the bottom?
https://github.com/sebfz1/wicket-jquery-ui/blob/wicket9.x/wicket-jquery-ui-plugins/src/main/resources/com/googlecode/wicket/jquery/ui/plugins/wysiwyg/resource/js/bootstrap-wysiwyg.js#L181

Is "this" in this context maybe not referencing to the object ? Cause $( window ) hasn't been created using the "new" constructor ? So it won't find any methods that have been prototype'd into the object ?

**Comment by sebawagner** [comment]
Yep I'm pretty sure "this" is the problem. The context is different.
You can debug it and "this" is not pointing at the current Wysiwyg that the touch event is attached to. But pointing against "window" where there is no proto functions.

**Comment by martin-g** [comment]
Hi @sebawagner !

IMO this issue should be reported to bootstrap-wysiwyg.js project.
Wicket JQuery UI just adds integration with Wicket on top.

**Comment by sebawagner** [comment]
> Hi @sebawagner !
> 
> IMO this issue should be reported to bootstrap-wysiwyg.js project.
> Wicket JQuery UI just adds integration with Wicket on top.

But which one? I can find several projects with that name. Which one did wicket-jquery-ui fork/copy ? 

And actually wicket-jquery-ui hosts a raw source file. So - if I find the bootstrap-wysiwyg project this came from, how will this change be populated here?

**Comment by martin-g** [comment]
The link to the project is at the top of the JS file: https://github.com/sebfz1/wicket-jquery-ui/blob/ebd3d1655609e265456800c9c9b15b29784576d2/wicket-jquery-ui-plugins/src/main/resources/com/googlecode/wicket/jquery/ui/plugins/wysiwyg/resource/js/bootstrap-wysiwyg.js#L1

https://github.com/steveathon/bootstrap-wysiwyg 

The bad news is that there is no much activity in this project since 2018.

**Comment by sebawagner** [comment]
There is actually a fix proposed and committed in that repo:
https://github.com/steveathon/bootstrap-wysiwyg/commit/aa73cd30cdde28a7e4c9416b60009e9e46bf0588#diff-5533b3a46c8d44c5a0d1f3198ee1cd9a

But the fix doesn't work. I checked the fix.
The fix does if(!this.getCurrentRange)
This will never be true. So you could also just delete this method. It seems to have no effect on the overall functionality anyway. I'm not sure what it is supposed to do.

**Comment by sebawagner** [comment]
I've created an issue in their Repo: https://github.com/steveathon/bootstrap-wysiwyg/issues/152

But will you import those latest changes to get rid of the console error ?

**Comment by sebawagner** [comment]
Although not fixing the issue :) It at least stops your browser from making a funny noise when there is a console.error :)

**Comment by sebfz1** [comment]
Hi Sebastian, thanks for reporting the issue!
Maxim provided the fix. `9.0.0-M5.1` is now on its way to maven central...

**Comment by sebawagner** [comment]
Great thanks!
