### ISSUE TITLE
Auto-complete issue with Kendo/Chrome

### ISSUE THREAD

**Issue by reckart** [sebfz1/wicket-jquery-ui#317]
There seems to be an issue with Kendo failing to properly turn off Chrome's auto-complete/auto-fill functionality:

  https://github.com/telerik/kendo-ui-core/issues/4174

It seems this might be fixed in recent releases of Kendo.

I can see that the Wicket 9.x branch has recently been updated to a new Kendo. Are there any more updates of the Wicket 8.x line of this library planned?

**Comment by sebfz1** [comment]
Hi Richard, sure. I will do it this weekend!

**Comment by sebfz1** [comment]
Released 8.8.0, with Kendo UI 2020.2.513.
On its way to Maven Central...
