### ISSUE TITLE
AccordionPanel

### ISSUE THREAD

**Issue by vahida1157** [sebfz1/wicket-jquery-ui#319]
hello
i have one question about AccordionPanel
i searched about one of this parameters(Options)
but i can't find what is that and how i can use that and what is this options

**Comment by martin-g** [comment]
Hi,

On Wed, Jun 3, 2020 at 5:09 PM vahid <notifications@github.com> wrote:

> hello
> i have one question about AccordionPanel
> i searched about one of this parameters(Options)
> but i can't find what is that and how i can use that and what is this
> options
>

options is the JSON object with all the configuration settings that is
being passed to the JavaScript widget
For example:
var options = {width: "100px", height: "50%", onEvent: (evt) =>
{console.log(evt)}}
$(selector).accordion(options);

In Java code it is something like:
Options options = new Options();
options.set("width", "100px");
...

See http://www.7thweb.net/wicket-jquery-ui/tooltip/DefaultTooltipPage and
the source code below.

**Comment by vahida1157** [comment]
thanks for your answer
i think height style its necessary for accordion panel, isn't it?
and i have another question.
how i can change model of my accordion?
I want to keep open several accordion tabs together.
I mean, when I click on the tab, I don't want to close another tab.

**Comment by martin-g** [comment]
Hi,

On Thu, Jun 4, 2020 at 11:46 AM vahid <notifications@github.com> wrote:

> thanks for your answer
> i think height style its necessary for accordion panel, isn't it?
>
This was just an explanation how Options work. I'm not sure whether height
is needed for Accordion or not.
Please check
- http://www.7thweb.net/wicket-jquery-ui/accordion/DefaultAccordionPage
<http://www.7thweb.net/wicket-jquery-ui/accordion/DefaultAccordionPage?1>
 and http://jqueryui.com/demos/accordion/
- http://www.7thweb.net/wicket-jquery-ui/kendo/accordion/KendoAccordionPage
 and https://demos.telerik.com/kendo-ui/panelbar/index

> and i have another question.
> how i can change model of my accordion?
>
I want to keep open several accordion tabs together.
> I mean, when I click on the tab, I don't want to close another tab.
>
You should check how to do this with plain jQueryUI and then use Options to
tell Wicket JQuery UI to do it.

**Comment by sebfz1** [comment]
>  how i can change model of my accordion?

The Accordion (both jQuery UI and Kendo UI) takes a `IModel<List<ITab>> model` as a ctor argument.
You can update your model and reattach the component in ajax:

```
// for Kendo UI
target.add(accordion);

// for jQuery UI
accordion.setActiveTab(0).reload(target); // resets active tab and forces reload model
```

>  I mean, when I click on the tab, I don't want to close another tab.

For the Kendo UI accordion that's the default behavior
https://docs.telerik.com/kendo-ui/api/javascript/ui/panelbar/configuration/expandmode

For jQuery UI accordion, it seems not to be straightforward to get this behavior. AFAIS it is not just an option to activate or not.

**Comment by vahida1157** [comment]
Hello again.
I'm trying to use options in AccordionPanel but I have a problem.
It's my code.
```

1.     public void accordionPanel(List<T> object, WebMarkupContainer webMarkupContainer) {
2.         Options options = new Options();
3.         options.set("heightStyle", Options.asString("content"));
4.         options.set("classes.ui-accordion-header", "headAccordionStyle");
5.         AccordionPanel accordionPanel = new AccordionPanel("accordion", new TabListModel() {
6.             @Override
7.             protected List<ITab> load() {
8.                 List<ITab> tabs = new ArrayList<>();
9.                 object.forEach(obj -> {
10.                     ITab tab;
11.                     if (haveLazyLoadTab()) {
12.                         tab = getLazyTab(obj);
13.                     } else {
14.                         tab = getAbstractTab(obj);
15.                     }
16.                     tabs.add(tab);
17.                 });
18.                 return tabs;
19.             }
20.         }, options) {
21. 
22. 
23.             @Override
24.             public void renderHead(IHeaderResponse response) {
25.                 super.renderHead(response);
26. //                response.render(OnDomReadyHeaderItem.forScript(style()));
27.                 response.render(CssReferenceHeaderItem.forReference(new CssResourceReference(AccordionPanelUtils.class, "accordion.css")));
28.             }
29.         };
30.         accordionPanel.setOutputMarkupId(true);
31.         webMarkupContainer.addOrReplace(accordionPanel);
32.     }

```
When running this code, line 4 wasn't working and this is my error in the console:

> Uncaught ReferenceError: headAccordionStyle is not defined
    at HTMLDocument.<anonymous> (?3:72)
    at i (jquery-1.12.4-ver-8195A8C8C12FE76B1AF13FF30D4EC630.js:2)
    at Object.fireWith [as resolveWith] (jquery-1.12.4-ver-8195A8C8C12FE76B1AF13FF30D4EC630.js:2)
    at Function.ready (jquery-1.12.4-ver-8195A8C8C12FE76B1AF13FF30D4EC630.js:2)
    at HTMLDocument.K (jquery-1.12.4-ver-8195A8C8C12FE76B1AF13FF30D4EC630.js:2)

But "headAccordionStyle" is defined::

```

1. .headAccordionStyle {
2.     border-radius: 10px;
3.     background-image: linear-gradient(#2e86de 0px, #2176cc 100%);
4.     color: #ffffff;
5.     font-size: 18px;
6.     cursor: pointer;
7. }

``` 

How can I fix this problem?
thanks for spending your time to resolve my issue.

**Comment by sebfz1** [comment]
"headAccordionStyle" should be specified as a String (otherwise it means
it's a function name). Use Options.asString(""headAccordionStyle"), and it
should be good.

Please note that GitHub issues is for reporting bugs. For help or questions
please use the dedicated google forum or even the Wicket mailing list...
