### ISSUE TITLE
release 9.1.0?

### ISSUE THREAD

**Issue by reiern70** [sebfz1/wicket-jquery-ui#321]
Hi,

We need a 9.1.0 release for our project. 

@sebfz1 

Do you think it would be good to move this project to wicketstuff?

**Comment by reiern70** [comment]
https://github.com/sebfz1/wicket-jquery-ui/pull/322

**Comment by sebfz1** [comment]
Hi Ernesto!

I planned to do it next weekend because it requires me to test it before
(following the discussions about CSP mainly)...
If it's urgent for you I can try to manage tomorrow... Please let me know.
I am not closed about moving the project to wicket-stuff if it make sense.
Not sure it is the case, it will probably require a non negligeable amount
of work (I'm thinking about the demo site for instance)...
In another hand, I do not have any issue giving you and Maxim the key to
release the project from here.

WDYT?

**Comment by reiern70** [comment]
> Hi Ernesto! I planned to do it next weekend because it requires me to test it before (following the discussions about CSP mainly)... If it's urgent for you I can try to manage tomorrow... Please let me know. I am not closed about moving the project to wicket-stuff if it make sense. Not sure it is the case, it will probably require a non negligeable amount of work (I'm thinking about the demo site for instance)... In another hand, I do not have any issue giving you and Maxim the key to release the project from here. WDYT?

Hi,

Many thanks for your answer. No need to do it now. We can wait for weekend. I can also try to help during this week as our project depends on your library. Project compiles and installs (mvn clean install) against 9.1.x. Please let me know how can I help.

**Comment by sebfz1** [comment]
The only help I would need would be to upgrade wicket version to 9.0.1 and
test some samples (mainly kendo) to see if there is no issue with CSP.
Everything is currently working fine with 9.0.0 so I guess that's the only
thing to have a look at...
Btw, there is no need to upgrade the project version in the poms from
snapshot to final, it is automatically done by mvn release

>

**Comment by reiern70** [comment]
@sebfz1 

As far as I can see Kendo UI integration is working.

![image](https://user-images.githubusercontent.com/462655/95808437-6ad9e200-0cda-11eb-97fb-e5c15053c4d1.png)

![image](https://user-images.githubusercontent.com/462655/95808494-89d87400-0cda-11eb-949a-057c457912a2.png)

![image](https://user-images.githubusercontent.com/462655/95808518-9d83da80-0cda-11eb-9217-cd8da53717e9.png)

![image](https://user-images.githubusercontent.com/462655/95808559-b5f3f500-0cda-11eb-94d5-0b155db1bfdf.png)

![image](https://user-images.githubusercontent.com/462655/95808646-ed62a180-0cda-11eb-9a9a-c6f51dea9eb0.png)

![image](https://user-images.githubusercontent.com/462655/95808678-ffdcdb00-0cda-11eb-87b1-6fff0871ddb7.png)

![image](https://user-images.githubusercontent.com/462655/95808711-17b45f00-0cdb-11eb-8302-70067c16c6f4.png)

![image](https://user-images.githubusercontent.com/462655/95808746-24d14e00-0cdb-11eb-9f0b-a539449cc8d8.png)

![image](https://user-images.githubusercontent.com/462655/95808799-416d8600-0cdb-11eb-8edc-fe7a8bdb8349.png)

Also Jequery UI


![image](https://user-images.githubusercontent.com/462655/95808829-5813dd00-0cdb-11eb-8c32-1cb7398181b5.png)

These we are using extensibly. Thus we will provided feedback if something is broken.

**Comment by reiern70** [comment]
Only some warnings in console

![image](https://user-images.githubusercontent.com/462655/95809020-c48edc00-0cdb-11eb-8a17-ab93299d1ba4.png)

**Comment by sebfz1** [comment]
Great! Thank you so much Ernesto!!

>

**Comment by reiern70** [comment]
> Great! Thank you so much Ernesto!!
> […](#)

Thanks to you for maintaining the software we use...

**Comment by reiern70** [comment]
Let me know if any more actions are needed from my side.

**Comment by sebfz1** [comment]
Hi Ernesto! 
`9.1.0` is on its way to maven central.
Thanks for your help testing the upgrade to wicket 9.1.0!

**Comment by reiern70** [comment]
Thanks to you!
