### ISSUE TITLE
Apache Wicket 6.x to 9.1 migration, AJAX com.googlecode.wicket.kendo.ui.form.autocomplete.AutoCompleteTextField stopped working

### ISSUE THREAD

**Issue by appsofteng** [sebfz1/wicket-jquery-ui#326]
Hi,

I used com.googlecode.wicket.kendo.ui.form.autocomplete.AutoCompleteTextField with Apache Wicket 6.x. It is added in a WebMarkupContainer in the onBeforeRender(). I migrated to Wicket 9.1 including Wicket JQuery UI 9.1. The rendering of the HTML works fine, but there are these problems

- the Javascript that gets the autocomplete choices from the server starts working only after the page is reloaded e.g. by clicking the reload button of the browser
 - the Javascript that should be called when a choice is selected is not called at all

I compared the AJAX Javascript between Wicket 6.x and 9.1. It seems that the component paths in the new version are a bit broken but didn't find why.

Does anybody have an idea as to what is wrong?

Thank you.

More details:
https://stackoverflow.com/questions/65270206/apache-wicket-6-x-to-9-1-migration-ajax-com-googlecode-wicket-kendo-ui-form-aut

**Comment by sebfz1** [comment]
I will try to have a look asap. In the meantime, can you run the samples
against the wicket-9.x branch to see it it's repro?

**Comment by appsofteng** [comment]
I tried it with 9.1.1-SNAPSHOT, the problem is the same.

**Comment by sebfz1** [comment]
I didn't repro the first point, it seems to work for me using the samples
app.
However, I can repro the second point. Working on it....

**Comment by sebfz1** [comment]
The problem was actually not related to Wicket-9 in particular, but rather the version of Kendo UI which seemed to have change the select event payload. I fixed it in all versions, and will roll a patch-release now...
It also might solves your fist issue. If it is not the case, please create a quickstart that reproduce the issue.

**Comment by sebfz1** [comment]
Released `9.2.0`
