### ISSUE TITLE
List comes as a single element, comma separated

### ISSUE THREAD

**Issue by pekour** [sebfz1/wicket-jquery-ui#331]
In Wicket for Kendo 8.11.1 selected keys of multiple rows come as a comma-separated single list element
```public void onChecked(AjaxRequestTarget target, List<String> selectedKeys)```

**Comment by sebfz1** [comment]
Yes, that's the purpose. Why do you think it is an issue?

**Comment by sebfz1** [comment]
Maybe I didn't understood the issue correctly. I'll have a look...

**Comment by sebfz1** [comment]
Well spotted Alexander!
I fixed it, and will release 8.12.0 in the coming days

**Comment by pekour** [comment]
Thank you!
