### ISSUE TITLE
AjaxMultiSelect / unknown but important parameter

### ISSUE THREAD

**Issue by Patrick1701** [sebfz1/wicket-jquery-ui#334]
Hi Sebastien,
do you know, which code creates the parameter, named like the multiselect itself?

Sometimes its missing and the multi select ajax feature is not working. The parameter 'value' is always present.
And it seems this parameter is the implemented one. But I cannot get it, where the other parameter comes from?

The parameter 'value' does not update the internal model-object. Thats the bug, I'm searching for...

kind regards
Patrick

![grafik](https://user-images.githubusercontent.com/3428658/115517963-fdf66480-a287-11eb-9d75-55a02ffbeccb.png)

**Comment by Patrick1701** [comment]
@sebfz1 Ping :-)

**Comment by sebfz1** [comment]
Hi Patrick,

The value is provided to respect the contract with the on-change event, like stated in the doc:
https://docs.telerik.com/kendo-ui/api/javascript/ui/multiselect/events/change

But it is *not* used to update the model here and is not intended to - IIRC. The `OnChangeAjaxBehavior` is the generic behavior aim to be bound to on-change. We may need to use or retransmit the value being retrieved or not (the AutoComplete for instance)

The components (like `DropDown`, `ComboBox`, `MultiSelect`, etc) are `FormComponent`. The Wicket's internal are in charge of retrieving/converting the data (and then the model is updated). The parameter you are seeing (having the name of the component) is the one the form supplies. 
If your component is not in a Form, that might explain your issue...

**Comment by Patrick1701** [comment]
Hi Sebastien,

Question:
Ok, but why does the toplevel component MultiSelect tries to read the data using convertInput() -> getInputAsArray() -> getParameterValues(getInputName())?

And: It don't gets the parameter 'value' sent by the request, because the getInputName() has a random name, given by wicket for reading form submits/parameters.
If I override the method getInputName() and set a hard return value "value", the MultiSelect behaves as expected.
Then the getParameterValues() retrieves the value 'value' sent via ajax and writes it into the modelobject.

Is it a bug?
Or can it be a feature request? What do you think?

Suggestion:
If I use the MultiSelect in a form submit case, but maps it incorrectly to a &lt;div&gt; instead of &lt;select&gt;, the form submit does not work correct.
You should provide a check onComponentTag() like wicket does for different components, when mapping it to wrong mark-up tags.

(The reason: If not an original <select> is used, kendo displays:none it. So it is not part of the form submit anymore. If you use &lt;select&gt; it works.)

kind regards
Patrick

**Comment by Patrick1701** [comment]
@sebfz1 Ping :-)

**Comment by sebfz1** [comment]
Oh damned, thanks for the recall!
I have been kind or very busy lately, I will have some time to look at it
tomorrow (crossing fingers).
Please reping early next week if I didn't replied in the meantime!

**Comment by Patrick1701** [comment]
@sebfz1 I played a bit the last two hours, and all my mentioned problems disappear, when using the correct tag &lt;select&gt; in the markup file.
So, I think, you could just add the following code to your MultiSelects classes, to prevent a client programer uses it wrong.

```
   @Override
    protected void onComponentTag(ComponentTag tag) {

        // Must be attached to a select tag
        checkComponentTag(tag, "select");

        super.onComponentTag(tag);
    }

```

I think, you can close this issue after this improvement.
Patrick

**Comment by sebfz1** [comment]
Yes, it has to be a `select` (form component). I added the suggested fix (8.x and 9.x branches for now).
Which wicket version are you now on?

**Comment by Patrick1701** [comment]
@sebfz1 We are on 8.10.0 and unfortunately we will stay there for some months+.

**Comment by Patrick1701** [comment]
@sebfz1 Ah, the open 8.x branch is at 8.12.1-SNAPSHOT... ok, I see.

**Comment by sebfz1** [comment]
Ok, I will try to cherry-pick the commits on a new branch from this
release...

**Comment by Patrick1701** [comment]
@sebfz1 No need. I applied the component check in our sub-class of yours. Just release it into the 8,x and 9.x Branch.
More important to me is the feature #336 in an 8.10.x Version.

**Comment by sebfz1** [comment]
Hi Patrick, I released `8.13.0` and `9.5.0`.

If you need a specific version, please:
- Clone the repo
- Checkout your own branch from the release tag you want 
- Apply the changes you need (you can try to cherry-pick) 
- Test locally everything works as expected
- Then tell me where is your repo/branch and I'll double check and release a special version for you

**Comment by Patrick1701** [comment]
@sebfz1 I will have a try, to update to 8.13.0, first. I should do it anyway...
Did you deploy 8.13.0 on maven central?

**Comment by sebfz1** [comment]
Yes, I deployed on Maven Central
