### ISSUE TITLE
migrate from 6.12 to 8.12

### ISSUE THREAD

**Issue by giorgioUnimi** [sebfz1/wicket-jquery-ui#337]
Hi,I'am giorgio and I have to migrate a wicket project from 6 to 8 . I have a  problem in my code with wicket jquery core  using the class IJQueryLibrarySettings because is not present in wicket-jquery 8 . How can i do ? where I can fin migration infos to migrate from wicket-jquery 6 to 8 . I have choose 8 because the project use also apache wicket and I can't migrate to apache wicket 9 due to I can use java 11 so I decide to migrate to apache wicket 8 and wicket-jquqery 8. Thanks in advance for every infos . Bye

**Comment by sebfz1** [comment]
Hi Giorgio,

`IJQueryLibrarySettings` has been renamed to `JQueryLibrarySettings`.

I do not have migration guides per se, I usually used to publish the changelog with the release notes.
You can scroll/browse from here: https://github.com/sebfz1/wicket-jquery-ui/releases?after=wicket-jquery-ui-8.0.0-M9.2

If you have other questions, please ask in the Forum (http://groups.google.com/group/wicket-jquery-ui/) or in the Wicket ML.
The Github Issues page is reserved for issues.
