### ISSUE TITLE
AutoCompleteChoiceModelBehavior sets wrong index

### ISSUE THREAD

**Issue by stekuth** [sebfz1/wicket-jquery-ui#342]
You used to start with index 1 in AutoCompleteChoiceModelBehavior before the change to JSONObject
So imho this line should be changed, to add 1:  object.put("id", Integer.toString(index **+ 1**)); /* 'id' is a reserved word */
Now the code in AutoCompleteBehavior still subtracts 1 from the returned index, so the wrong entry is selected

greetings!
Stefan

**Comment by sebfz1** [comment]
Just had a look at the issue, well done!
I will remove the "substracts 1" from the `SelectEvent` then, and release asap...

**Comment by sebfz1** [comment]
Deployed `9.8.0-SNAPSHOT`. If you can test it this week that would be great, I will release this week-end. If you need `8.x` instead please let me know...

**Comment by stekuth** [comment]
Hello, thanks for fixing this - I tested it and it works!
greetings

**Comment by stekuth** [comment]
could you also please push a 9.8.0 release including this fix to maven-repo?

**Comment by sebfz1** [comment]
Hi Stefan,

I was about to release yesterday, but I came across an issue with the last
release of kendo ui, and I don't know yet if it's their mistake or my web
application design... I need to test further.
If you need a release asap I can deploy tonight without the latest version
of kendo ui, and release 9.8.1 later hopefully...

**Comment by sebfz1** [comment]
Actually my spare time will be almost null for the next 10 days so I released `9.8.0`. 
Should be available in Maven Central soon...
