### ISSUE TITLE
Broken style in dialogue box between 8.11 and 9.8

### ISSUE THREAD

**Issue by tverdokhlebd** [sebfz1/wicket-jquery-ui#345]
The difference in the style in a dialogue box:

8.11.1:
![8 11](https://user-images.githubusercontent.com/10245067/160883593-c8e28f49-1706-46c7-bfb0-12ed895df5ef.PNG)
org.apache.wicket 8.13
com.googlecode 8.11.1 (wicket-kendo-ui, wicket-kendo-ui-theme-material, wicket-kendo-ui-culture)

9.8:
![9 8](https://user-images.githubusercontent.com/10245067/160883620-afc9c034-705d-41d4-ab21-99048601544d.PNG)
org.apache.wicket 9.8.0
com.googlecode 9.8.0 (wicket-kendo-ui, wicket-kendo-ui-theme-material, wicket-kendo-ui-culture)

Kendo UI JS 2021.1.224

Is it an issue for this repo?

**Comment by sebfz1** [comment]
Thanks for reporting this! I'll investigate...

**Comment by tverdokhlebd** [comment]
@sebfz1 Any news?

**Comment by sebfz1** [comment]
So sorry I didn't replied earlier. I tested some time ago already and I
really couldn't reproduce the issue.
I was thinking it should be a conflict between the api version and the
theme version, but I didn't get a chance to test.
Please double check on your end, and please create a quickstart that repro
the issue so I have something to work with.
Worth to note that the latest version of kendo ui jas similar issues (on
combobox/dropdown and I didn't release it for this reason...

**Comment by tverdokhlebd** [comment]
So, I applied Wicket 9.8 (wicket-kendo-ui, wicket-kendo-ui-theme-material, wicket-kendo-ui-culture) and the latest version of Kendo UI JS 2022.1.412. 

The result is:
![delete_container_2](https://user-images.githubusercontent.com/10245067/166232687-1371af91-a9c9-4606-a8cd-ef2812bef55f.PNG)
Something is different compared to Wicket 8.11.1, the distance between icon and button, but, the title bar looks normal.

However, I got another problem with combobox/dropdown components:
![image](https://user-images.githubusercontent.com/10245067/166233282-9944df96-f9b8-4136-9d78-96d8fcdc8330.png)
Is this the problem, that you have noted?

**Comment by sebfz1** [comment]
Hi,

Yes, looks like the issue I noted.
As a side note, you cannot mix js and theme versions. They have to be the
same. You don't need to provide the kendo js (core), it's already bundled.
Except if it's to provide the kendo-ui-all.js. In that case be sure it's
the same version than the theme. You have the versions table in the readme.

**Comment by tverdokhlebd** [comment]
@sebfz1 , could you tell me, what is the version of Kendo UI for Wicket 9.8?
There is a version for only 9.7 in the readme.

**Comment by sebfz1** [comment]
Strange that it's not up to date...
The version should be 2021.3.1207

**Comment by tverdokhlebd** [comment]
Checked on Wicket 9.8 with the correct version (2021.3.1207) of Kendo UI JS. The problem described above does not reproduce.

**Comment by tverdokhlebd** [comment]
@sebfz1 After updating to 2021.3.1207, found strange behavior for tabs:
![1](https://user-images.githubusercontent.com/10245067/167434597-0373c72e-c75e-42fa-a6b4-f87ac3aad80a.PNG)
Non selected tab is filled with white color, and the whole background color is blue (Should be white or transparent).

**Comment by tverdokhlebd** [comment]
@sebfz1 could you check this in your free time?

**Comment by sebfz1** [comment]
Hi have upgraded to `kendo-ui-2022.2.510`, please give a try to `9.9.1-SNAPSHOT`.
There is still some other issues with dropdown and co I need to investigate. Any help is very welcome!
