### ISSUE TITLE
Jquery 1.13.1 is not found in wicket8.x

### ISSUE THREAD

**Issue by Ragulrangarajan** [sebfz1/wicket-jquery-ui#349]
Able to see Jquery UI version as 1.13.1 in [Readme](https://github.com/sebfz1/wicket-jquery-ui/blob/wicket8.x/README.md) of wicket8.x but the actual Jquery UI of wicket8.x still points to [1.12.1](https://github.com/sebfz1/wicket-jquery-ui/blob/wicket8.x/wicket-jquery-ui/src/main/resources/com/googlecode/wicket/jquery/ui/resource/jquery-ui.min.js) 
Is this expected?

<html>
<body>
<h3 dir="auto" style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 1.25em; font-weight: 600; line-height: 1.25; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Versions</h3>

wicket-jquery-ui | Wicket | jQuery UI
-- | -- | --
8.13.0 | 8.13.0 | 1.13.1
8.12.0 | 8.12.0 | 1.12.1

</body>
</html>

Able to see an upgrade ticket https://github.com/sebfz1/wicket-jquery-ui/pull/348 that was done only in wicket9.x. 
Is there any plan to upgrade in wicket8.x ?

**Comment by sebfz1** [comment]
Right, I didn't released yet. IIRC I asked for testing the snapshot but I
didn't get any feedback...

I'll try to release this week, thanks for the reminder!

**Comment by Ragulrangarajan** [comment]
Thanks for the confirmation @sebfz1  Waiting for the fix.

Like to know whether are we planning to upgrade Jquery 1.13.1 (as mentioned in Readme) or 1.13.2 (latest).

**Comment by sebfz1** [comment]
`8.14.0` (with jquery-ui `1.13.2`) is released
