### ISSUE TITLE
Create branch for Wicket 10.x / Jakarta EE?

### ISSUE THREAD

**Issue by ilgrosso** [sebfz1/wicket-jquery-ui#353]
There is no current branch yet for Wicket 10.x: while not reelased yet, Wicket `10.0.0-M1-SNAPSHOT` works with Jakarta EE namespace.

**Comment by sebfz1** [comment]
`wicket10.x` branch created

**Comment by ilgrosso** [comment]
thanks @sebfz1 : are `10.0.0-SNAPSHOT` artifacts published somewhere?

**Comment by sebfz1** [comment]
Not yet, but I can do it shortly. Please remind me if you don't have news
in a couple of days...

**Comment by ilgrosso** [comment]
Thank you!

**Comment by ilgrosso** [comment]
@sebfz1 ping :-)

I can't see `10.0.0-SNAPSHOT` yet in https://oss.sonatype.org/content/repositories/snapshots/com/googlecode/wicket-jquery-ui/wicket-jquery-ui/

**Comment by sebfz1** [comment]
Hi Francesco, 10.0.0-SNAPSHOT should be available now!
