### ISSUE TITLE
onError(AjaxRequestTarget, DialogButton) of AbstractWizard is final

### ISSUE THREAD

**Issue by Patrick1701** [sebfz1/wicket-jquery-ui#357]
Hi Sebastien,
could you please allow overriding the method, in order to get a callback for this case.

kind regards
Patrick

**Comment by Patrick1701** [comment]
Ups. Duplicate... https://github.com/sebfz1/wicket-jquery-ui/issues/235

Which weekend did you have a look at it? :-D

**Comment by sebfz1** [comment]
I also released `9.12.0`
