### ISSUE TITLE
Release from wicket10.x ?

### ISSUE THREAD

**Issue by ilgrosso** [sebfz1/wicket-jquery-ui#358]
Now that Wicket 10.0.0-M1 is out, any chance to cut a release from the `wicket10.x` branch here?

**Comment by sebfz1** [comment]
Hi Francesco, I'm currently in vacation. I'll try to release it end of next
week!..

**Comment by ilgrosso** [comment]
Sure, thank you @sbriquet !

**Comment by ilgrosso** [comment]
@sebfz1 is there any update?

FYI we have now both WicketStuff 10.0.0-M1 and Wicket-Bootstrap 7.0.0 released, all based on Wicket 10.0.0-M1:

* https://github.com/wicketstuff/core/releases/tag/wicketstuff-core-10.0.0-M1
* https://github.com/l0rdn1kk0n/wicket-bootstrap/releases/tag/bootstrap-parent-7.0.0

**Comment by sebfz1** [comment]
I've a lot of new javadoc errors that now prevent me to release... Still,
I'm on it, will try to release asap ...

**Comment by ilgrosso** [comment]
Great, thank you!

**Comment by martin-g** [comment]
https://github.com/apache/wicket/blob/master/pom.xml#L1068
`<failOnError>false</failOnError>` and leave it for another day :-)

**Comment by sebfz1** [comment]
Thank you very much, Martin!
`10.0.0-M1` is now released!

**Comment by ilgrosso** [comment]
Thank you @sebfz1
I can see now `10.0.0-M1` in Maven central for most components; however, some are not available, for example https://repo1.maven.org/maven2/com/googlecode/wicket-jquery-ui/wicket-kendo-ui/

**Comment by sebfz1** [comment]
I will have a look, maybe the sync is not completed yet?

**Comment by ilgrosso** [comment]
Don't know, in my experience usually all the same modules for the same group / version are published at the same time

**Comment by ilgrosso** [comment]
@sebfz1 sorry for the noise, all seems to be published now, thanks again
